import { useCallback, useEffect, useMemo, useState } from "react";
import { apiGet, apiPatch, apiPost, apiUpload } from "../../../utils/api";
import "./compliance-center.css";

const EMPTY_DASH = { summary:{}, profiles:[], missingRequirements:[], documents:[], expiring:[], findings:[], audits:[] };
const STATUS_LABELS = { ACTIVE:"Geçerli", EXPIRING:"Yaklaşıyor", CRITICAL:"Kritik", EXPIRED:"Süresi Geçti", ARCHIVED:"Arşiv" };
const SEVERITY_LABELS = { CRITICAL:"Kritik", HIGH:"Yüksek", MEDIUM:"Orta", LOW:"Düşük" };
const TABS = {
  "denetim-genel":"OVERVIEW", "denetim-dosyalari":"AUDITS", "denetim-evraklar":"DOCUMENTS", "denetim-standartlar":"STANDARDS",
  "denetim-capa":"CAPA", "denetim-takvim":"CALENDAR", "denetim-ayarlar":"SETTINGS",
};

function dateText(value){ if(!value)return"-"; const d=new Date(`${String(value).slice(0,10)}T00:00:00`); return Number.isNaN(d.getTime())?String(value):d.toLocaleDateString("tr-TR"); }
function cls(value){ return String(value||"").toLowerCase().replace(/_/g,"-"); }
function payloadData(value, fallback){ return value?.data ?? fallback; }
function today(){ return new Date().toISOString().slice(0,10); }

export default function ComplianceCenterPage({ activeTab="denetim-genel" }){
  const section=TABS[activeTab]||"OVERVIEW";
  const [dash,setDash]=useState(EMPTY_DASH),[profiles,setProfiles]=useState([]),[tasks,setTasks]=useState([]),[calendar,setCalendar]=useState([]),[systemCandidates,setSystemCandidates]=useState([]);
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const [q,setQ]=useState(""),[stateFilter,setStateFilter]=useState("ALL"),[showDocForm,setShowDocForm]=useState(false);
  const [docForm,setDocForm]=useState({title:"",category:"Genel",issuer:"",documentNo:"",issueDate:today(),expiresAt:"",reminderDays:10,ownerDepartment:"",requirementId:""});
  const [docFile,setDocFile]=useState(null),[showFindingForm,setShowFindingForm]=useState(false),[showAuditForm,setShowAuditForm]=useState(false);
  const [findingForm,setFindingForm]=useState({title:"",severity:"MEDIUM",description:"",correctiveAction:"",dueDate:""});
  const [auditForm,setAuditForm]=useState({name:"",profileId:"",auditType:"CUSTOMER",plannedDate:"",auditorName:"",notes:""});
  const [profileForm,setProfileForm]=useState({name:"",code:"",version:"CUSTOM",description:""});
  const [selectedProfile,setSelectedProfile]=useState("");
  const [requirementForm,setRequirementForm]=useState({title:"",code:"",category:"Genel",ownerDepartment:"",warningDays:10,criticalDays:3,mandatory:true});
  const [applicabilityForm,setApplicabilityForm]=useState({requirementId:"",title:"",state:"APPLICABLE",reason:""});
  const loadAll=useCallback(async()=>{
    setLoading(true); setMessage("");
    try{
      const extra=section==="OVERVIEW"?apiGet("/compliance/tasks",{}, {timeoutMs:10000}):section==="STANDARDS"?apiGet("/compliance/profiles",{}, {timeoutMs:15000}):section==="CALENDAR"?apiGet("/compliance/calendar",{}, {timeoutMs:10000}):Promise.resolve({data:[]});
      const evidence=section==="OVERVIEW"?apiGet("/compliance/system-evidence-candidates",{}, {timeoutMs:12000}):Promise.resolve({data:[]});
      const [d,x,e]=await Promise.all([apiGet("/compliance/dashboard",{}, {timeoutMs:15000}),extra,evidence]);
      setDash(payloadData(d,EMPTY_DASH));
      if(section==="OVERVIEW"){setTasks(payloadData(x,[]));setSystemCandidates(payloadData(e,[]));}
      if(section==="STANDARDS"){const rows=payloadData(x,[]);setProfiles(rows);setSelectedProfile(prev=>prev||rows[0]?.id||"");}
      if(section==="CALENDAR")setCalendar(payloadData(x,[]));
    }catch(error){ setMessage(`Hata: ${error?.message||"Denetim verileri alınamadı."}`); }
    finally{ setLoading(false); }
  },[section]);

  useEffect(()=>{ loadAll(); },[loadAll]);
  const docs=useMemo(()=>dash.documents||[],[dash.documents]);
  const filteredDocs=useMemo(()=>docs.filter(row=>{
    const hay=`${row.title||""} ${row.category||""} ${row.document_no||""} ${row.issuer||""}`.toLocaleLowerCase("tr-TR");
    return (!q||hay.includes(q.toLocaleLowerCase("tr-TR")))&&(stateFilter==="ALL"||row.state===stateFilter);
  }),[docs,q,stateFilter]);
  const profile=useMemo(()=>profiles.find(row=>String(row.id)===String(selectedProfile))||profiles[0]||null,[profiles,selectedProfile]);

  async function createDocument(event){
    event.preventDefault(); if(!docForm.title.trim())return setMessage("Hata: Evrak adı zorunlu."); setBusy(true);
    try{
      const created=await apiPost("/compliance/documents",docForm); const id=created?.data?.id;
      if(id&&docFile){ const form=new FormData(); form.append("file",docFile); await apiUpload(`/compliance/documents/${id}/upload`,form); await apiPost(`/compliance/documents/${id}/auto-link`,{}); }
      setDocForm({title:"",category:"Genel",issuer:"",documentNo:"",issueDate:today(),expiresAt:"",reminderDays:10,ownerDepartment:"",requirementId:""}); setDocFile(null); setShowDocForm(false);
      setMessage("Evrak kaydedildi ve takip sistemine alındı."); await loadAll();
    }catch(error){setMessage(`Hata: ${error?.message||"Evrak kaydedilemedi."}`)} finally{setBusy(false)}
  }

  async function createAudit(event){event.preventDefault();setBusy(true);try{await apiPost("/compliance/audits",auditForm);setAuditForm({name:"",profileId:"",auditType:"CUSTOMER",plannedDate:"",auditorName:"",notes:""});setShowAuditForm(false);setMessage("Denetim dosyası oluşturuldu.");await loadAll();}catch(error){setMessage(`Hata: ${error?.message||"Denetim dosyası oluşturulamadı."}`)}finally{setBusy(false)}}
  async function runAi(){ setBusy(true); try{const result=await apiPost("/compliance/ai-scan",{});setMessage(result?.data?.summary||"Akıllı kontrol tamamlandı.");await loadAll();}catch(error){setMessage(`Hata: ${error?.message||"AI kontrolü yapılamadı."}`)}finally{setBusy(false)} }
  async function createFinding(event){event.preventDefault();setBusy(true);try{await apiPost("/compliance/findings",findingForm);setFindingForm({title:"",severity:"MEDIUM",description:"",correctiveAction:"",dueDate:""});setShowFindingForm(false);setMessage("Düzeltici faaliyet açıldı.");await loadAll();}catch(error){setMessage(`Hata: ${error?.message||"CAPA oluşturulamadı."}`)}finally{setBusy(false)}}
  async function closeFinding(id){setBusy(true);try{await apiPatch(`/compliance/findings/${id}`,{status:"CLOSED"});setMessage("CAPA kapatıldı.");await loadAll();}catch(error){setMessage(`Hata: ${error?.message||"CAPA kapatılamadı."}`)}finally{setBusy(false)}}
  async function createProfile(event){event.preventDefault();setBusy(true);try{await apiPost("/compliance/profiles",profileForm);setProfileForm({name:"",code:"",version:"CUSTOM",description:""});setMessage("Yeni denetim standardı oluşturuldu.");await loadAll();}catch(error){setMessage(`Hata: ${error?.message||"Standart oluşturulamadı."}`)}finally{setBusy(false)}}
  async function createRequirement(event){event.preventDefault();if(!profile?.id)return;setBusy(true);try{await apiPost(`/compliance/profiles/${profile.id}/requirements`,requirementForm);setRequirementForm({title:"",code:"",category:"Genel",ownerDepartment:"",warningDays:10,criticalDays:3,mandatory:true});setMessage("Yeni gereklilik eklendi.");await loadAll();}catch(error){setMessage(`Hata: ${error?.message||"Gereklilik eklenemedi."}`)}finally{setBusy(false)}}
  async function saveApplicability(event){event.preventDefault();if(!applicabilityForm.requirementId)return;setBusy(true);try{await apiPatch(`/compliance/requirements/${applicabilityForm.requirementId}/applicability`,{state:applicabilityForm.state,reason:applicabilityForm.reason});setApplicabilityForm({requirementId:"",title:"",state:"APPLICABLE",reason:""});setMessage("Uygulanabilirlik kararı kaydedildi.");await loadAll();}catch(error){setMessage(`Hata: ${error?.message||"Uygulanabilirlik kaydedilemedi."}`)}finally{setBusy(false)}}
  async function toggleProfileReadiness(){if(!profile?.id)return;setBusy(true);try{const next=profile.readinessEnabled===false;await apiPatch(`/compliance/profiles/${profile.id}`,{metadata:{...(profile.metadata||{}),readinessEnabled:next}});setMessage(next?"Standart hazırlık skoruna dahil edildi.":"Standart katalog moduna alındı; genel skoru etkilemeyecek.");await loadAll();}catch(error){setMessage(`Hata: ${error?.message||"Standart durumu değiştirilemedi."}`)}finally{setBusy(false)}}
  async function verifySystemEvidence(row){setBusy(true);try{await apiPost("/compliance/system-evidence/verify",row);setMessage(`${row.title} ortak kanıt olarak doğrulandı.`);await loadAll();}catch(error){setMessage(`Hata: ${error?.message||"ERP kanıtı doğrulanamadı."}`)}finally{setBusy(false)}}
  async function markTaskDone(id){setBusy(true);try{await apiPatch(`/compliance/tasks/${id}`,{status:"DONE"});await loadAll();}catch(error){setMessage(`Hata: ${error?.message||"Görev tamamlanamadı."}`)}finally{setBusy(false)}}

  const s=dash.summary||{};
  if(loading)return <div className="content-card compliance-loading"><h3>Denetim Merkezi hazırlanıyor</h3><p>Evraklar, süreler ve standartlar kontrol ediliyor...</p></div>;

  return <div className="compliance-page">
    <header className="compliance-hero">
      <div><small>DENETİM & UYGUNLUK / AKILLI EVRAK TAKİP</small><h1>Denetim Merkezi</h1><p>Disney, Sedex/SMETA, SLCP, Inditex/Zara, ZDHC, Higg FEM, OEKO-TEX, WRAP, amfori BSCI ve özel denetimler tek ortak kanıt sisteminde.</p></div>
      <div className="compliance-actions"><button onClick={loadAll} disabled={busy}>Yenile</button><button className="primary" onClick={()=>setShowDocForm(true)} disabled={busy}>+ Yeni Evrak</button><button className="ai" onClick={runAi} disabled={busy}>✦ AI Akıllı Kontrol</button></div>
    </header>
    {message&&<div className={`compliance-banner ${message.startsWith("Hata:")?"bad":"good"}`}>{message}</div>}

    {showDocForm&&<form className="compliance-form-card" onSubmit={createDocument}><div className="form-title"><div><h3>Yeni Evrak</h3><p>Dosyayı yükle; süre ve sorumluyu belirle. Sistem uygun standartlarla otomatik eşleştirebilir.</p></div><button type="button" onClick={()=>setShowDocForm(false)}>Kapat</button></div>
      <div className="compliance-form-grid"><label>Evrak Adı<input value={docForm.title} onChange={e=>setDocForm(v=>({...v,title:e.target.value}))} required/></label><label>Kategori<input value={docForm.category} onChange={e=>setDocForm(v=>({...v,category:e.target.value}))}/></label><label>Veren Kurum<input value={docForm.issuer} onChange={e=>setDocForm(v=>({...v,issuer:e.target.value}))}/></label><label>Belge No<input value={docForm.documentNo} onChange={e=>setDocForm(v=>({...v,documentNo:e.target.value}))}/></label><label>Belge Tarihi<input type="date" value={docForm.issueDate} onChange={e=>setDocForm(v=>({...v,issueDate:e.target.value}))}/></label><label>Son Geçerlilik<input type="date" value={docForm.expiresAt} onChange={e=>setDocForm(v=>({...v,expiresAt:e.target.value}))}/></label><label>Uyarı (gün)<input type="number" min="1" value={docForm.reminderDays} onChange={e=>setDocForm(v=>({...v,reminderDays:Number(e.target.value)}))}/></label><label>Sorumlu Bölüm<input value={docForm.ownerDepartment} onChange={e=>setDocForm(v=>({...v,ownerDepartment:e.target.value}))}/></label><label className="wide">Dosya<input type="file" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx,.xml,.zip" onChange={e=>setDocFile(e.target.files?.[0]||null)}/></label></div>
      <div className="form-footer"><span>Varsayılan uyarı: son tarihten 10 gün önce.</span><button className="primary" type="submit" disabled={busy}>Kaydet ve Takibe Al</button></div>
    </form>}
    {section==="OVERVIEW"&&<>
      <div className="compliance-metrics">
        <div className="score"><span>Hazırlık Skoru</span><b>%{s.readinessScore??0}</b><small>Genel denetim hazırlığı</small></div>
        <div><span>Eksik Evrak</span><b>{s.missingRequirements??0}</b><small>Zorunlu gereklilik</small></div>
        <div><span>90 / 30 Gün</span><b>{s.expiring90Days??0} / {s.expiring30Days??0}</b><small>Yaklaşan yenilemeler</small></div><div><span>10 / 7 / 3 Gün</span><b>{s.expiring10Days??0} / {s.expiring7Days??0} / {s.expiring3Days??0}</b><small>Öncelikli ve kritik</small></div>
        <div className="danger"><span>Süresi Geçmiş</span><b>{s.expiredDocuments??0}</b><small>Hemen aksiyon</small></div>
        <div><span>Açık CAPA</span><b>{s.openFindings??0}</b><small>{s.overdueFindings??0} gecikmiş</small></div><div><span>Ortak Kanıt</span><b>{s.sharedEvidenceRequirements??0}</b><small>Tek kanıtla ek karşılanan madde</small></div>
      </div>
      <div className="compliance-grid two">
        <section className="compliance-card"><div className="card-head"><div><h3>Denetim Hazırlığı</h3><p>Standart bazında mevcut kanıt oranı</p></div></div><div className="profile-score-list">{(dash.profiles||[]).map(row=><div className="profile-score" key={row.id}><div><b>{row.name}</b><small>{row.missing} eksik / {row.total} gereklilik</small></div><div className="score-track"><i style={{width:`${row.score||0}%`}}/></div><strong>%{row.score||0}</strong></div>)}</div></section>
        <section className="compliance-card"><div className="card-head"><div><h3>Bugün Ne Yapılmalı?</h3><p>Eksik, yaklaşan ve geciken işler</p></div><button className="link" onClick={runAi}>AI Tara</button></div><div className="action-list">{(dash.missingRequirements||[]).slice(0,5).map(row=><div key={row.id} className="action-row warning"><span>Eksik</span><div><b>{row.title}</b><small>{row.category} · {row.owner_department||"Sorumlu atanmadı"}</small></div></div>)}{(dash.expiring||[]).slice(0,5).map(row=><div key={row.id} className={`action-row ${cls(row.state)}`}><span>{STATUS_LABELS[row.state]||row.state}</span><div><b>{row.title}</b><small>{dateText(row.expires_at)} · {row.owner_department||"Sorumlu atanmadı"}</small></div></div>)}{!(dash.missingRequirements||[]).length&&!(dash.expiring||[]).length?<div className="empty">Kritik aksiyon görünmüyor.</div>:null}</div></section>
      </div>
      <section className="compliance-card"><div className="card-head"><div><h3>ERP'den Hazır Kanıtlar</h3><p>PDKS/İK ve operasyon kayıtları aday olur; yetkili doğrulamadan denetim kanıtına dönüşmez.</p></div><small>{systemCandidates.length} aday</small></div><div className="task-list">{systemCandidates.slice(0,8).map(row=><div key={`${row.controlKey}-${row.sourceRef}-${row.periodEnd||""}`}><div><b>{row.title}</b><small>{row.controlTitle} · {row.periodStart||"-"} / {row.periodEnd||"-"} · %{Math.round((row.confidence||0)*100)} güven</small></div><button onClick={()=>verifySystemEvidence(row)} disabled={busy}>Kanıt Olarak Doğrula</button></div>)}{!systemCandidates.length?<div className="empty">ERP içinde doğrulanacak yeni kanıt adayı yok.</div>:null}</div></section>
      <div className="compliance-grid two">
        <section className="compliance-card"><div className="card-head"><h3>Yaklaşan Evraklar</h3><small>{(dash.expiring||[]).length} kayıt</small></div><div className="mini-table">{(dash.expiring||[]).slice(0,8).map(row=><div key={row.id}><span className={`state ${cls(row.state)}`}>{STATUS_LABELS[row.state]||row.state}</span><b>{row.title}</b><span>{row.days_remaining==null?dateText(row.expires_at):row.days_remaining===0?"Bugün":row.days_remaining>0?`${row.days_remaining} gün`:`${Math.abs(row.days_remaining)} gün geçti`}</span></div>)}{!(dash.expiring||[]).length?<div className="empty">Yaklaşan evrak yok.</div>:null}</div></section>
        <section className="compliance-card"><div className="card-head"><h3>Açık Görevler</h3><small>{tasks.filter(x=>x.status==="OPEN").length} kayıt</small></div><div className="task-list">{tasks.filter(x=>x.status==="OPEN").slice(0,8).map(row=><div key={row.id}><div><b>{row.title}</b><small>{row.due_date?dateText(row.due_date):"Tarih yok"} · {row.priority}</small></div><button onClick={()=>markTaskDone(row.id)} disabled={busy}>Tamamla</button></div>)}{!tasks.filter(x=>x.status==="OPEN").length?<div className="empty">Açık görev yok.</div>:null}</div></section>
      </div>
    </>}
    {section==="AUDITS"&&<section className="compliance-card"><div className="card-head"><div><h3>Denetim Dosyaları</h3><p>Disney, SMETA, SLCP, Inditex/Zara veya özel müşteri denetimini tek iş dosyasında yönetin.</p></div><button className="primary" onClick={()=>setShowAuditForm(v=>!v)}>+ Denetim Aç</button></div>{showAuditForm&&<form className="capa-form" onSubmit={createAudit}><input placeholder="Denetim adı" value={auditForm.name} onChange={e=>setAuditForm(v=>({...v,name:e.target.value}))} required/><select value={auditForm.profileId} onChange={e=>setAuditForm(v=>({...v,profileId:e.target.value}))}><option value="">Standart seçin</option>{(dash.profiles||[]).map(row=><option key={row.id} value={row.id}>{row.name}</option>)}</select><select value={auditForm.auditType} onChange={e=>setAuditForm(v=>({...v,auditType:e.target.value}))}><option value="CUSTOMER">Müşteri / Marka</option><option value="SOCIAL">Sosyal Uygunluk</option><option value="ENVIRONMENT">Çevre</option><option value="LEGAL">Yasal / İSG</option><option value="INTERNAL">İç Denetim</option></select><input type="date" value={auditForm.plannedDate} onChange={e=>setAuditForm(v=>({...v,plannedDate:e.target.value}))}/><input placeholder="Denetçi / audit firması" value={auditForm.auditorName} onChange={e=>setAuditForm(v=>({...v,auditorName:e.target.value}))}/><textarea placeholder="Notlar / portal referansı" value={auditForm.notes} onChange={e=>setAuditForm(v=>({...v,notes:e.target.value}))}/><button className="primary" disabled={busy}>Denetim Dosyasını Oluştur</button></form>}<div className="capa-list">{(dash.audits||[]).map(row=><div className="capa-row" key={row.id}><span className="severity medium">{row.audit_type||"AUDIT"}</span><div><b>{row.name}</b><small>{row.profile_name||row.profile_id||"Standart seçilmemiş"} · {row.auditor_name||"Denetçi atanmadı"}</small><em>{row.notes||"Not yok"}</em></div><span>{row.planned_date?dateText(row.planned_date):"Tarih yok"}</span><i>{row.status||"PLANNED"}</i></div>)}{!(dash.audits||[]).length?<div className="empty">Henüz denetim dosyası yok.</div>:null}</div></section>}

    {section==="DOCUMENTS"&&<section className="compliance-card documents-card"><div className="card-head"><div><h3>Evrak Takip Merkezi</h3><p>Tüm belge, süre, kurum ve dosyalar tek listede.</p></div><button className="primary" onClick={()=>setShowDocForm(true)}>+ Yeni Evrak</button></div><div className="document-toolbar"><input type="search" placeholder="Evrak, kurum, kategori veya belge no ara" value={q} onChange={e=>setQ(e.target.value)}/><select value={stateFilter} onChange={e=>setStateFilter(e.target.value)}><option value="ALL">Tüm Durumlar</option><option value="ACTIVE">Geçerli</option><option value="EXPIRING">Yaklaşıyor</option><option value="CRITICAL">Kritik</option><option value="EXPIRED">Süresi Geçti</option></select><span>{filteredDocs.length} kayıt</span></div><div className="document-table"><div className="document-row head"><span>Durum</span><span>Evrak</span><span>Kategori</span><span>Belge No</span><span>Son Tarih</span><span>Sorumlu</span><span>Dosya</span></div>{filteredDocs.map(row=><div className="document-row" key={row.id}><span><i className={`state ${cls(row.state)}`}>{STATUS_LABELS[row.state]||row.state}</i></span><span><b>{row.title}</b><small>{row.issuer||"Kurum yok"}</small></span><span>{row.category||"-"}</span><span>{row.document_no||"-"}</span><span>{dateText(row.expires_at)}</span><span>{row.owner_department||"-"}</span><span>{row.file_name?<b className="file-ok">✓ {row.file_name}</b>:<em>Dosya yok</em>}</span></div>)}{!filteredDocs.length?<div className="empty">Filtreye uygun evrak bulunamadı.</div>:null}</div></section>}

    {section==="STANDARDS"&&<div className="compliance-grid standards-layout"><section className="compliance-card standard-list"><div className="card-head"><div><h3>Denetim Standartları</h3><p>Hazır şablonlar ve firma özel profilleri</p></div></div>{profiles.map(row=><button key={row.id} className={String(row.id)===String(profile?.id)?"active":""} onClick={()=>setSelectedProfile(row.id)}><b>{row.name}</b><small>{row.code} · {row.version||"-"}</small><span>{row.requirements?.length||0} madde · {row.readinessEnabled===false?"Katalog":"Aktif"}</span></button>)}<form className="mini-form" onSubmit={createProfile}><h4>+ Yeni Standart</h4><input placeholder="Standart adı" value={profileForm.name} onChange={e=>setProfileForm(v=>({...v,name:e.target.value}))} required/><input placeholder="Kod (örn. LCW_2027)" value={profileForm.code} onChange={e=>setProfileForm(v=>({...v,code:e.target.value}))}/><input placeholder="Sürüm" value={profileForm.version} onChange={e=>setProfileForm(v=>({...v,version:e.target.value}))}/><textarea placeholder="Açıklama" value={profileForm.description} onChange={e=>setProfileForm(v=>({...v,description:e.target.value}))}/><button className="primary" disabled={busy}>Standardı Oluştur</button></form></section>
      <section className="compliance-card requirement-list"><div className="card-head"><div><h3>{profile?.name||"Standart seçin"}</h3><p>{profile?.description||"Sol listeden bir standart seçin."}</p></div><div><span>{profile?.requirements?.length||0} madde</span>{profile&&<button className="link" type="button" onClick={toggleProfileReadiness} disabled={busy}>{profile.readinessEnabled===false?"Hazırlığa dahil et":"Katalog moduna al"}</button>}</div></div><div className="requirement-scroll">{(profile?.requirements||[]).map(row=><div className="requirement-row" key={row.id}><span>{row.code}</span><div><b>{row.title}</b><small>{row.category} · {row.owner_department||"Sorumlu yok"} · {row.applicability_state==="EXEMPT"?"Muaf":row.applicability_state==="NOT_APPLICABLE"?"Uygulanmaz":row.applicability_state==="REVIEW"?"İncelenecek":"Uygulanır"}</small></div><button className="link" type="button" onClick={()=>setApplicabilityForm({requirementId:row.id,title:row.title,state:row.applicability_state||"APPLICABLE",reason:row.applicability_reason||""})}>Uygulanabilirlik</button></div>)}</div>{applicabilityForm.requirementId&&<form className="mini-form" onSubmit={saveApplicability}><h4>Uygulanabilirlik · {applicabilityForm.title}</h4><select value={applicabilityForm.state} onChange={e=>setApplicabilityForm(v=>({...v,state:e.target.value}))}><option value="APPLICABLE">Uygulanır</option><option value="REVIEW">İncelenecek</option><option value="EXEMPT">Muaf</option><option value="NOT_APPLICABLE">Uygulanmaz</option></select><textarea placeholder="Muaf / uygulanmaz ise gerekçe zorunlu" value={applicabilityForm.reason} onChange={e=>setApplicabilityForm(v=>({...v,reason:e.target.value}))}/><div><button type="button" onClick={()=>setApplicabilityForm({requirementId:"",title:"",state:"APPLICABLE",reason:""})}>Vazgeç</button><button className="primary" disabled={busy}>Kararı Kaydet</button></div></form>}{profile&&<form className="requirement-form" onSubmit={createRequirement}><h4>Yeni Gereklilik Ekle</h4><div><input placeholder="Madde adı" value={requirementForm.title} onChange={e=>setRequirementForm(v=>({...v,title:e.target.value}))} required/><input placeholder="Kod" value={requirementForm.code} onChange={e=>setRequirementForm(v=>({...v,code:e.target.value}))}/><input placeholder="Kategori" value={requirementForm.category} onChange={e=>setRequirementForm(v=>({...v,category:e.target.value}))}/><input placeholder="Sorumlu bölüm" value={requirementForm.ownerDepartment} onChange={e=>setRequirementForm(v=>({...v,ownerDepartment:e.target.value}))}/><input type="number" min="1" placeholder="Uyarı günü" value={requirementForm.warningDays} onChange={e=>setRequirementForm(v=>({...v,warningDays:Number(e.target.value)}))}/><label><input type="checkbox" checked={requirementForm.mandatory} onChange={e=>setRequirementForm(v=>({...v,mandatory:e.target.checked}))}/> Zorunlu</label></div><button className="primary" disabled={busy}>Maddeyi Ekle</button></form>}</section>
    </div>}
    {section==="CAPA"&&<section className="compliance-card"><div className="card-head"><div><h3>Düzeltici Faaliyet / CAPA</h3><p>Uygunsuzluk, sorumlu, termin ve kapanış kanıtı takibi.</p></div><button className="primary" onClick={()=>setShowFindingForm(v=>!v)}>+ CAPA Aç</button></div>{showFindingForm&&<form className="capa-form" onSubmit={createFinding}><input placeholder="Bulgu / uygunsuzluk" value={findingForm.title} onChange={e=>setFindingForm(v=>({...v,title:e.target.value}))} required/><select value={findingForm.severity} onChange={e=>setFindingForm(v=>({...v,severity:e.target.value}))}><option value="CRITICAL">Kritik</option><option value="HIGH">Yüksek</option><option value="MEDIUM">Orta</option><option value="LOW">Düşük</option></select><input type="date" value={findingForm.dueDate} onChange={e=>setFindingForm(v=>({...v,dueDate:e.target.value}))}/><textarea placeholder="Açıklama" value={findingForm.description} onChange={e=>setFindingForm(v=>({...v,description:e.target.value}))}/><textarea placeholder="Düzeltici faaliyet" value={findingForm.correctiveAction} onChange={e=>setFindingForm(v=>({...v,correctiveAction:e.target.value}))}/><button className="primary" disabled={busy}>Kaydet</button></form>}<div className="capa-list">{(dash.findings||[]).map(row=><div className="capa-row" key={row.id}><span className={`severity ${cls(row.severity)}`}>{SEVERITY_LABELS[row.severity]||row.severity}</span><div><b>{row.title}</b><small>{row.description||"Açıklama yok"}</small><em>{row.corrective_action||"Düzeltici faaliyet girilmemiş"}</em></div><span>{dateText(row.due_date)}</span><button onClick={()=>closeFinding(row.id)} disabled={busy}>Kapat</button></div>)}{!(dash.findings||[]).length?<div className="empty">Açık CAPA yok.</div>:null}</div></section>}

    {section==="CALENDAR"&&<section className="compliance-card"><div className="card-head"><div><h3>Denetim Takvimi</h3><p>Evrak son tarihleri, denetimler, CAPA terminleri ve görevler.</p></div><span>{calendar.length} kayıt</span></div><div className="calendar-list">{calendar.map(row=><div key={`${row.kind}-${row.id}`}><time>{dateText(row.due_date)}</time><span className={`kind ${cls(row.kind)}`}>{row.kind}</span><div><b>{row.title}</b><small>{row.status||""}</small></div></div>)}{!calendar.length?<div className="empty">Takvim kaydı yok.</div>:null}</div></section>}

    {section==="SETTINGS"&&<section className="compliance-card"><div className="card-head"><div><h3>Sistem Mantığı</h3><p>Yeni standart veya evrak türü için kod değişikliği gerektirmeyen yapı.</p></div></div><div className="settings-grid"><div><b>Standart Şablonları</b><p>Disney, SMETA, SLCP, Inditex/Zara, ZDHC, Higg FEM, OEKO-TEX, WRAP, amfori BSCI ve özel müşteri profilleri.</p></div><div><b>Özelleştirilebilir Maddeler</b><p>Firma yöneticisi yeni gereklilik, kategori, uyarı süresi ve sorumlu bölüm ekleyebilir.</p></div><div><b>Versiyonlu Evrak</b><p>Yeni dosya eski kanıtı silmez; revizyon geçmişi korunur.</p></div><div><b>Akıllı Kontrol</b><p>Eksik, süresi yaklaşan, süresi geçmiş ve geciken CAPA kayıtlarını otomatik önceliklendirir.</p></div></div></section>}
  </div>;
}
