const http = require('http');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { DatabaseSync } = require('node:sqlite');

const ROOT = process.env.HAKAN_EMP_APP_ROOT || __dirname;
const PORT = Number(process.env.HAKAN_EMP_PORT || 8789);
const DATA_ROOT = process.env.HAKAN_EMP_DATA_DIR || path.join(ROOT,'data');
if(!fs.existsSync(DATA_ROOT))fs.mkdirSync(DATA_ROOT,{recursive:true});
const DB_PATH = path.join(DATA_ROOT, 'IMALAT.db');
const db = new DatabaseSync(DB_PATH);
const txt=v=>v==null?'':String(v).trim();
const norm=v=>txt(v).replace(/\s+/g,' ').toLocaleUpperCase('tr-TR');
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const today=()=>new Date().toISOString().slice(0,10);
const nowIso=()=>new Date().toISOString();
const uuid=()=>crypto.randomUUID();

function cols(t){return db.prepare(`PRAGMA table_info(${t})`).all().map(x=>x.name)}
function addcol(t,n,ddl){if(!cols(t).includes(n))db.exec(`ALTER TABLE ${t} ADD COLUMN ${n} ${ddl}`)}
function dir(p){if(p&&!fs.existsSync(p))fs.mkdirSync(p,{recursive:true})}
function oneDrive(){return ['D:/Onedrive-Hkn/OneDrive','D:/onedrive-Hkn/OneDrive','D:/onedrive hkngursu/OneDrive',process.env.OneDrive,process.env.OneDriveCommercial].filter(Boolean).find(p=>fs.existsSync(p))||''}

const OD=process.env.HAKAN_EMP_DISABLE_SYNC==='1'?'':oneDrive(),SYNC=OD?path.join(OD,'HAKAN EMP','SYNC'):'',PCOUT=SYNC?path.join(SYNC,'PC-OUTBOX'):'',ANDOUT=SYNC?path.join(SYNC,'ANDROID-OUTBOX'):'',ACK=SYNC?path.join(SYNC,'ACK'):'',ARCH=SYNC?path.join(SYNC,'ARCHIVE'):'';
const IMGROOT=OD?path.join(OD,'HAKAN EMP','BELGELER','CEKLER'):path.join(DATA_ROOT,'check-images');
[SYNC,PCOUT,ANDOUT,ACK,ARCH,IMGROOT].filter(Boolean).forEach(dir);

db.exec(`
PRAGMA journal_mode=WAL;
CREATE TABLE IF NOT EXISTS settings(k TEXT PRIMARY KEY,v TEXT);
CREATE TABLE IF NOT EXISTS machines(machine_no TEXT PRIMARY KEY,machine_name TEXT,day_operator TEXT,day_assistant TEXT,night_operator TEXT,night_assistant TEXT);
CREATE TABLE IF NOT EXISTS operators(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,norm TEXT UNIQUE NOT NULL,active INTEGER DEFAULT 1,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS models(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,norm TEXT UNIQUE NOT NULL);
CREATE TABLE IF NOT EXISTS batches(id INTEGER PRIMARY KEY AUTOINCREMENT,model_id INTEGER NOT NULL,batch_no TEXT NOT NULL,is_repeat INTEGER DEFAULT 0,order_no TEXT,ground TEXT,region TEXT,dispatch_qty REAL DEFAULT 0,invoice_qty REAL DEFAULT 0,status TEXT DEFAULT 'OPEN',first_date TEXT,last_date TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS entries(id INTEGER PRIMARY KEY AUTOINCREMENT,batch_id INTEGER NOT NULL,date TEXT,machine_no TEXT,shift TEXT,machine_name TEXT,operator TEXT,assistant TEXT,qty REAL DEFAULT 0,fabric_defect REAL DEFAULT 0,print_defect REAL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS financial(id INTEGER PRIMARY KEY AUTOINCREMENT,batch_id INTEGER NOT NULL,type TEXT,doc_no TEXT,date TEXT,qty REAL DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS companies(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,norm TEXT UNIQUE NOT NULL,opening_balance REAL DEFAULT 0,active INTEGER DEFAULT 1,note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS company_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,company_id INTEGER NOT NULL,type TEXT NOT NULL,date TEXT,amount REAL DEFAULT 0,doc_no TEXT,model_id INTEGER,batch_id INTEGER,note TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payment_reminders(id INTEGER PRIMARY KEY AUTOINCREMENT,party TEXT NOT NULL,due_date TEXT,amount REAL DEFAULT 0,note TEXT,status TEXT DEFAULT 'PENDING',paid_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notes(id INTEGER PRIMARY KEY AUTOINCREMENT,uid TEXT UNIQUE NOT NULL,title TEXT,body TEXT NOT NULL,author TEXT DEFAULT 'Muhasebe',target TEXT DEFAULT 'Patron',category TEXT DEFAULT 'Genel',priority TEXT DEFAULT 'NORMAL',status TEXT DEFAULT 'AKTİF',active INTEGER DEFAULT 1,pinned INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS checks(id INTEGER PRIMARY KEY AUTOINCREMENT,direction TEXT NOT NULL,due_date TEXT,bank TEXT,serial_no TEXT,counterparty TEXT,drawer TEXT,amount REAL DEFAULT 0,status TEXT DEFAULT 'ÖDENECEK',account_no TEXT,iban TEXT,note TEXT,source TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sync_events(event_id TEXT PRIMARY KEY,source_device TEXT,event_type TEXT,payload TEXT,direction TEXT,status TEXT DEFAULT 'NEW',created_at TEXT DEFAULT CURRENT_TIMESTAMP,applied_at TEXT);
`);
addcol('models','company_id','INTEGER'); addcol('machines','active','INTEGER DEFAULT 1'); addcol('batches','expected_qty','REAL DEFAULT 0'); addcol('batches','production_done','INTEGER DEFAULT 0'); addcol('batches','completed_at','TEXT');
addcol('financial','amount','REAL DEFAULT 0'); addcol('financial','company_id','INTEGER');
addcol('company_movements','batch_id','INTEGER');
addcol('payment_reminders','party','TEXT');
try{db.exec("UPDATE payment_reminders SET party=COALESCE(NULLIF(party,''),payee,'') WHERE party IS NULL OR party=''")}catch{}
addcol('checks','account_no','TEXT'); addcol('checks','iban','TEXT'); addcol('checks','receipt_received','INTEGER DEFAULT 0'); addcol('checks','receipt_by','TEXT'); addcol('checks','receipt_note','TEXT'); addcol('checks','against_text','TEXT'); addcol('checks','image_path','TEXT');
addcol('sync_events','source_device','TEXT'); addcol('sync_events','event_type','TEXT'); addcol('sync_events','payload','TEXT'); addcol('sync_events','direction','TEXT'); addcol('sync_events','status',"TEXT DEFAULT 'NEW'"); addcol('sync_events','created_at','TEXT'); addcol('sync_events','applied_at','TEXT');
try{db.exec(`CREATE INDEX IF NOT EXISTS idx_e_b ON entries(batch_id);CREATE INDEX IF NOT EXISTS idx_b_m ON batches(model_id);CREATE INDEX IF NOT EXISTS idx_b_s ON batches(status);CREATE INDEX IF NOT EXISTS idx_f_b ON financial(batch_id);CREATE INDEX IF NOT EXISTS idx_c_m ON company_movements(company_id);CREATE INDEX IF NOT EXISTS idx_r_d ON payment_reminders(due_date,status);CREATE INDEX IF NOT EXISTS idx_n_s ON notes(status,active,updated_at);CREATE INDEX IF NOT EXISTS idx_ch_d ON checks(due_date,status);`)}catch{}

function company(name='TAHA GİYİM'){let r=db.prepare('SELECT * FROM companies WHERE norm=?').get(norm(name));if(!r){db.prepare('INSERT INTO companies(name,norm) VALUES(?,?)').run(name,norm(name));r=db.prepare('SELECT * FROM companies WHERE norm=?').get(norm(name))}return r}
const TAHA=company();
db.prepare('UPDATE models SET company_id=? WHERE company_id IS NULL OR company_id=0').run(TAHA.id);
function model(name,cid=TAHA.id){let r=db.prepare('SELECT * FROM models WHERE norm=?').get(norm(name));if(!r){db.prepare('INSERT INTO models(name,norm,company_id) VALUES(?,?,?)').run(txt(name),norm(name),cid);r=db.prepare('SELECT * FROM models WHERE norm=?').get(norm(name))}return r}
for(const r of db.prepare(`SELECT b.id,b.expected_qty,COALESCE((SELECT SUM(qty) FROM entries e WHERE e.batch_id=b.id),0) produced FROM batches b WHERE b.status='OPEN'`).all())if(num(r.expected_qty)<=0&&num(r.produced)>0)db.prepare('UPDATE batches SET expected_qty=? WHERE id=?').run(num(r.produced),r.id);

function importChecks(){if(num(db.prepare('SELECT COUNT(*) c FROM checks').get().c)>0||!SYNC)return;const f=path.join(SYNC,'HAKAN_EMP_SNAPSHOT.json');if(!fs.existsSync(f))return;try{const x=JSON.parse(fs.readFileSync(f,'utf8').replace(/^\uFEFF/,'')),q=db.prepare(`INSERT INTO checks(direction,due_date,bank,serial_no,counterparty,drawer,amount,status,account_no,iban,note,source,receipt_received,receipt_by,receipt_note,against_text,image_path) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`);for(const c of x.checks||[])q.run(txt(c.direction)||'OUT',txt(c.due_date),txt(c.bank),txt(c.serial_no),txt(c.counterparty),txt(c.drawer),num(c.amount),txt(c.status)||'ÖDENECEK',txt(c.account_no),txt(c.iban),txt(c.note),txt(c.source)||'Snapshot',num(c.receipt_received),txt(c.receipt_by),txt(c.receipt_note),txt(c.against_text),txt(c.image_path))}catch(e){console.error('CHECK_IMPORT',e.message)}}
importChecks();
try{
 const iq=db.prepare('INSERT OR IGNORE INTO operators(name,norm) VALUES(?,?)');
 for(const m of db.prepare("SELECT day_operator,night_operator FROM machines").all()){
   for(const name of [m.day_operator,m.night_operator].map(txt).filter(Boolean))iq.run(name,norm(name));
 }
}catch(e){console.error('OPERATOR_SEED',e.message)}

function backup(){try{db.exec('PRAGMA wal_checkpoint(TRUNCATE)');const p=path.join(DATA_ROOT,'backup');dir(p);const f=path.join(p,'IMALAT_'+nowIso().replace(/[:.]/g,'-')+'.db');fs.copyFileSync(DB_PATH,f);const a=fs.readdirSync(p).filter(x=>x.endsWith('.db')).sort().reverse();for(const x of a.slice(30))fs.unlinkSync(path.join(p,x))}catch(e){console.error('BACKUP',e.message)}} backup();

function totals(id){return db.prepare(`SELECT b.*,m.name model_name,m.company_id,c.name company_name,COALESCE((SELECT SUM(qty) FROM entries e WHERE e.batch_id=b.id),0) produced_qty,COALESCE((SELECT SUM(fabric_defect) FROM entries e WHERE e.batch_id=b.id),0) fabric_defect,COALESCE((SELECT SUM(print_defect) FROM entries e WHERE e.batch_id=b.id),0) print_defect FROM batches b JOIN models m ON m.id=b.model_id LEFT JOIN companies c ON c.id=m.company_id WHERE b.id=?`).get(id)}
function calc(r){if(!r)return null;const incoming=num(r.expected_qty),prod=num(r.produced_qty),disp=num(r.dispatch_qty),inv=num(r.invoice_qty),prodRem=Math.max(0,incoming-prod),dispRem=Math.max(0,incoming-disp),invRem=Math.max(0,disp-inv);let action='GELEN ADEDİ GİR',code='NEED_INCOMING',color='red';if(incoming>0&&prod<incoming){action=fmt(prodRem)+' ADET ÜRETİM KALDI';code='PRODUCTION';color='blue'}else if(incoming>0&&prod>=incoming&&disp<=0){action='İRSALİYE İSTE';code='NEED_DISPATCH';color='red'}else if(incoming>0&&disp<incoming){action=fmt(dispRem)+' ADET İRSALİYE EKSİK';code='DISPATCH_SHORT';color='orange'}else if(incoming>0&&inv<disp){action=fmt(invRem)+' ADET FATURA KES';code='INVOICE';color='purple'}else if(incoming>0){action='TAMAM';code='DONE';color='green'}return {...r,incoming_qty:incoming,production_remaining:prodRem,dispatch_remaining:dispRem,invoice_remaining:invRem,action,action_code:code,color}}
function fmt(x){return Math.round(num(x)).toLocaleString('tr-TR')}
function isoLocal(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function addDays(date,days){const d=new Date((txt(date)||today())+'T12:00:00');d.setDate(d.getDate()+num(days));return isoLocal(d)}
function weekInfo(date=today()){const raw=txt(date)||today(),d=new Date(raw+'T12:00:00'),shift=(d.getDay()+6)%7;d.setDate(d.getDate()-shift);const start=isoLocal(d),end=addDays(start,6);return{start,end}}
function weeklyBatch(batchId,date=today()){const w=weekInfo(date),r=db.prepare(`SELECT COUNT(*) entry_count,COALESCE(SUM(qty),0) produced_qty,COALESCE(SUM(fabric_defect),0) fabric_defect,COALESCE(SUM(print_defect),0) print_defect,COUNT(DISTINCT date) work_days FROM entries WHERE batch_id=? AND date BETWEEN ? AND ?`).get(num(batchId),w.start,w.end)||{};return{week_start:w.start,week_end:w.end,week_entries:num(r.entry_count),week_produced:num(r.produced_qty),week_fabric_defect:num(r.fabric_defect),week_print_defect:num(r.print_defect),week_work_days:num(r.work_days)}}
function withWeek(r,date=today()){const base=calc(r);return base?{...base,...weeklyBatch(base.batch_id||base.id,date)}:base}
function evaluate(id){const r=calc(totals(id));if(!r)return;if(r.action_code==='DONE')db.prepare("UPDATE batches SET status='TAMAM',production_done=1,completed_at=COALESCE(completed_at,?) WHERE id=?").run(nowIso(),id);else db.prepare("UPDATE batches SET status='OPEN',completed_at=NULL,production_done=CASE WHEN ?>=? AND ?>0 THEN 1 ELSE production_done END WHERE id=?").run(r.produced_qty,r.incoming_qty,r.incoming_qty,id)}
function rows(status='OPEN',week=today()){return db.prepare(`SELECT b.id batch_id,b.model_id,b.expected_qty,b.order_no,b.ground,b.region,b.first_date,b.last_date,b.status,b.production_done,b.completed_at,m.name model_name,m.company_id,c.name company_name,COALESCE((SELECT SUM(qty) FROM entries e WHERE e.batch_id=b.id),0) produced_qty,COALESCE((SELECT SUM(fabric_defect) FROM entries e WHERE e.batch_id=b.id),0) fabric_defect,COALESCE((SELECT SUM(print_defect) FROM entries e WHERE e.batch_id=b.id),0) print_defect,b.dispatch_qty,b.invoice_qty FROM batches b JOIN models m ON m.id=b.model_id LEFT JOIN companies c ON c.id=m.company_id WHERE b.status=? ORDER BY COALESCE(b.completed_at,b.last_date) DESC,b.id DESC LIMIT 500`).all(status).map(r=>withWeek(r,week))}
function companyRows(activeOnly=true){const where=activeOnly?'WHERE c.active=1':'';return db.prepare(`SELECT c.*,COALESCE((SELECT SUM(CASE WHEN type='INVOICE' THEN amount ELSE 0 END) FROM company_movements m WHERE m.company_id=c.id),0) invoice_total,COALESCE((SELECT SUM(CASE WHEN type='PAYMENT' THEN amount ELSE 0 END) FROM company_movements m WHERE m.company_id=c.id),0) payment_total,(SELECT COUNT(*) FROM company_movements m WHERE m.company_id=c.id) movement_count FROM companies c ${where} ORDER BY CASE WHEN c.norm=? THEN 0 ELSE 1 END,c.active DESC,c.name`).all(norm('TAHA GİYİM')).map(r=>({...r,balance:num(r.opening_balance)+num(r.invoice_total)-num(r.payment_total)}))}
function companies(){const rows=companyRows(true),movements=db.prepare(`SELECT m.*,c.name company_name,mo.name model_name FROM company_movements m JOIN companies c ON c.id=m.company_id LEFT JOIN models mo ON mo.id=m.model_id ORDER BY m.date DESC,m.id DESC LIMIT 500`).all();return{rows,movements}}
function allCompanies(){return{rows:companyRows(false)}}
function dashboard(week=today()){const w=weekInfo(week),a=rows('OPEN',w.start),weekActive=a.filter(r=>num(r.week_entries)>0);return{week:w,rows:a,summary:{open:a.length,incoming:a.reduce((s,r)=>s+num(r.incoming_qty),0),produced:a.reduce((s,r)=>s+num(r.produced_qty),0),weekModels:weekActive.length,weekEntries:a.reduce((s,r)=>s+num(r.week_entries),0),weekProduced:a.reduce((s,r)=>s+num(r.week_produced),0),weekDefects:a.reduce((s,r)=>s+num(r.week_fabric_defect)+num(r.week_print_defect),0),needDispatch:a.filter(r=>['NEED_DISPATCH','DISPATCH_SHORT'].includes(r.action_code)).length,invoiceReady:a.reduce((s,r)=>s+num(r.invoice_remaining),0)},models:db.prepare('SELECT id,name,company_id FROM models ORDER BY name').all(),machines:db.prepare("SELECT * FROM machines WHERE machine_no<>'0' AND COALESCE(active,1)=1 ORDER BY CAST(machine_no AS INTEGER),machine_no").all(),operators:db.prepare("SELECT * FROM operators WHERE active=1 ORDER BY name").all(),companies:companies().rows}}
function detail(mid,week=today()){const m=db.prepare(`SELECT m.*,c.name company_name FROM models m LEFT JOIN companies c ON c.id=m.company_id WHERE m.id=?`).get(mid);if(!m)return null;const w=weekInfo(week),batches=db.prepare('SELECT * FROM batches WHERE model_id=? ORDER BY id DESC').all(mid),events=[];for(const b of batches){for(const e of db.prepare('SELECT * FROM entries WHERE batch_id=? ORDER BY date DESC,id DESC').all(b.id))events.push({id:e.id,kind:'production',batch_id:b.id,date:e.date,qty:e.qty,machine_no:e.machine_no,shift:e.shift,operator:e.operator,fabric_defect:e.fabric_defect,print_defect:e.print_defect});for(const f of db.prepare('SELECT * FROM financial WHERE batch_id=? ORDER BY date DESC,id DESC').all(b.id))events.push({id:f.id,kind:f.type,batch_id:b.id,date:f.date,qty:f.qty,doc_no:f.doc_no,amount:f.amount})}events.sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))||num(b.id)-num(a.id));const ob=db.prepare("SELECT id FROM batches WHERE model_id=? AND status='OPEN' ORDER BY id DESC LIMIT 1").get(mid),open=ob?withWeek(totals(ob.id),w.start):null,weekEvents=events.filter(e=>String(e.date||'')>=w.start&&String(e.date||'')<=w.end);return{model:m,open,batches,events,week:w,weekEvents}}

function event(type,payload){const id=uuid(),e={event_id:id,source_device:'PC-DESEN',event_type:type,payload,created_at:nowIso()};db.prepare('INSERT OR IGNORE INTO sync_events(event_id,source_device,event_type,payload,direction,status,created_at) VALUES(?,?,?,?,?,?,?)').run(id,e.source_device,type,JSON.stringify(payload),'OUT','NEW',e.created_at);if(PCOUT)try{fs.writeFileSync(path.join(PCOUT,id+'.json'),JSON.stringify(e,null,2),'utf8')}catch{}}
function job(x,no=false){const cid=num(x.companyId)||TAHA.id,m=model(x.modelName,cid),old=db.prepare("SELECT id FROM batches WHERE model_id=? AND status='OPEN' ORDER BY id DESC LIMIT 1").get(m.id);if(old)throw Error('Bu modelin açık işi zaten var');const c=num(db.prepare('SELECT COUNT(*) c FROM batches WHERE model_id=?').get(m.id).c),bid=Number(db.prepare('INSERT INTO batches(model_id,batch_no,is_repeat,order_no,ground,region,expected_qty,first_date,last_date,status) VALUES(?,?,?,?,?,?,?,?,?,?)').run(m.id,c?'REPEAT '+String(c).padStart(2,'0'):'İLK ÜRETİM',c?1:0,txt(x.orderNo),txt(x.ground),txt(x.region),num(x.expectedQty),txt(x.date)||today(),txt(x.date)||today(),'OPEN').lastInsertRowid);if(!no)event('job.create',{companyId:cid,modelName:m.name,expectedQty:num(x.expectedQty),orderNo:txt(x.orderNo),ground:txt(x.ground),date:txt(x.date)||today()});return{ok:true,batchId:bid,modelId:m.id}}
function adjustJob(x,no=false){const bid=num(x.batchId);if(!bid)throw Error('İş bulunamadı');const b=db.prepare("SELECT * FROM batches WHERE id=? AND status='OPEN'").get(bid);if(!b)throw Error('Yalnız açık havuzdaki iş düzenlenebilir');const expected=num(x.expectedQty);if(expected<=0)throw Error('Gelen toplam adet zorunlu');const produced=num(db.prepare('SELECT COALESCE(SUM(qty),0) q FROM entries WHERE batch_id=?').get(bid)?.q);const dispatch=num(b.dispatch_qty),invoice=num(b.invoice_qty);if(expected<Math.max(produced,dispatch,invoice))throw Error('Gelen adet, işlenmiş üretim/irsaliye/fatura adedinden küçük olamaz');db.prepare('UPDATE batches SET expected_qty=?,ground=?,order_no=? WHERE id=?').run(expected,txt(x.ground)||txt(b.ground),txt(x.orderNo)||txt(b.order_no),bid);evaluate(bid);if(!no)event('job.adjust',{batchId:bid,expectedQty:expected,ground:txt(x.ground)||txt(b.ground),orderNo:txt(x.orderNo)||txt(b.order_no)});return{ok:true,batchId:bid,summary:withWeek(totals(bid),txt(x.week)||today())}}
function production(x,no=false){let bid=num(x.batchId);if(!bid&&x.modelId)bid=db.prepare("SELECT id FROM batches WHERE model_id=? AND status='OPEN' ORDER BY id DESC LIMIT 1").get(num(x.modelId))?.id||0;if(!bid)throw Error('Önce model için iş açın');if(num(x.qty)<=0)throw Error('Üretim adedi zorunlu');const mach=db.prepare('SELECT * FROM machines WHERE machine_no=?').get(txt(x.machineNo))||{},night=norm(x.shift)==='GECE',op=txt(x.operator)||txt(night?mach.night_operator:mach.day_operator);if(!txt(x.machineNo))throw Error('Makine zorunlu');if(!op)throw Error('Makinacı zorunlu');db.prepare('INSERT INTO entries(batch_id,date,machine_no,shift,machine_name,operator,assistant,qty,fabric_defect,print_defect) VALUES(?,?,?,?,?,?,?,?,?,?)').run(bid,txt(x.date)||today(),txt(x.machineNo),txt(x.shift)||'Gündüz',txt(mach.machine_name),op,'',num(x.qty),num(x.fabricDefect),num(x.printDefect));db.prepare('UPDATE batches SET last_date=? WHERE id=?').run(txt(x.date)||today(),bid);evaluate(bid);if(!no)event('production.create',{batchId:bid,date:txt(x.date)||today(),machineNo:txt(x.machineNo),shift:txt(x.shift)||'Gündüz',operator:op,qty:num(x.qty),fabricDefect:num(x.fabricDefect),printDefect:num(x.printDefect)});return{ok:true,batchId:bid,summary:calc(totals(bid))}}
function editDistance(a,b){a=norm(a);b=norm(b);const m=a.length,n=b.length,dp=Array.from({length:n+1},(_,j)=>j);for(let i=1;i<=m;i++){let prev=dp[0];dp[0]=i;for(let j=1;j<=n;j++){const old=dp[j],cost=a[i-1]===b[j-1]?0:1;dp[j]=Math.min(dp[j]+1,dp[j-1]+1,prev+cost);prev=old}}return dp[n]}
function similarModels(name,excludeId=0){
 const q=norm(name);if(q.length<2)return[];
 const pool=db.prepare('SELECT id,name,company_id FROM models WHERE id<>?').all(num(excludeId));
 return pool.map(m=>{const mn=norm(m.name),dist=editDistance(q,mn),score=1-dist/Math.max(q.length,mn.length,1),boost=(mn.startsWith(q)||q.startsWith(mn))?0.18:(mn.includes(q)||q.includes(mn))?0.12:0;return{...m,score:Math.min(1,score+boost)}}).filter(x=>x.score>=.56).sort((a,b)=>b.score-a.score||a.name.localeCompare(b.name,'tr')).slice(0,6);
}
function productionLookup(name){
 const q=norm(name);if(!q)return{state:'EMPTY',similar:[]};
 const m=db.prepare('SELECT * FROM models WHERE norm=?').get(q);
 if(!m)return{state:'NEW',modelName:txt(name),similar:similarModels(name)};
 const open=db.prepare("SELECT id FROM batches WHERE model_id=? AND status='OPEN' ORDER BY id DESC LIMIT 1").get(m.id);
 if(open){const r=calc(totals(open.id)),recent=db.prepare('SELECT date,machine_no,shift,operator,qty,fabric_defect,print_defect FROM entries WHERE batch_id=? ORDER BY date DESC,id DESC LIMIT 5').all(open.id);return{state:'OPEN',model:m,summary:r,recent,similar:similarModels(name,m.id)}}
 const last=db.prepare("SELECT id FROM batches WHERE model_id=? ORDER BY id DESC LIMIT 1").get(m.id);
 const summary=last?calc(totals(last.id)):null,recent=last?db.prepare('SELECT date,machine_no,shift,operator,qty,fabric_defect,print_defect FROM entries WHERE batch_id=? ORDER BY date DESC,id DESC LIMIT 5').all(last.id):[];
 return{state:'REPEAT',model:m,summary,recent,similar:similarModels(name,m.id)};
}
function serialProduction(x){
 const name=txt(x.modelName),ground=txt(x.ground);if(!name)throw Error('Model adı zorunlu');if(!ground)throw Error('Zemin rengi zorunlu');
 let lookup=productionLookup(name),modelId=lookup.model?.id||0;
 if(lookup.state==='REPEAT'&&String(x.repeatConfirmed)!=='1'&&x.repeatConfirmed!==true)throw Error('REPETE_ONAY_GEREKLI');
 if(lookup.state==='NEW'&&(lookup.similar||[]).length&&String(x.newConfirmed)!=='1'&&x.newConfirmed!==true)throw Error('BENZER_MODEL_ONAY_GEREKLI');
 if(lookup.state!=='OPEN'){
   if(num(x.expectedQty)<=0)throw Error('Yeni veya repete iş için gelen toplam adet zorunlu');
   const j=job({companyId:num(x.companyId)||TAHA.id,modelName:name,expectedQty:num(x.expectedQty),ground,date:txt(x.date)||today()},false);
   modelId=j.modelId;
 }else{
   const current=lookup.summary||{};
   if(txt(current.ground)&&norm(current.ground)!==norm(ground))throw Error('Zemin rengi açık iş ile uyuşmuyor: '+txt(current.ground));
   if(!txt(current.ground))db.prepare('UPDATE batches SET ground=? WHERE id=?').run(ground,num(current.id||current.batch_id));
 }
 const p=production({modelId,date:txt(x.date)||today(),machineNo:txt(x.machineNo),shift:txt(x.shift)||'Gündüz',operator:txt(x.operator),qty:num(x.qty),fabricDefect:num(x.fabricDefect),printDefect:num(x.printDefect)},false);
 const out=productionLookup(name);
 return{ok:true,createdNew:lookup.state!=='OPEN',isRepeat:lookup.state==='REPEAT',stateBefore:lookup.state,modelId,batchId:p.batchId,summary:out.summary,recent:out.recent||[]};
}
function saveOperator(x){
 const name=txt(x.name);if(!name)throw Error('Makinacı adı zorunlu');const nr=norm(name);let id=num(x.id);
 if(id)db.prepare('UPDATE operators SET name=?,norm=?,active=? WHERE id=?').run(name,nr,x.active===0?0:1,id);
 else id=Number(db.prepare('INSERT OR IGNORE INTO operators(name,norm,active) VALUES(?,?,1)').run(name,nr).lastInsertRowid||db.prepare('SELECT id FROM operators WHERE norm=?').get(nr)?.id||0);
 return{ok:true,id};
}
function financial(x,no=false){const type=txt(x.type).toLowerCase();if(!['invoice','dispatch'].includes(type)||num(x.qty)<=0)throw Error('Adet zorunlu');let bid=num(x.batchId);if(!bid&&x.modelId)bid=db.prepare("SELECT id FROM batches WHERE model_id=? AND status='OPEN' ORDER BY id DESC LIMIT 1").get(num(x.modelId))?.id||0;if(!bid)throw Error('Açık imalat kaydı bulunamadı');const b=totals(bid),cid=num(x.companyId)||num(b.company_id)||TAHA.id;db.prepare('INSERT INTO financial(batch_id,type,doc_no,date,qty,amount,company_id) VALUES(?,?,?,?,?,?,?)').run(bid,type,txt(x.docNo),txt(x.date)||today(),num(x.qty),type==='invoice'?num(x.amount):0,cid);db.prepare(`UPDATE batches SET ${type==='invoice'?'invoice_qty':'dispatch_qty'}=${type==='invoice'?'invoice_qty':'dispatch_qty'}+?,last_date=? WHERE id=?`).run(num(x.qty),txt(x.date)||today(),bid);if(type==='invoice'&&num(x.amount)>0)db.prepare('INSERT INTO company_movements(company_id,type,date,amount,doc_no,model_id,batch_id,note) VALUES(?,?,?,?,?,?,?,?)').run(cid,'INVOICE',txt(x.date)||today(),num(x.amount),txt(x.docNo),b.model_id,bid,txt(x.note));evaluate(bid);if(!no)event(type+'.create',{batchId:bid,companyId:cid,date:txt(x.date)||today(),docNo:txt(x.docNo),qty:num(x.qty),amount:num(x.amount),note:txt(x.note)});return{ok:true,batchId:bid}}
function payment(x,no=false){const cid=num(x.companyId)||TAHA.id;if(num(x.amount)<=0)throw Error('Tutar zorunlu');const id=Number(db.prepare('INSERT INTO company_movements(company_id,type,date,amount,doc_no,note) VALUES(?,?,?,?,?,?)').run(cid,'PAYMENT',txt(x.date)||today(),num(x.amount),txt(x.docNo),txt(x.note)).lastInsertRowid);if(!no)event('payment.create',{companyId:cid,date:txt(x.date)||today(),amount:num(x.amount),docNo:txt(x.docNo),note:txt(x.note)});return{ok:true,id}}
function reminder(x,no=false){if(!txt(x.party))throw Error('Kime ödeme yapılacağı zorunlu');let id;if(cols('payment_reminders').includes('payee'))id=Number(db.prepare('INSERT INTO payment_reminders(party,payee,description,due_date,amount,note,status,updated_at) VALUES(?,?,?,?,?,?,?,?)').run(txt(x.party),txt(x.party),txt(x.note),txt(x.dueDate)||today(),num(x.amount),txt(x.note),'PENDING',nowIso()).lastInsertRowid);else id=Number(db.prepare('INSERT INTO payment_reminders(party,due_date,amount,note,status,updated_at) VALUES(?,?,?,?,?,?)').run(txt(x.party),txt(x.dueDate)||today(),num(x.amount),txt(x.note),'PENDING',nowIso()).lastInsertRowid);if(!no)event('reminder.create',{party:txt(x.party),dueDate:txt(x.dueDate)||today(),amount:num(x.amount),note:txt(x.note)});return{ok:true,id}}
function reminderPaid(id,no=false){db.prepare("UPDATE payment_reminders SET status='PAID',paid_at=?,updated_at=? WHERE id=?").run(nowIso(),nowIso(),num(id));if(!no)event('reminder.paid',{id:num(id)});return{ok:true}}

function noteUpsert(x,no=false){
 const uid=txt(x.uid)||uuid(),title=txt(x.title),bodyText=txt(x.body);if(!bodyText)throw Error('Not içeriği zorunlu');
 const old=db.prepare('SELECT id FROM notes WHERE uid=?').get(uid);
 if(old)db.prepare('UPDATE notes SET title=?,body=?,author=?,target=?,category=?,priority=?,status=?,active=?,pinned=?,updated_at=? WHERE uid=?').run(title,bodyText,txt(x.author)||'Muhasebe',txt(x.target)||'Patron',txt(x.category)||'Genel',txt(x.priority)||'NORMAL',txt(x.status)||'AKTİF',(String(x.active)==='0'||x.active===0)?0:1,num(x.pinned)?1:0,nowIso(),uid);
 else db.prepare('INSERT INTO notes(uid,title,body,author,target,category,priority,status,active,pinned,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(uid,title,bodyText,txt(x.author)||'Muhasebe',txt(x.target)||'Patron',txt(x.category)||'Genel',txt(x.priority)||'NORMAL',txt(x.status)||'AKTİF',(String(x.active)==='0'||x.active===0)?0:1,num(x.pinned)?1:0,txt(x.createdAt)||nowIso(),nowIso());
 if(!no)event('note.upsert',{uid,title,body:bodyText,author:txt(x.author)||'Muhasebe',target:txt(x.target)||'Patron',category:txt(x.category)||'Genel',priority:txt(x.priority)||'NORMAL',status:txt(x.status)||'AKTİF',active:(String(x.active)==='0'||x.active===0)?0:1,pinned:num(x.pinned)?1:0,createdAt:txt(x.createdAt)||nowIso()});
 return{ok:true,uid};
}
function noteStatus(x,no=false){const uid=txt(x.uid);if(!uid)throw Error('Not bulunamadı');const active=(String(x.active)==='0'||x.active===0)?0:1;db.prepare('UPDATE notes SET status=?,active=?,updated_at=? WHERE uid=?').run(txt(x.status)||'AKTİF',active,nowIso(),uid);if(!no)event('note.status',{uid,status:txt(x.status)||'AKTİF',active});return{ok:true}}
function machineSave(x,no=false){
 const machineNo=txt(x.machineNo),original=txt(x.originalMachineNo)||machineNo;if(!machineNo)throw Error('Makine no zorunlu');
 if(original!==machineNo){const used=num(db.prepare('SELECT COUNT(*) c FROM entries WHERE machine_no=?').get(original)?.c);if(used>0)throw Error('Geçmiş üretimi olan makine no değiştirilemez. Eski makineyi pasif yapıp yeni makine ekleyin.');db.prepare('DELETE FROM machines WHERE machine_no=?').run(original)}
 const active=String(x.active)==='0'||x.active===0?0:1;db.prepare(`INSERT INTO machines(machine_no,machine_name,day_operator,day_assistant,night_operator,night_assistant,active) VALUES(?,?,?,?,?,?,?) ON CONFLICT(machine_no) DO UPDATE SET machine_name=excluded.machine_name,day_operator=excluded.day_operator,night_operator=excluded.night_operator,active=excluded.active`).run(machineNo,txt(x.machineName),txt(x.dayOperator),'',txt(x.nightOperator),'',active);
 if(!no)event('machine.update',{machineNo,machineName:txt(x.machineName),dayOperator:txt(x.dayOperator),nightOperator:txt(x.nightOperator),active});
 return{ok:true};
}
function machineRemove(x,no=false){const nox=txt(x.machineNo);if(!nox)throw Error('Makine no zorunlu');const used=num(db.prepare('SELECT COUNT(*) c FROM entries WHERE machine_no=?').get(nox)?.c);if(used>0)db.prepare('UPDATE machines SET active=0 WHERE machine_no=?').run(nox);else db.prepare('DELETE FROM machines WHERE machine_no=?').run(nox);if(!no)event('machine.remove',{machineNo:nox,soft:used>0});return{ok:true,soft:used>0}}
function addCheck(x,no=false){const id=Number(db.prepare(`INSERT INTO checks(direction,due_date,bank,serial_no,counterparty,drawer,amount,status,account_no,iban,note,source,receipt_received,receipt_by,receipt_note,against_text,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(txt(x.direction)||'OUT',txt(x.dueDate),txt(x.bank),txt(x.serialNo),txt(x.counterparty),txt(x.drawer),num(x.amount),txt(x.status)||(txt(x.direction)==='IN'?'PORTFÖY':'ÖDENECEK'),txt(x.accountNo),txt(x.iban),txt(x.note),'HAKAN EMP',num(x.receiptReceived),txt(x.receiptBy),txt(x.receiptNote),txt(x.againstText),nowIso()).lastInsertRowid);if(!no)event('check.create',{direction:txt(x.direction)||'OUT',dueDate:txt(x.dueDate),bank:txt(x.bank),serialNo:txt(x.serialNo),counterparty:txt(x.counterparty),drawer:txt(x.drawer),amount:num(x.amount),note:txt(x.note),againstText:txt(x.againstText)});return{ok:true,id}}
function setCheck(id,status,no=false){db.prepare('UPDATE checks SET status=?,updated_at=? WHERE id=?').run(txt(status),nowIso(),num(id));if(!no)event('check.status',{id:num(id),status:txt(status)});return{ok:true}}

function apply(e){if(!e?.event_id||db.prepare('SELECT 1 FROM sync_events WHERE event_id=?').get(e.event_id))return false;const p=e.payload||{},t=txt(e.event_type);if(t==='job.create')job(p,true);else if(t==='job.adjust')adjustJob(p,true);else if(t==='production.create')production(p,true);else if(t==='dispatch.create')financial({...p,type:'dispatch'},true);else if(t==='invoice.create')financial({...p,type:'invoice'},true);else if(t==='payment.create')payment(p,true);else if(t==='reminder.create')reminder(p,true);else if(t==='reminder.paid')reminderPaid(p.id,true);else if(t==='check.create')addCheck(p,true);else if(t==='check.status')setCheck(p.id,p.status,true);else if(t==='company.update'){let c=num(p.id)?db.prepare('SELECT id FROM companies WHERE id=?').get(num(p.id)):null;if(!c)c=db.prepare('SELECT id FROM companies WHERE norm=?').get(norm(p.name));if(c)db.prepare('UPDATE companies SET opening_balance=?,note=?,active=? WHERE id=?').run(num(p.openingBalance),txt(p.note),p.active===0?0:1,c.id);else db.prepare('INSERT INTO companies(name,norm,opening_balance,note,active) VALUES(?,?,?,?,?)').run(txt(p.name),norm(p.name),num(p.openingBalance),txt(p.note),p.active===0?0:1)}else if(t==='note.upsert')noteUpsert(p,true);else if(t==='note.status')noteStatus(p,true);else if(t==='machine.update')machineSave(p,true);else if(t==='machine.remove')machineRemove(p,true);else if(t==='operator.update')saveOperator({name:txt(p.name),active:p.active});else return false;db.prepare('INSERT OR IGNORE INTO sync_events(event_id,source_device,event_type,payload,direction,status,created_at,applied_at) VALUES(?,?,?,?,?,?,?,?)').run(e.event_id,txt(e.source_device)||'ANDROID',t,JSON.stringify(p),'IN','APPLIED',txt(e.created_at)||nowIso(),nowIso());return true}
function syncNow(){if(!SYNC)return{enabled:false,imported:0};let imported=0;for(const f of fs.readdirSync(ANDOUT).filter(x=>x.endsWith('.json'))){const full=path.join(ANDOUT,f);try{const e=JSON.parse(fs.readFileSync(full,'utf8'));if(apply(e))imported++;fs.writeFileSync(path.join(ACK,(e.event_id||path.parse(f).name)+'.json'),JSON.stringify({event_id:e.event_id,status:'APPLIED',at:nowIso()}));fs.renameSync(full,path.join(ARCH,'ANDROID_'+Date.now()+'_'+f))}catch(e){console.error('SYNC',e.message)}}db.prepare("INSERT OR REPLACE INTO settings(k,v) VALUES('last_sync',?)").run(nowIso());return{enabled:true,imported}}
setInterval(()=>{try{syncNow()}catch{}},600000).unref();

async function body(req,limit=12*1024*1024){return new Promise((res,rej)=>{let s='';req.on('data',c=>{s+=c;if(s.length>limit){rej(Error('İstek çok büyük'));req.destroy()}});req.on('end',()=>{try{res(s?JSON.parse(s):{})}catch(e){rej(e)}});req.on('error',rej)})}
function send(res,code,o){res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(o));return true}
function mime(f){const e=path.extname(f).toLowerCase();return e==='.css'?'text/css; charset=utf-8':e==='.js'?'text/javascript; charset=utf-8':e==='.png'?'image/png':['.jpg','.jpeg'].includes(e)?'image/jpeg':e==='.webp'?'image/webp':'text/html; charset=utf-8'}

async function api(req,res,u){
 if(req.method==='GET'&&u.pathname==='/api/dashboard')return send(res,200,dashboard(u.searchParams.get('week')||today()));
 if(req.method==='GET'&&u.pathname==='/api/completed')return send(res,200,{week:weekInfo(u.searchParams.get('week')||today()),rows:rows('TAMAM',u.searchParams.get('week')||today())});
 if(req.method==='GET'&&u.pathname==='/api/model-detail'){const x=detail(num(u.searchParams.get('modelId')),u.searchParams.get('week')||today());return x?send(res,200,x):send(res,404,{error:'Model bulunamadı'})}
 if(req.method==='GET'&&u.pathname==='/api/production-lookup')return send(res,200,productionLookup(u.searchParams.get('model')||''));
 if(req.method==='GET'&&u.pathname==='/api/companies')return send(res,200,companies());
 if(req.method==='GET'&&u.pathname==='/api/companies-all')return send(res,200,allCompanies());
 if(req.method==='GET'&&u.pathname==='/api/machines-all')return send(res,200,{rows:db.prepare("SELECT * FROM machines WHERE machine_no<>'0' ORDER BY COALESCE(active,1) DESC,CAST(machine_no AS INTEGER),machine_no").all()});
 if(req.method==='GET'&&u.pathname==='/api/notes')return send(res,200,{rows:db.prepare("SELECT * FROM notes ORDER BY pinned DESC,CASE status WHEN 'AKTİF' THEN 0 WHEN 'TAMAMLANDI' THEN 1 ELSE 2 END,updated_at DESC,id DESC").all()});
 if(req.method==='GET'&&u.pathname==='/api/reminders')return send(res,200,{rows:db.prepare(`SELECT *,CASE WHEN status='PAID' THEN 99999 ELSE CAST(julianday(due_date)-julianday(?) AS INTEGER) END days_remaining FROM payment_reminders ORDER BY CASE WHEN status='PENDING' THEN 0 ELSE 1 END,due_date,id DESC`).all(today())});
 if(req.method==='GET'&&u.pathname==='/api/checks')return send(res,200,{rows:db.prepare(`SELECT *,CASE WHEN due_date IS NULL OR due_date='' THEN 99999 ELSE CAST(julianday(due_date)-julianday(?) AS INTEGER) END days_remaining FROM checks ORDER BY CASE WHEN due_date='' OR due_date IS NULL THEN 1 ELSE 0 END,due_date,id DESC`).all(today())});
 if(req.method==='GET'&&u.pathname==='/api/settings'){const rows=db.prepare('SELECT k,v FROM settings').all();const values={};for(const r of rows)values[r.k]=r.v;return send(res,200,{values})}
 if(req.method==='GET'&&u.pathname==='/api/sync/status'){const last=db.prepare("SELECT v FROM settings WHERE k='last_sync'").get()?.v||'',pendingOut=PCOUT?fs.readdirSync(PCOUT).filter(x=>x.endsWith('.json')).length:0,pendingIn=ANDOUT?fs.readdirSync(ANDOUT).filter(x=>x.endsWith('.json')).length:0;return send(res,200,{enabled:!!SYNC,syncDir:SYNC,lastSync:last,pendingOut,pendingIn,intervalMinutes:10})}
 if(req.method==='GET'&&u.pathname==='/api/check-image'){const c=db.prepare('SELECT image_path FROM checks WHERE id=?').get(num(u.searchParams.get('id')));if(!c?.image_path||!fs.existsSync(c.image_path)){res.writeHead(404);return res.end('404')}res.writeHead(200,{'Content-Type':mime(c.image_path),'Cache-Control':'no-store'});fs.createReadStream(c.image_path).pipe(res);return true}
 if(req.method==='POST'&&u.pathname==='/api/job'){try{return send(res,200,job(await body(req)))}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/job-adjust'){try{return send(res,200,adjustJob(await body(req)))}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/production'){try{return send(res,200,production(await body(req)))}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/serial-production'){try{return send(res,200,serialProduction(await body(req)))}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/financial'){try{return send(res,200,financial(await body(req)))}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/payment'){try{return send(res,200,payment(await body(req)))}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/company'){const x=await body(req);try{let id=num(x.id),active=String(x.active)==='0'||x.active===0?0:1;if(!txt(x.name))throw Error('Firma adı zorunlu');if(id)db.prepare('UPDATE companies SET name=?,norm=?,opening_balance=?,note=?,active=? WHERE id=?').run(txt(x.name),norm(x.name),num(x.openingBalance),txt(x.note),active,id);else id=Number(db.prepare('INSERT INTO companies(name,norm,opening_balance,note,active) VALUES(?,?,?,?,?)').run(txt(x.name),norm(x.name),num(x.openingBalance),txt(x.note),active).lastInsertRowid);event('company.update',{id,name:txt(x.name),openingBalance:num(x.openingBalance),note:txt(x.note),active});return send(res,200,{ok:true,id})}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/reminder'){try{return send(res,200,reminder(await body(req)))}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/reminder-paid'){const x=await body(req);return send(res,200,reminderPaid(x.id))}
 if(req.method==='POST'&&u.pathname==='/api/note'){const x=await body(req);try{return send(res,200,noteUpsert(x))}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/note-status'){const x=await body(req);try{return send(res,200,noteStatus(x))}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/check'){try{return send(res,200,addCheck(await body(req)))}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/check-status'){const x=await body(req);return send(res,200,setCheck(x.id,x.status))}
 if(req.method==='POST'&&u.pathname==='/api/check-receipt'){const x=await body(req);db.prepare('UPDATE checks SET receipt_received=?,receipt_by=?,receipt_note=?,against_text=?,updated_at=? WHERE id=?').run(num(x.receiptReceived),txt(x.receiptBy),txt(x.receiptNote),txt(x.againstText),nowIso(),num(x.id));event('check.receipt',{id:num(x.id),receiptReceived:num(x.receiptReceived),receiptBy:txt(x.receiptBy),receiptNote:txt(x.receiptNote),againstText:txt(x.againstText)});return send(res,200,{ok:true})}
 if(req.method==='POST'&&u.pathname==='/api/check-image'){const x=await body(req),id=num(x.id),c=db.prepare('SELECT * FROM checks WHERE id=?').get(id);if(!c)return send(res,404,{error:'Çek bulunamadı'});const m=String(x.data||'').match(/^data:(image\/[a-zA-Z0-9.+-]+);base64,(.+)$/);if(!m)return send(res,400,{error:'Görsel okunamadı'});const ext=(m[1].split('/')[1]||'jpg').replace('jpeg','jpg').replace(/[^a-z0-9]/gi,'').slice(0,6),ym=(c.due_date||today()).slice(0,7).split('-'),p=path.join(IMGROOT,ym[0]||'TARIHSIZ',ym[1]||'00');dir(p);const f=path.join(p,'cek_'+id+'_'+Date.now()+'.'+ext);fs.writeFileSync(f,Buffer.from(m[2],'base64'));db.prepare('UPDATE checks SET image_path=?,updated_at=? WHERE id=?').run(f,nowIso(),id);return send(res,200,{ok:true})}
 if(req.method==='POST'&&u.pathname==='/api/machine'){const x=await body(req);try{return send(res,200,machineSave(x))}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/machine-remove'){const x=await body(req);try{return send(res,200,machineRemove(x))}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/operator'){const x=await body(req);try{const r=saveOperator(x);event('operator.update',{id:r.id,name:txt(x.name),active:x.active===0?0:1});return send(res,200,r)}catch(e){return send(res,400,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/settings'){const x=await body(req);const allowed=['default_company_id','default_shift','check_horizon_days','receipt_required'];for(const k of allowed)if(Object.prototype.hasOwnProperty.call(x,k))db.prepare('INSERT OR REPLACE INTO settings(k,v) VALUES(?,?)').run(k,txt(x[k]));return send(res,200,{ok:true})}
 if(req.method==='POST'&&u.pathname==='/api/sync/now'){try{return send(res,200,{ok:true,...syncNow()})}catch(e){return send(res,500,{error:e.message})}}
 if(req.method==='POST'&&u.pathname==='/api/backup'){backup();return send(res,200,{ok:true})}
 return false;
}
http.createServer(async(req,res)=>{try{const u=new URL(req.url,'http://127.0.0.1');if(u.pathname.startsWith('/api/')){if(await api(req,res,u)!==false)return;return send(res,404,{error:'Bulunamadı'})}const rel=u.pathname==='/'?'index.html':u.pathname.replace(/^\//,''),f=path.join(ROOT,'public',rel);if(!f.startsWith(path.join(ROOT,'public'))||!fs.existsSync(f)){res.writeHead(404);return res.end('404')}res.writeHead(200,{'Content-Type':mime(f),'Cache-Control':'no-store'});fs.createReadStream(f).pipe(res)}catch(e){send(res,500,{error:e.message})}}).listen(PORT,'127.0.0.1',()=>console.log('HAKAN EMP FINAL http://127.0.0.1:'+PORT));
