import {
  AlertTriangle,
  ArrowDownLeft,
  ArrowUpRight,
  Banknote,
  BarChart3,
  Bell,
  Building2,
  Calculator,
  CalendarDays,
  CheckCircle2,
  CircleDollarSign,
  Clock,
  CreditCard,
  Eye,
  FileCheck,
  FileInput,
  FileSpreadsheet,
  Files,
  FileText,
  Filter,
  Hourglass,
  Home,
  Info,
  Landmark,
  LayoutDashboard,
  Mail,
  Package,
  Boxes,
  Archive,
  Pencil,
  ReceiptText,
  RefreshCw,
  Save,
  Search,
  Settings,
  Trash2,
  Truck,
  UploadCloud,
  Users,
  Wallet,
} from "lucide-react";

const iconMap = {
  "genel-bakis": LayoutDashboard,
  dashboard: LayoutDashboard,
  home: Home,
  "model-takip-merkezi": Boxes,
  "gelen-model": Truck,
  arsiv: Archive,
  "firma-kartlari": Building2,
  urunler: Package,
  "musteri-irsaliye": Truck,
  "file-input": FileInput,
  "bizim-belgeler": Files,
  belge: FileText,
  "tedarikci-fatura": ReceiptText,
  "cari-kasa": Wallet,
  kasa: CircleDollarSign,
  odemeler: Banknote,
  cekler: Landmark,
  "file-check": FileCheck,
  "kredi-kartlari": CreditCard,
  kdv: Calculator,
  percent: Calculator,
  hesap: Calculator,
  eposta: Mail,
  raporlar: BarChart3,
  ayarlar: Settings,
  kaydet: Save,
  sil: Trash2,
  duzenle: Pencil,
  goruntule: Eye,
  filtrele: Filter,
  yenile: RefreshCw,
  ara: Search,
  yukle: UploadCloud,
  excel: FileSpreadsheet,
  uyari: AlertTriangle,
  "arrow-down": ArrowDownLeft,
  "arrow-up": ArrowUpRight,
  bilgi: Info,
  onay: CheckCircle2,
  saat: Clock,
  vade: Hourglass,
  takvim: CalendarDays,
  users: Users,
  bildirim: Bell,
};

export function ErpIcon({ name, size = 16, className = "", strokeWidth = 2 }) {
  const Icon = iconMap[name] || Info;
  return (
    <Icon
      aria-hidden="true"
      className={className}
      size={size}
      strokeWidth={strokeWidth}
    />
  );
}
