<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>HKN.PDKS.HizliIslem</AssemblyName>
    <Product>HKN PDKS Hızlı İşlem</Product>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\KYERP.PDKS.Core\KYERP.PDKS.Core.csproj" />
  </ItemGroup>
</Project>
