import test from 'node:test';
import assert from 'node:assert/strict';
import { parseProductionEntries, validateProductionRows } from './productionEntryParser.js';

const dictionaries={models:[{id:'w',modelName:'WINDY',printRegions:[{regionName:'Ön'},{regionName:'Arka'},{regionName:'Kol'}]},{id:'m',modelName:'MERVOD POLO',printRegions:[{regionName:'Ön'},{regionName:'Kol'}]},{id:'e1',modelName:'EPULS A'},{id:'e2',modelName:'EPULS A SARI'},{id:'e3',modelName:'EPULS A SARI REPETE'}],machines:[{id:'mk1',machineNo:'1',machineName:'Makine 1'}],operators:[{id:'murat',name:'Murat'},{id:'suphi',name:'Süphi'},{id:'resul',name:'Resul'}]};
const defaults={date:'2026-07-15',shift:'Gündüz',machineId:'mk1',machineName:'Makine 1'};
for(const line of ['15 windy ekru ön 2500 gündüz murat','windy murat 2500 ön gündüz 15','2500 windy 15 murat gündüz ön','murat windy ön 2500 15 gündüz']) test(line,()=>{const [row]=parseProductionEntries(line,dictionaries,defaults);assert.equal(row.modelId,'w');assert.equal(row.quantity,2500);assert.equal(row.date,'2026-07-15');assert.equal(row.printRegion,'Ön')});
test('bir satırdaki bölge-adet çiftlerini ayırır',()=>{const rows=parseProductionEntries('15 mervod polo ön 2500 kol 2400 gündüz murat',dictionaries,defaults);assert.deepEqual(rows.map(x=>[x.printRegion,x.quantity]),[['Ön',2500],['Kol',2400]])});
test('bağlamı alt satırlara taşır',()=>{const rows=parseProductionEntries('15.07.2026 windy ekru gündüz murat\nön 2500\narka 2480\nkol 4950',dictionaries,defaults).filter(x=>x.quantity);assert.equal(rows.length,3);assert.ok(rows.every(x=>x.modelId==='w'&&x.date==='2026-07-15'))});
test('geçersiz tarihi reddeder',()=>{const [row]=parseProductionEntries('32-15 windy ön 2500 murat',dictionaries,defaults);assert.equal(row.status,'error');assert.match(row.warnings.join(' '),/Geçersiz tarih/)});
test('benzer modellerde kontrol ister',()=>{const [row]=parseProductionEntries('epuls a sarı 900 resul',dictionaries,defaults);assert.notEqual(row.status,'ready')});
test('gündüz 1 makine eşleşmesinden kayıtlı makinacıyı getirir',()=>{const dict={...dictionaries,machines:[{id:'mk1',machineNo:'1',machineName:'Makine 1',dayOperator:'Murat',nightOperator:'Süphi'}]};const [row]=parseProductionEntries('windy ön 2500 gündüz 1',dict,{date:'2026-07-15',shift:'Gündüz'});assert.equal(row.machineId,'mk1');assert.equal(row.operatorName,'Murat');assert.equal(row.date,'2026-07-15');assert.equal(row.status,'ready')});
test('aynı fişte yinelenen üretim satırını bloke eder',()=>{const base={id:'1',date:'2026-07-15',modelId:'w',printRegion:'Ön',quantity:2500,shift:'Gündüz',machineId:'mk1',operatorName:'Murat',warnings:[]};const rows=validateProductionRows([base,{...base,id:'2'}]);assert.equal(rows[0].status,'ready');assert.equal(rows[1].status,'error');assert.match(rows[1].warnings.join(' '),/yineleniyor/)});
