// @ts-nocheck
import type { Context, Hono } from "hono";
import { registerAccountingDocumentReviewRoutes } from "./accounting-document-review";

type AppEnv={Bindings:Cloudflare.Env;Variables:{requestId:string}};
type Row=Record<string,any>;
const text=(v:unknown)=>v==null?"":String(v).trim();
const upper=(v:unknown)=>text(v).toLocaleUpperCase("tr-TR");
const num=(v:unknown)=>{const n=Number(v??0);return Number.isFinite(n)?n:0};
const now=()=>new Date().toISOString();
const slugOf=(c:Context<AppEnv>,b:Row={})=>text(b.mainCompanySlug||b.main_company_slug||b.mainCompanyId||c.req.query("mainCompanySlug")||c.req.query("mainCompanyId")||c.req.header("X-KYERP-Tenant-Slug")||"mecit-hakan");
async function bodyOf(c:Context<AppEnv>):Promise<Row>{try{const b=await c.req.json();return b&&typeof b==="object"&&!Array.isArray(b)?b as Row:{}}catch{return{}}}
const err=(code:string,message:string)=>({ok:false,success:false,error:{code,message}});
function iso(d:Date){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function mondayRange(offsetWeeks=0){const d=new Date(),day=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day+offsetWeeks*7);const e=new Date(d);e.setDate(d.getDate()+6);return{from:iso(d),to:iso(e)}}
function weekendRange(offsetWeeks=0){const r=mondayRange(offsetWeeks),m=new Date(`${r.from}T00:00:00`);m.setDate(m.getDate()+5);const s=new Date(m);s.setDate(m.getDate()+1);return{from:iso(m),to:iso(s)}}
function parseCsvLine(line:string,delimiter:string){const out:string[]=[];let cur="",quote=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quote&&line[i+1]==='"'){cur+='"';i++}else quote=!quote}else if(ch===delimiter&&!quote){out.push(cur.trim());cur=""}else cur+=ch}out.push(cur.trim());return out}
function parseAmount(v:string){let s=text(v).replace(/[₺$€\s]/g,"").replace(/[^0-9,.-]/g,"");const c=s.lastIndexOf(","),d=s.lastIndexOf("."),idx=Math.max(c,d);if(c>=0&&d>=0)s=`${s.slice(0,idx).replace(/[,.]/g,"")}.${s.slice(idx+1).replace(/[,.]/g,"")}`;else if(c>=0)s=s.replace(/\./g,"").replace(",",".");const n=Number(s);return Number.isFinite(n)?n:0}
function normalize(v:unknown){return upper(v).replace(/İ/g,"I").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^A-Z0-9ÇĞÖŞÜ]+/g," ").replace(/\s+/g," ").trim()}
async function matchCompany(c:Context<AppEnv>,slug:string,name:string,iban:string){if(iban){const clean=iban.replace(/\s/g,"");const rows=await c.env.DB.prepare(`SELECT id,name FROM companies WHERE main_company_slug=? AND deleted_at IS NULL AND UPPER(COALESCE(note,'')) LIKE UPPER(?) LIMIT 1`).bind(slug,`%${clean}%`).first<Row>();if(rows)return{id:rows.id,name:rows.name,confidence:.9}}const n=normalize(name);if(n){const r=await c.env.DB.prepare(`SELECT c.id,c.name FROM company_aliases a JOIN companies c ON c.id=a.company_id AND c.main_company_slug=a.main_company_slug WHERE a.main_company_slug=? AND a.deleted_at IS NULL AND a.is_active=1 AND a.normalized_name=? LIMIT 1`).bind(slug,n).first<Row>();if(r)return{id:r.id,name:r.name,confidence:.96}}return{id:"",name,confidence:0}}

export function registerAccountingOperationRoutes(app:Hono<AppEnv>){
 registerAccountingDocumentReviewRoutes(app);
 app.get("/api/muhasebe/odeme-plani/hafta",async c=>{const slug=slugOf(c),range=mondayRange(Number(c.req.query("offset")||0)),r=await c.env.DB.prepare(`SELECT * FROM accounting_payment_plans WHERE main_company_slug=? AND status NOT IN ('PAID','CANCELLED') AND COALESCE(planned_date,due_date) BETWEEN ? AND ? ORDER BY COALESCE(planned_date,due_date),CASE priority WHEN 'URGENT' THEN 0 WHEN 'HIGH' THEN 1 ELSE 2 END,amount DESC`).bind(slug,range.from,range.to).all<Row>();return c.json({ok:true,data:{...range,rows:r.results||[]}})});
 app.get("/api/muhasebe/odeme-plani/hafta-sonu",async c=>{const slug=slugOf(c),range=weekendRange(Number(c.req.query("offset")||0)),r=await c.env.DB.prepare(`SELECT * FROM accounting_payment_plans WHERE main_company_slug=? AND status NOT IN ('PAID','CANCELLED') AND COALESCE(planned_date,due_date) BETWEEN ? AND ? ORDER BY COALESCE(planned_date,due_date),amount DESC`).bind(slug,range.from,range.to).all<Row>();return c.json({ok:true,data:{...range,rows:r.results||[]}})});
 app.post("/api/muhasebe/odeme-plani/:id/paid",async c=>{const b=await bodyOf(c),slug=slugOf(c,b),id=c.req.param("id"),ts=now(),plan=await c.env.DB.prepare(`SELECT * FROM accounting_payment_plans WHERE id=? AND main_company_slug=? LIMIT 1`).bind(id,slug).first<Row>();if(!plan)return c.json(err("NOT_FOUND","Ödeme planı bulunamadı."),404);const paid=num(b.paidAmount||b.amount||plan.amount),status=paid>=num(plan.amount)?"PAID":"PARTIAL";await c.env.DB.prepare(`UPDATE accounting_payment_plans SET paid_amount=?,status=?,updated_at=? WHERE id=? AND main_company_slug=?`).bind(paid,status,ts,id,slug).run();const ledgerId=crypto.randomUUID();await c.env.DB.prepare(`INSERT INTO accounting_ledger_entries(id,main_company_slug,entry_date,entry_type,record_scope,company_id,company_name,description,debit,credit,currency,payment_method,bank_account_id,source_document_id,source_payment_plan_id,file_asset_id,note,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(ledgerId,slug,text(b.paymentDate)||ts.slice(0,10),"ODEME","OFFICIAL",text(plan.counterparty_id)||null,text(plan.counterparty_name),text(b.description)||text(plan.description)||"Planlanan ödeme",paid,0,text(plan.currency)||"TRY",text(b.paymentMethod||plan.payment_method)||null,text(b.bankAccountId||plan.bank_account_id)||null,text(plan.source_document_id)||null,id,text(b.fileAssetId)||null,text(b.note)||null,text(b.createdBy)||null,ts,ts).run();return c.json({ok:true,data:{id,status,paidAmount:paid,ledgerEntryId:ledgerId}})});
 app.get("/api/muhasebe/hatirlatmalar",async c=>{const slug=slugOf(c),until=text(c.req.query("until"))||new Date(Date.now()+7*86400000).toISOString(),r=await c.env.DB.prepare(`SELECT * FROM accounting_payment_plans WHERE main_company_slug=? AND reminder_enabled=1 AND status NOT IN ('PAID','CANCELLED') AND reminder_at IS NOT NULL AND reminder_at<=? ORDER BY reminder_at`).bind(slug,until).all<Row>();return c.json({ok:true,data:r.results||[]})});
 app.get("/api/muhasebe/belge-okuma-profilleri",async c=>{const slug=slugOf(c),r=await c.env.DB.prepare(`SELECT * FROM accounting_extraction_profiles WHERE main_company_slug=? ORDER BY is_active DESC,party_tax_no,document_type`).bind(slug).all<Row>();return c.json({ok:true,data:r.results||[]})});
 app.post("/api/muhasebe/belge-okuma-profilleri",async c=>{const b=await bodyOf(c),slug=slugOf(c,b),id=text(b.id)||crypto.randomUUID(),ts=now();await c.env.DB.prepare(`INSERT INTO accounting_extraction_profiles(id,main_company_slug,party_company_id,party_tax_no,party_name_pattern,document_type,provider_type,provider_model_id,min_confidence,field_hints,is_active,successful_samples,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,0,?,?) ON CONFLICT(id) DO UPDATE SET party_company_id=excluded.party_company_id,party_tax_no=excluded.party_tax_no,party_name_pattern=excluded.party_name_pattern,document_type=excluded.document_type,provider_type=excluded.provider_type,provider_model_id=excluded.provider_model_id,min_confidence=excluded.min_confidence,field_hints=excluded.field_hints,is_active=excluded.is_active,updated_at=excluded.updated_at`).bind(id,slug,text(b.partyCompanyId)||null,text(b.partyTaxNo)||null,text(b.partyNamePattern)||null,text(b.documentType)||"GELEN_FATURA",text(b.providerType)||"AZURE_DOCUMENT_INTELLIGENCE",text(b.providerModelId)||null,num(b.minConfidence)||.75,JSON.stringify(b.fieldHints||{}),b.isActive===false?0:1,ts,ts).run();return c.json({ok:true,data:{id}},201)});
 app.post("/api/muhasebe/banka/import-csv",async c=>{const form=await c.req.parseBody({all:true}) as any,candidate=Array.isArray(form.file)?form.file[0]:form.file,file=candidate instanceof File?candidate:null;if(!file)return c.json(err("FILE_REQUIRED","Banka CSV dosyası zorunludur."),400);const slug=text(form.mainCompanySlug||c.req.header("X-KYERP-Tenant-Slug")||"mecit-hakan"),raw=await file.text(),lines=raw.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(lines.length<2)return c.json(err("CSV_EMPTY","CSV içinde hareket bulunamadı."),422);const delimiter=(lines[0].match(/;/g)||[]).length>=(lines[0].match(/,/g)||[]).length?";":",",headers=parseCsvLine(lines[0],delimiter).map(normalize),batchId=crypto.randomUUID(),ts=now();let matched=0,unmatched=0;for(let i=1;i<lines.length;i++){const cells=parseCsvLine(lines[i],delimiter),row:any={};headers.forEach((h,idx)=>row[h]=cells[idx]||"");const date=text(row.TARIH||row.ISLEM_TARIHI||row.DATE),desc=text(row.ACIKLAMA||row.DESCRIPTION||row.ISLEM_ACIKLAMASI),iban=text(row.IBAN||row.KARSI_IBAN||row.ALICI_IBAN),name=text(row.FIRMA||row.UNVAN||row.ALICI||row.GONDEREN),rawAmount=text(row.TUTAR||row.AMOUNT||row.MEBLAG),amount=parseAmount(rawAmount),direction=amount<0||/BORC|CIKIS|GIDEN/.test(upper(row.YON||row.TIP))?"OUT":"IN",match=await matchCompany(c,slug,name,iban);if(match.id)matched++;else unmatched++;await c.env.DB.prepare(`INSERT INTO accounting_bank_import_rows(id,main_company_slug,batch_id,row_no,transaction_date,value_date,description,reference_no,amount,direction,currency,counterparty_name,counterparty_iban,company_id,match_status,match_confidence,raw_data,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),slug,batchId,i,date||null,text(row.VALOR||row.VALUE_DATE)||null,desc||null,text(row.REFERANS||row.REFERENCE)||null,Math.abs(amount),direction,text(row.PARA_BIRIMI||row.CURRENCY)||"TRY",name||null,iban||null,match.id||null,match.id?"AUTO_MATCHED":"UNMATCHED",match.confidence,JSON.stringify(row),ts,ts).run()}await c.env.DB.prepare(`INSERT INTO accounting_bank_import_batches(id,main_company_slug,source_type,bank_name,account_name,iban,original_file_name,row_count,matched_count,unmatched_count,status,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(batchId,slug,"BANK_CSV",text(form.bankName)||null,text(form.accountName)||null,text(form.iban)||null,file.name,lines.length-1,matched,unmatched,"IMPORTED",text(form.createdBy)||null,ts,ts).run();return c.json({ok:true,data:{batchId,rowCount:lines.length-1,matchedCount:matched,unmatchedCount:unmatched}},201)});
 app.get("/api/muhasebe/banka/import/:batchId",async c=>{const slug=slugOf(c),id=c.req.param("batchId"),batch=await c.env.DB.prepare(`SELECT * FROM accounting_bank_import_batches WHERE id=? AND main_company_slug=? LIMIT 1`).bind(id,slug).first<Row>();if(!batch)return c.json(err("NOT_FOUND","Banka importu bulunamadı."),404);const rows=await c.env.DB.prepare(`SELECT * FROM accounting_bank_import_rows WHERE batch_id=? AND main_company_slug=? ORDER BY row_no`).bind(id,slug).all<Row>();return c.json({ok:true,data:{batch,rows:rows.results||[]}})});
}
