// @ts-nocheck
import type { Context, Hono } from "hono";

type AppEnv={Bindings:Cloudflare.Env;Variables:{requestId:string}};
type Row=Record<string,any>;
const text=(v:unknown)=>v==null?"":String(v).trim();
const num=(v:unknown)=>{const n=Number(v??0);return Number.isFinite(n)?n:0};
const now=()=>new Date().toISOString();
const slugOf=(c:Context<AppEnv>,b:Row={})=>text(b.mainCompanySlug||b.main_company_slug||b.mainCompanyId||c.req.query("mainCompanySlug")||c.req.query("mainCompanyId")||c.req.header("X-KYERP-Tenant-Slug")||"mecit-hakan");
async function bodyOf(c:Context<AppEnv>):Promise<Row>{try{const b=await c.req.json();return b&&typeof b==="object"&&!Array.isArray(b)?b as Row:{}}catch{return{}}}
const err=(code:string,message:string)=>({ok:false,success:false,error:{code,message}});

async function documentExists(c:Context<AppEnv>,slug:string,id:string){return c.env.DB.prepare(`SELECT id,status FROM accounting_documents WHERE id=? AND main_company_slug=? AND deleted_at IS NULL LIMIT 1`).bind(id,slug).first<Row>()}
async function recalc(c:Context<AppEnv>,slug:string,id:string){const r=await c.env.DB.prepare(`SELECT COALESCE(SUM(line_total),0) subtotal,COALESCE(SUM(tax_amount),0) tax_total,COALESCE(SUM(discount_total),0) discount_total FROM accounting_document_lines WHERE main_company_slug=? AND document_id=?`).bind(slug,id).first<Row>();const subtotal=num(r?.subtotal),tax=num(r?.tax_total),discount=num(r?.discount_total),payable=subtotal+tax-discount;await c.env.DB.prepare(`UPDATE accounting_documents SET subtotal=?,tax_total=?,discount_total=?,payable_total=?,updated_at=? WHERE id=? AND main_company_slug=?`).bind(subtotal,tax,discount,payable,now(),id,slug).run();return{subtotal,taxTotal:tax,discountTotal:discount,payableTotal:payable}}
async function addIssue(c:Context<AppEnv>,slug:string,id:string,code:string,message:string,severity="WARNING",field=""){await c.env.DB.prepare(`INSERT INTO accounting_document_issues(id,main_company_slug,document_id,issue_code,severity,field_name,message,is_resolved,created_at) VALUES(?,?,?,?,?,?,?,0,?)`).bind(crypto.randomUUID(),slug,id,code,severity,field||null,message,now()).run()}

export function registerAccountingDocumentReviewRoutes(app:Hono<AppEnv>){
 app.patch("/api/muhasebe/belge-havuzu/:id",async c=>{const b=await bodyOf(c),slug=slugOf(c,b),id=c.req.param("id"),doc=await documentExists(c,slug,id);if(!doc)return c.json(err("NOT_FOUND","Belge bulunamadı."),404);const allowed:{[k:string]:string}={documentType:"document_type",documentNo:"document_no",issueDate:"issue_date",dueDate:"due_date",currency:"currency",partyCompanyId:"party_company_id",partyName:"party_name",partyTaxNo:"party_tax_no",partyTaxOffice:"party_tax_office",partyIban:"party_iban",recordScope:"record_scope",note:"note"},sets:string[]=[],args:any[]=[];for(const [key,col] of Object.entries(allowed)){if(Object.prototype.hasOwnProperty.call(b,key)){sets.push(`${col}=?`);args.push(text(b[key])||null)}}if(!sets.length)return c.json({ok:true,data:{id,unchanged:true}});sets.push("status='REVIEW_REQUIRED'","updated_at=?");args.push(now(),id,slug);await c.env.DB.prepare(`UPDATE accounting_documents SET ${sets.join(",")} WHERE id=? AND main_company_slug=?`).bind(...args).run();if(Object.prototype.hasOwnProperty.call(b,"partyCompanyId")&&text(b.partyCompanyId)){await c.env.DB.prepare(`UPDATE accounting_document_issues SET is_resolved=1,resolved_by=?,resolved_at=? WHERE main_company_slug=? AND document_id=? AND issue_code='PARTY_UNMATCHED' AND is_resolved=0`).bind(text(b.updatedBy)||null,now(),slug,id).run()}return c.json({ok:true,data:{id,status:"REVIEW_REQUIRED"}})});
 app.patch("/api/muhasebe/belge-havuzu/:id/lines/:lineId",async c=>{const b=await bodyOf(c),slug=slugOf(c,b),id=c.req.param("id"),lineId=c.req.param("lineId"),doc=await documentExists(c,slug,id);if(!doc)return c.json(err("NOT_FOUND","Belge bulunamadı."),404);const current=await c.env.DB.prepare(`SELECT * FROM accounting_document_lines WHERE id=? AND main_company_slug=? AND document_id=? LIMIT 1`).bind(lineId,slug,id).first<Row>();if(!current)return c.json(err("LINE_NOT_FOUND","Belge kalemi bulunamadı."),404);const qty=Object.prototype.hasOwnProperty.call(b,"quantity")?num(b.quantity):num(current.quantity),unitPrice=Object.prototype.hasOwnProperty.call(b,"unitPrice")?num(b.unitPrice):num(current.unit_price),discount=Object.prototype.hasOwnProperty.call(b,"discountTotal")?num(b.discountTotal):num(current.discount_total),taxRate=Object.prototype.hasOwnProperty.call(b,"taxRate")?num(b.taxRate):num(current.tax_rate),base=Math.max(0,qty*unitPrice-discount),tax=Object.prototype.hasOwnProperty.call(b,"taxAmount")?num(b.taxAmount):base*taxRate/100,lineTotal=Object.prototype.hasOwnProperty.call(b,"lineTotal")?num(b.lineTotal):base;await c.env.DB.prepare(`UPDATE accounting_document_lines SET product_id=?,product_code=?,supplier_product_code=?,description=?,quantity=?,unit_code=?,unit_price=?,discount_total=?,tax_rate=?,tax_amount=?,line_total=?,match_status=?,match_confidence=?,updated_at=? WHERE id=? AND main_company_slug=? AND document_id=?`).bind(text(b.productId??current.product_id)||null,text(b.productCode??current.product_code)||null,text(b.supplierProductCode??current.supplier_product_code)||null,text(b.description??current.description)||null,qty,text(b.unitCode??current.unit_code)||null,unitPrice,discount,taxRate,tax,lineTotal,text(b.productId??current.product_id)?"MANUAL":text(current.match_status)||"UNMATCHED",text(b.productId??current.product_id)?1:num(current.match_confidence),now(),lineId,slug,id).run();await c.env.DB.prepare(`UPDATE accounting_documents SET status='REVIEW_REQUIRED',updated_at=? WHERE id=? AND main_company_slug=?`).bind(now(),id,slug).run();const totals=await recalc(c,slug,id);return c.json({ok:true,data:{id:lineId,...totals}})});
 app.post("/api/muhasebe/belge-havuzu/:id/issues/:issueId/resolve",async c=>{const b=await bodyOf(c),slug=slugOf(c,b),id=c.req.param("id"),issueId=c.req.param("issueId");await c.env.DB.prepare(`UPDATE accounting_document_issues SET is_resolved=1,resolved_by=?,resolved_at=? WHERE id=? AND main_company_slug=? AND document_id=?`).bind(text(b.resolvedBy)||null,now(),issueId,slug,id).run();return c.json({ok:true,data:{issueId,resolved:true}})});
 app.post("/api/muhasebe/belge-havuzu/:id/revalidate",async c=>{const b=await bodyOf(c),slug=slugOf(c,b),id=c.req.param("id"),doc=await c.env.DB.prepare(`SELECT * FROM accounting_documents WHERE id=? AND main_company_slug=? AND deleted_at IS NULL LIMIT 1`).bind(id,slug).first<Row>();if(!doc)return c.json(err("NOT_FOUND","Belge bulunamadı."),404);await c.env.DB.prepare(`DELETE FROM accounting_document_issues WHERE main_company_slug=? AND document_id=? AND is_resolved=0 AND issue_code IN ('TOTAL_MISMATCH','PARTY_UNMATCHED','LINES_MISSING')`).bind(slug,id).run();const lines=await c.env.DB.prepare(`SELECT * FROM accounting_document_lines WHERE main_company_slug=? AND document_id=? ORDER BY line_no`).bind(slug,id).all<Row>();if(!text(doc.party_company_id))await addIssue(c,slug,id,"PARTY_UNMATCHED","Firma/cari seçilmelidir.");if(!(lines.results||[]).length)await addIssue(c,slug,id,"LINES_MISSING","Belgede en az bir kalem bulunmalıdır.","ERROR","lines");const totals=await recalc(c,slug,id),declared=num(doc.payable_total);if(declared&&Math.abs(declared-totals.payableTotal)>.02)await addIssue(c,slug,id,"TOTAL_MISMATCH",`Kalem toplamı ile belge toplamı uyuşmuyor (${declared.toFixed(2)} / ${totals.payableTotal.toFixed(2)}).`,"WARNING","payable_total");const open=await c.env.DB.prepare(`SELECT COUNT(*) n FROM accounting_document_issues WHERE main_company_slug=? AND document_id=? AND is_resolved=0`).bind(slug,id).first<Row>();const status=num(open?.n)?"REVIEW_REQUIRED":"READY_FOR_APPROVAL";await c.env.DB.prepare(`UPDATE accounting_documents SET status=?,updated_at=? WHERE id=? AND main_company_slug=?`).bind(status,now(),id,slug).run();return c.json({ok:true,data:{id,status,openIssueCount:num(open?.n),totals}})});
}
