// @ts-nocheck
import type { Context, Hono } from "hono";
import { getAuthenticatedUser } from "./auth-cloud";

type AppEnv={Bindings:Cloudflare.Env;Variables:{requestId:string}};
type Row=Record<string,any>;
const text=(v:unknown)=>v==null?"":String(v).trim();
const upper=(v:unknown)=>text(v).toLocaleUpperCase("tr-TR").replace(/İ/g,"I");
const lower=(v:unknown)=>text(v).toLocaleLowerCase("tr-TR");
const now=()=>new Date().toISOString();
const dateOnly=(v:unknown)=>text(v).slice(0,10);
const json=(v:unknown,f:any={})=>{if(v&&typeof v==="object")return v;try{return JSON.parse(text(v)||JSON.stringify(f))}catch{return f}};
const err=(code:string,message:string)=>({ok:false,success:false,error:{code,message}});
async function bodyOf(c:Context<AppEnv>):Promise<Row>{try{const b=await c.req.json();return b&&typeof b==="object"&&!Array.isArray(b)?b as Row:{}}catch{return{}}}
function isOwner(u:Row){return["SUPER_ADMIN","ADMIN"].includes(upper(u?.role))}
function isCompanyAdmin(u:Row){return upper(u?.role)==="COMPANY_ADMIN"}
function permission(u:Row){return(Array.isArray(u?.permissions)?u.permissions:[]).find((p:Row)=>upper(p.moduleKey||p.module_key)==="COMPLIANCE")||null}
function canView(u:Row){return isOwner(u)||isCompanyAdmin(u)||Boolean(permission(u)?.canView??permission(u)?.can_view)}
function canWrite(u:Row){const p=permission(u);return isOwner(u)||isCompanyAdmin(u)||Boolean(p?.canCreate??p?.can_create??p?.canUpdate??p?.can_update)}
function ownSlug(u:Row){return lower(u?.mainCompanySlug||u?.main_company_slug||u?.security?.main_company_slug)}
function requestedSlug(c:Context<AppEnv>,b:Row={}){return lower(b.mainCompanySlug||b.main_company_slug||c.req.query("mainCompanySlug")||c.req.header("X-KYERP-Tenant-Slug"))}
async function scope(c:Context<AppEnv>,body:Row={},write=false){const u=await getAuthenticatedUser(c) as Row|null;if(!u||!canView(u)||(write&&!canWrite(u)))return{ok:false,status:u?403:401,user:u,slug:""};const requested=requestedSlug(c,body),own=ownSlug(u);if(!isOwner(u)){if(!own||(requested&&requested!==own))return{ok:false,status:403,user:u,slug:""};return{ok:true,status:200,user:u,slug:own}}const slug=requested||own;if(!slug)return{ok:false,status:400,user:u,slug:""};return{ok:true,status:200,user:u,slug}}
function scopeError(c:Context<AppEnv>,s:Row){return c.json(err(s.status===401?"UNAUTHORIZED":"COMPLIANCE_FORBIDDEN",s.status===401?"Oturum gerekli.":"Denetim Merkezi için yetkiniz yok."),s.status as any)}
async function tableExists(c:Context<AppEnv>,name:string){try{const r=await c.env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=? LIMIT 1").bind(name).first<Row>();return Boolean(r?.name)}catch{return false}}
async function requireFinalSchema(c:Context<AppEnv>){for(const n of["compliance_audit_documents","compliance_audit_shares","compliance_finding_capa","compliance_finding_evidence"])if(!(await tableExists(c,n)))return false;return true}
async function event(c:Context<AppEnv>,slug:string,eventType:string,entityType:string,entityId:string,userId:string,detail:Row={}){try{await c.env.DB.prepare("INSERT INTO compliance_events(id,main_company_slug,event_type,entity_type,entity_id,actor_user_id,detail,created_at) VALUES(?,?,?,?,?,?,?,?)").bind(crypto.randomUUID(),slug,eventType,entityType,entityId,userId||null,JSON.stringify(detail),now()).run()}catch{}}
function safeName(v:unknown){return text(v).replace(/[^A-Za-z0-9._ÇĞİÖŞÜçğıöşü -]+/g,"_").slice(0,160)||"kanit"}
const ALLOWED_EXT=new Set(["JPG","JPEG","PNG","WEBP","PDF","DOC","DOCX","XLS","XLSX","CSV"]);
function fileExt(file:File){return upper(file.name.split(".").pop()||"")}
function validateFile(file:File,maxMb=40){const ext=fileExt(file);if(!ALLOWED_EXT.has(ext))return{ok:false,message:"Yalnız JPG/JPEG, PNG, WEBP, PDF, Word (DOC/DOCX), Excel (XLS/XLSX) ve CSV yüklenebilir."};if(file.size<=0)return{ok:false,message:"Dosya boş."};if(file.size>maxMb*1024*1024)return{ok:false,message:`Dosya en fazla ${maxMb} MB olabilir.`};return{ok:true,ext}}
async function hashToken(token:string){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(token));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
function randomToken(){const b=new Uint8Array(32);crypto.getRandomValues(b);return btoa(String.fromCharCode(...b)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/,"")}
async function auditOwned(c:Context<AppEnv>,slug:string,id:string){return c.env.DB.prepare("SELECT a.*,p.name profile_name,p.code profile_code FROM compliance_audits a LEFT JOIN compliance_profiles p ON p.id=a.profile_id WHERE a.id=? AND a.main_company_slug=? LIMIT 1").bind(id,slug).first<Row>()}
async function fileAsset(c:Context<AppEnv>,slug:string,file:File,purpose:string,entityId:string){const check=validateFile(file);if(!check.ok)throw Object.assign(new Error(check.message),{code:"FILE_TYPE"});const id=crypto.randomUUID(),ts=now(),name=safeName(file.name),key=`compliance/${slug}/${purpose.toLowerCase()}/${entityId}/${id}-${name}`;await c.env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type||"application/octet-stream"},customMetadata:{purpose,entityId,mainCompanySlug:slug,originalName:file.name}});await c.env.DB.prepare("INSERT INTO file_hub_assets(id,main_company_slug,logical_key,file_name,extension,mime_type,size_bytes,status,source_type,preview_status,preview_storage_key,metadata,first_seen_at,last_seen_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'AVAILABLE','COMPLIANCE_UPLOAD','READY',?,?,?, ?,?,?)").bind(id,slug,`compliance:${purpose.toLowerCase()}:${entityId}`,file.name,check.ext,file.type||null,file.size,key,JSON.stringify({storageKey:key,purpose,entityId}),ts,ts,ts,ts).run();return{id,key,fileName:file.name,mimeType:file.type||"application/octet-stream",size:file.size}}
async function shareByToken(c:Context<AppEnv>,token:string){if(!token||token.length<24)return null;const hash=await hashToken(token),today=now();const share=await c.env.DB.prepare("SELECT s.*,a.name audit_name,a.profile_id,a.audit_type,a.planned_date,a.completed_date,a.auditor_name,a.status audit_status,a.notes,p.name profile_name,p.code profile_code FROM compliance_audit_shares s JOIN compliance_audits a ON a.id=s.audit_id AND a.main_company_slug=s.main_company_slug LEFT JOIN compliance_profiles p ON p.id=a.profile_id WHERE s.token_hash=? AND s.revoked_at IS NULL AND s.expires_at>? LIMIT 1").bind(hash,today).first<Row>();return share||null}

export function registerComplianceOperationsRoutes(app:Hono<AppEnv>){
 app.get("/api/compliance/audits/:id/workspace",async c=>{const s=await scope(c);if(!s.ok)return scopeError(c,s);if(!(await requireFinalSchema(c)))return c.json(err("COMPLIANCE_FINAL_SCHEMA_REQUIRED","Denetim final şeması hazır değil."),503);const audit=await auditOwned(c,s.slug,c.req.param("id"));if(!audit)return c.json(err("NOT_FOUND","Denetim dosyası bulunamadı."),404);const [linked,allDocs,findings,shares]=await Promise.all([
  c.env.DB.prepare("SELECT ad.*,d.title,d.category,d.issuer,d.document_no,d.issue_date,d.valid_from,d.expires_at,d.file_name,d.mime_type,d.file_size,d.status,d.custom_fields FROM compliance_audit_documents ad JOIN compliance_documents d ON d.id=ad.document_id AND d.main_company_slug=ad.main_company_slug WHERE ad.main_company_slug=? AND ad.audit_id=? AND d.archived_at IS NULL ORDER BY ad.sort_order,d.title").bind(s.slug,audit.id).all<Row>(),
  c.env.DB.prepare("SELECT id,title,category,issuer,document_no,issue_date,valid_from,expires_at,file_name,mime_type,file_size,status,custom_fields FROM compliance_documents WHERE main_company_slug=? AND archived_at IS NULL AND file_asset_id IS NOT NULL ORDER BY title").bind(s.slug).all<Row>(),
  c.env.DB.prepare("SELECT f.*,cc.immediate_correction,cc.root_cause,cc.preventive_action,cc.verification_note,cc.verification_status,cc.verified_at FROM compliance_findings f LEFT JOIN compliance_finding_capa cc ON cc.finding_id=f.id AND cc.main_company_slug=f.main_company_slug WHERE f.main_company_slug=? AND f.audit_id=? ORDER BY CASE f.severity WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'MEDIUM' THEN 2 ELSE 3 END,COALESCE(f.due_date,'9999-12-31')").bind(s.slug,audit.id).all<Row>(),
  c.env.DB.prepare("SELECT id,label,expires_at,allow_download,access_count,last_accessed_at,revoked_at,created_at FROM compliance_audit_shares WHERE main_company_slug=? AND audit_id=? ORDER BY created_at DESC").bind(s.slug,audit.id).all<Row>()
 ]);return c.json({ok:true,data:{audit,documents:(linked.results||[]).map((x:Row)=>({...x,custom_fields:json(x.custom_fields,{})})),availableDocuments:(allDocs.results||[]).map((x:Row)=>({...x,custom_fields:json(x.custom_fields,{})})),findings:findings.results||[],shares:shares.results||[]}})});
 app.put("/api/compliance/audits/:id/documents",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);if(!(await requireFinalSchema(c)))return c.json(err("COMPLIANCE_FINAL_SCHEMA_REQUIRED","Denetim final şeması hazır değil."),503);const audit=await auditOwned(c,s.slug,c.req.param("id"));if(!audit)return c.json(err("NOT_FOUND","Denetim dosyası bulunamadı."),404);const ids=[...new Set((Array.isArray(b.documentIds)?b.documentIds:[]).map(text).filter(Boolean))],ts=now();await c.env.DB.prepare("DELETE FROM compliance_audit_documents WHERE main_company_slug=? AND audit_id=?").bind(s.slug,audit.id).run();let n=0;for(const id of ids){const d=await c.env.DB.prepare("SELECT id FROM compliance_documents WHERE id=? AND main_company_slug=? AND archived_at IS NULL AND file_asset_id IS NOT NULL").bind(id,s.slug).first<Row>();if(!d)continue;await c.env.DB.prepare("INSERT INTO compliance_audit_documents(id,main_company_slug,audit_id,document_id,visibility,sort_order,added_by,created_at,updated_at) VALUES(?,?,?,?, 'AUDITOR',?,?,?,?)").bind(crypto.randomUUID(),s.slug,audit.id,id,n+1,text(s.user?.id)||null,ts,ts).run();n++}await event(c,s.slug,"AUDIT_DOCUMENTS_SET","AUDIT",audit.id,text(s.user?.id),{count:n});return c.json({ok:true,data:{count:n}})});
 app.post("/api/compliance/audits/:id/share",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);if(!(await requireFinalSchema(c)))return c.json(err("COMPLIANCE_FINAL_SCHEMA_REQUIRED","Denetim final şeması hazır değil."),503);const audit=await auditOwned(c,s.slug,c.req.param("id"));if(!audit)return c.json(err("NOT_FOUND","Denetim dosyası bulunamadı."),404);const count=await c.env.DB.prepare("SELECT COUNT(*) n FROM compliance_audit_documents WHERE main_company_slug=? AND audit_id=?").bind(s.slug,audit.id).first<Row>();if(Number(count?.n||0)<1)return c.json(err("AUDIT_DOCUMENTS_REQUIRED","Denetçi bağlantısından önce en az bir evrak seçin."),422);const days=Math.max(1,Math.min(90,Number(b.expiresDays||14))),token=randomToken(),tokenHash=await hashToken(token),created=now(),expires=new Date(Date.now()+days*86400000).toISOString(),id=crypto.randomUUID();await c.env.DB.prepare("INSERT INTO compliance_audit_shares(id,main_company_slug,audit_id,label,token_hash,expires_at,allow_download,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").bind(id,s.slug,audit.id,text(b.label)||"Denetçi erişimi",tokenHash,expires,b.allowDownload?1:0,text(s.user?.id)||null,created,created).run();await event(c,s.slug,"AUDIT_SHARE_CREATED","AUDIT",audit.id,text(s.user?.id),{shareId:id,expiresAt:expires});return c.json({ok:true,data:{id,token,expiresAt:expires,url:`https://kyerp.net/audit-room.html?token=${encodeURIComponent(token)}`}})});
 app.patch("/api/compliance/audit-shares/:id/revoke",async c=>{const s=await scope(c,{},true);if(!s.ok)return scopeError(c,s);const ts=now();const r=await c.env.DB.prepare("UPDATE compliance_audit_shares SET revoked_at=?,updated_at=? WHERE id=? AND main_company_slug=? AND revoked_at IS NULL").bind(ts,ts,c.req.param("id"),s.slug).run();return c.json({ok:true,data:{revoked:Number(r.meta?.changes||0)>0}})});
 app.get("/api/compliance/audits/:id/package",async c=>{const s=await scope(c);if(!s.ok)return scopeError(c,s);const audit=await auditOwned(c,s.slug,c.req.param("id"));if(!audit)return c.json(err("NOT_FOUND","Denetim dosyası bulunamadı."),404);const [docs,findings]=await Promise.all([c.env.DB.prepare("SELECT d.id,d.title,d.category,d.issuer,d.document_no,d.issue_date,d.valid_from,d.expires_at,d.file_name,d.mime_type,d.version_no FROM compliance_audit_documents ad JOIN compliance_documents d ON d.id=ad.document_id AND d.main_company_slug=ad.main_company_slug WHERE ad.main_company_slug=? AND ad.audit_id=? ORDER BY ad.sort_order").bind(s.slug,audit.id).all<Row>(),c.env.DB.prepare("SELECT id,title,severity,description,corrective_action,due_date,status FROM compliance_findings WHERE main_company_slug=? AND audit_id=? ORDER BY due_date").bind(s.slug,audit.id).all<Row>()]);return c.json({ok:true,data:{schemaVersion:1,generatedAt:now(),audit,documents:docs.results||[],findings:findings.results||[]}})});
 app.get("/api/compliance/findings/:id/capa",async c=>{const s=await scope(c);if(!s.ok)return scopeError(c,s);if(!(await requireFinalSchema(c)))return c.json(err("COMPLIANCE_FINAL_SCHEMA_REQUIRED","Denetim final şeması hazır değil."),503);const f=await c.env.DB.prepare("SELECT * FROM compliance_findings WHERE id=? AND main_company_slug=?").bind(c.req.param("id"),s.slug).first<Row>();if(!f)return c.json(err("NOT_FOUND","CAPA bulunamadı."),404);const [capa,evidence]=await Promise.all([c.env.DB.prepare("SELECT * FROM compliance_finding_capa WHERE main_company_slug=? AND finding_id=?").bind(s.slug,f.id).first<Row>(),c.env.DB.prepare("SELECT * FROM compliance_finding_evidence WHERE main_company_slug=? AND finding_id=? ORDER BY created_at DESC").bind(s.slug,f.id).all<Row>()]);return c.json({ok:true,data:{finding:f,capa:capa||{verification_status:"OPEN"},evidence:evidence.results||[]}})});
 app.patch("/api/compliance/findings/:id/capa",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);if(!(await requireFinalSchema(c)))return c.json(err("COMPLIANCE_FINAL_SCHEMA_REQUIRED","Denetim final şeması hazır değil."),503);const finding=await c.env.DB.prepare("SELECT * FROM compliance_findings WHERE id=? AND main_company_slug=?").bind(c.req.param("id"),s.slug).first<Row>();if(!finding)return c.json(err("NOT_FOUND","CAPA bulunamadı."),404);const ts=now(),status=upper(b.verificationStatus)||"OPEN",old=await c.env.DB.prepare("SELECT id FROM compliance_finding_capa WHERE main_company_slug=? AND finding_id=?").bind(s.slug,finding.id).first<Row>(),id=text(old?.id)||crypto.randomUUID(),verified=["VERIFIED","EFFECTIVE"].includes(status);if(old)await c.env.DB.prepare("UPDATE compliance_finding_capa SET immediate_correction=?,root_cause=?,corrective_action=?,preventive_action=?,verification_note=?,verification_status=?,verified_by=?,verified_at=?,updated_at=? WHERE id=? AND main_company_slug=?").bind(text(b.immediateCorrection)||null,text(b.rootCause)||null,text(b.correctiveAction)||null,text(b.preventiveAction)||null,text(b.verificationNote)||null,status,verified?text(s.user?.id)||null:null,verified?ts:null,ts,id,s.slug).run();else await c.env.DB.prepare("INSERT INTO compliance_finding_capa(id,main_company_slug,finding_id,immediate_correction,root_cause,corrective_action,preventive_action,verification_note,verification_status,verified_by,verified_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").bind(id,s.slug,finding.id,text(b.immediateCorrection)||null,text(b.rootCause)||null,text(b.correctiveAction)||null,text(b.preventiveAction)||null,text(b.verificationNote)||null,status,verified?text(s.user?.id)||null:null,verified?ts:null,ts,ts).run();if(text(b.correctiveAction))await c.env.DB.prepare("UPDATE compliance_findings SET corrective_action=?,status=?,closed_at=?,updated_at=? WHERE id=? AND main_company_slug=?").bind(text(b.correctiveAction),verified?"VERIFIED":"OPEN",verified?ts:null,ts,finding.id,s.slug).run();await event(c,s.slug,"CAPA_DETAIL_UPDATED","FINDING",finding.id,text(s.user?.id),{verificationStatus:status});return c.json({ok:true})});
 app.post("/api/compliance/findings/:id/evidence",async c=>{const form=await c.req.parseBody({all:true}) as any,s=await scope(c,{mainCompanySlug:text(form.mainCompanySlug)},true);if(!s.ok)return scopeError(c,s);if(!(await requireFinalSchema(c)))return c.json(err("COMPLIANCE_FINAL_SCHEMA_REQUIRED","Denetim final şeması hazır değil."),503);const finding=await c.env.DB.prepare("SELECT id FROM compliance_findings WHERE id=? AND main_company_slug=?").bind(c.req.param("id"),s.slug).first<Row>();if(!finding)return c.json(err("NOT_FOUND","CAPA bulunamadı."),404);const candidate=Array.isArray(form.file)?form.file[0]:form.file,file=candidate instanceof File?candidate:null;if(!file)return c.json(err("FILE_REQUIRED","Kanıt dosyası zorunludur."),400);let a;try{a=await fileAsset(c,s.slug,file,"CAPA_EVIDENCE",finding.id)}catch(e:any){return c.json(err(e.code||"UPLOAD_FAILED",e.message||"Dosya yüklenemedi."),422)}const id=crypto.randomUUID(),ts=now();await c.env.DB.prepare("INSERT INTO compliance_finding_evidence(id,main_company_slug,finding_id,file_asset_id,file_name,storage_key,mime_type,file_size,note,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").bind(id,s.slug,finding.id,a.id,a.fileName,a.key,a.mimeType,a.size,text(form.note)||null,text(s.user?.id)||null,ts).run();await event(c,s.slug,"CAPA_EVIDENCE_ADDED","FINDING",finding.id,text(s.user?.id),{fileName:a.fileName});return c.json({ok:true,data:{id,...a}})});
 app.get("/api/compliance/findings/:id/evidence/:evidenceId/file",async c=>{const s=await scope(c);if(!s.ok)return scopeError(c,s);const row=await c.env.DB.prepare("SELECT * FROM compliance_finding_evidence WHERE id=? AND finding_id=? AND main_company_slug=?").bind(c.req.param("evidenceId"),c.req.param("id"),s.slug).first<Row>();if(!row)return c.json(err("FILE_NOT_FOUND","Kanıt dosyası bulunamadı."),404);const obj=await c.env.FILES.get(row.storage_key);if(!obj)return c.json(err("FILE_NOT_FOUND","Kanıt dosyası depolamada bulunamadı."),404);const h=new Headers();obj.writeHttpMetadata(h);h.set("Content-Type",text(row.mime_type)||"application/octet-stream");h.set("Content-Disposition",`inline; filename*=UTF-8''${encodeURIComponent(text(row.file_name)||"kanit")}`);return new Response(obj.body,{headers:h})});

 app.get("/api/compliance-public/audit/:token",async c=>{if(!(await requireFinalSchema(c)))return c.json(err("NOT_READY","Denetçi odası hazır değil."),503);const share=await shareByToken(c,c.req.param("token"));if(!share)return c.json(err("LINK_INVALID","Denetçi bağlantısı geçersiz, süresi dolmuş veya iptal edilmiş."),404);const [docs,findings]=await Promise.all([c.env.DB.prepare("SELECT d.id,d.title,d.category,d.issuer,d.document_no,d.issue_date,d.valid_from,d.expires_at,d.file_name,d.mime_type,d.file_size,d.version_no,d.custom_fields FROM compliance_audit_documents ad JOIN compliance_documents d ON d.id=ad.document_id AND d.main_company_slug=ad.main_company_slug WHERE ad.main_company_slug=? AND ad.audit_id=? AND ad.visibility='AUDITOR' AND d.archived_at IS NULL ORDER BY ad.sort_order,d.title").bind(share.main_company_slug,share.audit_id).all<Row>(),c.env.DB.prepare("SELECT title,severity,due_date,status FROM compliance_findings WHERE main_company_slug=? AND audit_id=? ORDER BY CASE severity WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 ELSE 2 END,due_date").bind(share.main_company_slug,share.audit_id).all<Row>()]);const ts=now();await c.env.DB.prepare("UPDATE compliance_audit_shares SET access_count=access_count+1,last_accessed_at=?,updated_at=? WHERE id=?").bind(ts,ts,share.id).run();c.header("Cache-Control","no-store");return c.json({ok:true,data:{audit:{name:share.audit_name,type:share.audit_type,plannedDate:share.planned_date,completedDate:share.completed_date,auditorName:share.auditor_name,status:share.audit_status,profileName:share.profile_name,profileCode:share.profile_code,notes:share.notes},share:{label:share.label,expiresAt:share.expires_at,allowDownload:Boolean(share.allow_download)},documents:(docs.results||[]).map((x:Row)=>({...x,custom_fields:json(x.custom_fields,{})})),findings:findings.results||[]}})});
 app.get("/api/compliance-public/audit/:token/files/:documentId",async c=>{if(!(await requireFinalSchema(c)))return c.json(err("NOT_READY","Denetçi odası hazır değil."),503);const share=await shareByToken(c,c.req.param("token"));if(!share)return c.json(err("LINK_INVALID","Denetçi bağlantısı geçersiz, süresi dolmuş veya iptal edilmiş."),404);const row=await c.env.DB.prepare("SELECT d.file_name,d.storage_key,d.mime_type FROM compliance_audit_documents ad JOIN compliance_documents d ON d.id=ad.document_id AND d.main_company_slug=ad.main_company_slug WHERE ad.main_company_slug=? AND ad.audit_id=? AND ad.document_id=? AND ad.visibility='AUDITOR' AND d.archived_at IS NULL LIMIT 1").bind(share.main_company_slug,share.audit_id,c.req.param("documentId")).first<Row>();if(!row?.storage_key)return c.json(err("FILE_NOT_FOUND","Dosya bulunamadı."),404);const obj=await c.env.FILES.get(row.storage_key);if(!obj)return c.json(err("FILE_NOT_FOUND","Dosya depolamada bulunamadı."),404);const h=new Headers();obj.writeHttpMetadata(h);h.set("Content-Type",text(row.mime_type)||"application/octet-stream");h.set("Content-Disposition",`${share.allow_download?"attachment":"inline"}; filename*=UTF-8''${encodeURIComponent(text(row.file_name)||"evrak")}`);h.set("Cache-Control","private, no-store");return new Response(obj.body,{headers:h})});
}
