// @ts-nocheck
import type { Context, Hono } from "hono";
import { getAuthenticatedUser } from "./auth-cloud";

type AppEnv={Bindings:Cloudflare.Env;Variables:{requestId:string}};
type Row=Record<string,any>;
const text=(v:unknown)=>v==null?"":String(v).trim();
const upper=(v:unknown)=>text(v).toLocaleUpperCase("tr-TR").replace(/İ/g,"I");
const lower=(v:unknown)=>text(v).toLocaleLowerCase("tr-TR");
const now=()=>new Date().toISOString();
const dateOnly=(v:unknown)=>text(v).slice(0,10);
const bool=(v:unknown,f=false)=>v==null||v===""?f:(typeof v==="boolean"?v:Number(v)!==0&&!['FALSE','HAYIR','NO','OFF'].includes(upper(v)));
const json=(v:unknown,f:any={})=>{if(v&&typeof v==="object")return v;try{return JSON.parse(text(v)||JSON.stringify(f))}catch{return f}};
const err=(code:string,message:string,details?:unknown)=>({ok:false,success:false,error:{code,message,...(details===undefined?{}:{details})}});
async function bodyOf(c:Context<AppEnv>):Promise<Row>{try{const b=await c.req.json();return b&&typeof b==="object"&&!Array.isArray(b)?b as Row:{}}catch{return{}}}
function isOwner(u:Row){return ["SUPER_ADMIN","ADMIN"].includes(upper(u?.role))}
function isCompanyAdmin(u:Row){return upper(u?.role)==="COMPANY_ADMIN"}
function permission(u:Row){return (Array.isArray(u?.permissions)?u.permissions:[]).find((p:Row)=>upper(p.moduleKey||p.module_key)==="COMPLIANCE")||null}
function canView(u:Row){return isOwner(u)||isCompanyAdmin(u)||Boolean(permission(u)?.canView??permission(u)?.can_view)}
function canWrite(u:Row){const p=permission(u);return isOwner(u)||isCompanyAdmin(u)||Boolean(p?.canCreate??p?.can_create??p?.canUpdate??p?.can_update)}
function ownSlug(u:Row){return lower(u?.mainCompanySlug||u?.main_company_slug||u?.security?.main_company_slug)}
function requestedSlug(c:Context<AppEnv>,b:Row={}){return lower(b.mainCompanySlug||b.main_company_slug||c.req.query("mainCompanySlug")||c.req.header("X-KYERP-Tenant-Slug"))}
async function scope(c:Context<AppEnv>,body:Row={},write=false){
  const u=await getAuthenticatedUser(c) as Row|null;
  if(!u||!canView(u)||(write&&!canWrite(u)))return{ok:false,status:u?403:401,user:u,slug:""};
  const requested=requestedSlug(c,body),own=ownSlug(u);
  if(!isOwner(u)){if(!own||(requested&&requested!==own))return{ok:false,status:403,user:u,slug:""};return{ok:true,status:200,user:u,slug:own};}
  const slug=requested||own;if(!slug)return{ok:false,status:400,user:u,slug:""};return{ok:true,status:200,user:u,slug};
}
function scopeError(c:Context<AppEnv>,s:Row){return c.json(err(s.status===401?"UNAUTHORIZED":"COMPLIANCE_FORBIDDEN",s.status===401?"Oturum gerekli.":"Denetim Merkezi için yetkiniz yok."),s.status as any)}
async function event(c:Context<AppEnv>,slug:string,type:string,entityType:string,entityId:string,userId:string,detail:Row={}){
  await c.env.DB.prepare(`INSERT INTO compliance_events(id,main_company_slug,event_type,entity_type,entity_id,actor_user_id,detail,created_at) VALUES(?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),slug,type,entityType||null,entityId||null,userId||null,JSON.stringify(detail),now()).run();
}
function safeCode(v:unknown){return upper(v).replace(/[^A-Z0-9_-]+/g,"_").replace(/^_+|_+$/g,"").slice(0,80)}
function safeName(v:unknown){return text(v).replace(/[^A-Za-z0-9._ÇĞİÖŞÜçğıöşü -]+/g,"_").slice(0,160)||"evrak"}
function tokens(v:unknown){return lower(v).normalize("NFD").replace(/[\u0300-\u036f]/g,"").split(/[^a-z0-9çğıöşü]+/).filter(x=>x.length>=4&&!['belgesi','kayitlari','raporu','formu','evraki','dokuman'].includes(x));}
async function nextSort(c:Context<AppEnv>,slug:string,profileId:string){const r=await c.env.DB.prepare(`SELECT COALESCE(MAX(sort_order),0)+1 n FROM compliance_requirements WHERE main_company_slug=? AND profile_id=?`).bind(slug,profileId).first<Row>();return Number(r?.n||1)}
async function profileOwned(c:Context<AppEnv>,slug:string,id:string){return c.env.DB.prepare(`SELECT * FROM compliance_profiles WHERE id=? AND main_company_slug=? LIMIT 1`).bind(id,slug).first<Row>()}
async function requirementOwned(c:Context<AppEnv>,slug:string,id:string){return c.env.DB.prepare(`SELECT * FROM compliance_requirements WHERE id=? AND main_company_slug=? LIMIT 1`).bind(id,slug).first<Row>()}
async function autoLink(c:Context<AppEnv>,slug:string,documentId:string,title:string,category:string){
  const docTokens=new Set(tokens(`${title} ${category}`));if(!docTokens.size)return[];
  const rows=await c.env.DB.prepare(`SELECT id,title,category,code FROM compliance_requirements WHERE main_company_slug=? AND COALESCE(is_active,1)=1`).bind(slug).all<Row>();
  const scored=(rows.results||[]).map(r=>{const rt=tokens(`${r.title} ${r.category}`),hits=rt.filter((x:string)=>docTokens.has(x)).length;return{row:r,hits,score:rt.length?hits/Math.max(2,Math.min(rt.length,6)):0}}).filter(x=>x.hits>=2||x.score>=.45).sort((a,b)=>b.score-a.score).slice(0,5);
  const ts=now();for(const x of scored){await c.env.DB.prepare(`INSERT OR IGNORE INTO compliance_document_requirements(id,main_company_slug,document_id,requirement_id,is_primary,confidence,source,created_at,updated_at) VALUES(?,?,?,?,0,?,'AUTO_MATCH',?,?)`).bind(crypto.randomUUID(),slug,documentId,x.row.id,Math.min(.95,.55+x.score/2),ts,ts).run();}
  return scored.map(x=>({requirementId:x.row.id,code:x.row.code,title:x.row.title,confidence:Math.min(.95,.55+x.score/2)}));
}
async function linkRequirements(c:Context<AppEnv>,slug:string,documentId:string,ids:unknown,source="MANUAL"){
  const list=[...new Set((Array.isArray(ids)?ids:[ids]).map(text).filter(Boolean))],ts=now();
  for(const id of list){const r=await requirementOwned(c,slug,id);if(!r)continue;await c.env.DB.prepare(`INSERT OR IGNORE INTO compliance_document_requirements(id,main_company_slug,document_id,requirement_id,is_primary,confidence,source,created_at,updated_at) VALUES(?,?,?,?,0,1,?,?,?)`).bind(crypto.randomUUID(),slug,documentId,id,source,ts,ts).run();}
  return list.length;
}
async function stageVersion(c:Context<AppEnv>,slug:string,documentId:string,file:File,userId:string){
  const doc=await c.env.DB.prepare(`SELECT * FROM compliance_documents WHERE id=? AND main_company_slug=? AND archived_at IS NULL`).bind(documentId,slug).first<Row>();if(!doc)throw Object.assign(new Error("Evrak bulunamadı."),{code:"NOT_FOUND"});
  const assetId=crypto.randomUUID(),ts=now(),version=Number(doc.version_no||0)+1,name=safeName(file.name),key=`compliance/${slug}/${documentId}/v${version}/${assetId}-${name}`;
  await c.env.FILES.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:file.type||"application/octet-stream"},customMetadata:{purpose:"COMPLIANCE_DOCUMENT",documentId,version:String(version),originalName:file.name,mainCompanySlug:slug}});
  const ext=(file.name.split(".").pop()||"").toUpperCase();await c.env.DB.prepare(`INSERT INTO file_hub_assets(id,main_company_slug,logical_key,file_name,extension,mime_type,size_bytes,status,source_type,preview_status,preview_storage_key,metadata,first_seen_at,last_seen_at,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'AVAILABLE','COMPLIANCE_UPLOAD','READY',?,?,?, ?,?,?)`).bind(assetId,slug,`compliance:${documentId}:v${version}`,file.name,ext,file.type||null,file.size,key,JSON.stringify({storageKey:key,documentId,version}),ts,ts,ts,ts).run();
  await c.env.DB.prepare(`INSERT OR IGNORE INTO file_hub_relations(id,main_company_slug,file_asset_id,entity_type,entity_id,relation_type,is_primary,confidence,source,metadata,created_at,updated_at) VALUES(?,?,?,?,?,'COMPLIANCE_DOCUMENT',1,1,'COMPLIANCE_CENTER','{}',?,?)`).bind(crypto.randomUUID(),slug,assetId,"COMPLIANCE_DOCUMENT",documentId,ts,ts).run();
  const snapshot={title:doc.title,category:doc.category,documentNo:doc.document_no,issueDate:doc.issue_date,expiresAt:doc.expires_at,tags:json(doc.tags,[]),customFields:json(doc.custom_fields,{})};
  await c.env.DB.prepare(`INSERT INTO compliance_document_versions(id,main_company_slug,document_id,version_no,file_asset_id,file_name,storage_key,mime_type,file_size,metadata_snapshot,created_by,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),slug,documentId,version,assetId,file.name,key,file.type||null,file.size,JSON.stringify(snapshot),userId||null,ts).run();
  await c.env.DB.prepare(`UPDATE compliance_documents SET file_asset_id=?,file_name=?,storage_key=?,mime_type=?,file_size=?,version_no=?,ai_status='PENDING',updated_at=? WHERE id=? AND main_company_slug=?`).bind(assetId,file.name,key,file.type||null,file.size,version,ts,documentId,slug).run();
  return{assetId,key,fileName:file.name,mimeType:file.type||"application/octet-stream",size:file.size,versionNo:version};
}
function normalizeProfile(row:Row){return{...row,metadata:json(row.metadata,{})}}
function normalizeRequirement(row:Row){return{...row,evidence_types:json(row.evidence_types,[]),custom_fields:json(row.custom_fields,{}),metadata:json(row.metadata,{})}}
function normalizeDocument(row:Row){return{...row,tags:json(row.tags,[]),custom_fields:json(row.custom_fields,{}),ai_extracted_data:json(row.ai_extracted_data,{})}}

export function registerComplianceConfigRoutes(app:Hono<AppEnv>){
  app.post("/api/compliance/profiles",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);const name=text(b.name),code=safeCode(b.code||name);if(!name||!code)return c.json(err("PROFILE_REQUIRED","Profil adı ve kodu zorunludur."),422);const id=crypto.randomUUID(),ts=now();try{await c.env.DB.prepare(`INSERT INTO compliance_profiles(id,main_company_slug,code,name,version,description,source_url,is_active,metadata,created_at,updated_at) VALUES(?,?,?,?,?,?,?,1,?,?,?)`).bind(id,s.slug,code,name,text(b.version)||"CUSTOM",text(b.description)||null,text(b.sourceUrl)||null,JSON.stringify({...json(b.metadata,{}),custom:true,createdInUi:true}),ts,ts).run();}catch{return c.json(err("PROFILE_CODE_EXISTS","Bu profil kodu zaten kullanılıyor."),409)}await event(c,s.slug,"PROFILE_CREATED","PROFILE",id,text(s.user?.id),{code,name});return c.json({ok:true,data:{id,code}},201)});
  app.patch("/api/compliance/profiles/:id",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);const old=await profileOwned(c,s.slug,c.req.param("id"));if(!old)return c.json(err("NOT_FOUND","Denetim profili bulunamadı."),404);const ts=now();await c.env.DB.prepare(`UPDATE compliance_profiles SET name=?,version=?,description=?,source_url=?,is_active=?,metadata=?,updated_at=? WHERE id=? AND main_company_slug=?`).bind(text(b.name??old.name),text(b.version??old.version)||null,text(b.description??old.description)||null,text(b.sourceUrl??old.source_url)||null,b.isActive===undefined?old.is_active:(bool(b.isActive)?1:0),JSON.stringify(b.metadata===undefined?json(old.metadata,{}):json(b.metadata,{})),ts,old.id,s.slug).run();await event(c,s.slug,"PROFILE_UPDATED","PROFILE",old.id,text(s.user?.id));return c.json({ok:true})});
  app.post("/api/compliance/profiles/:id/clone",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);const source=await profileOwned(c,s.slug,c.req.param("id"));if(!source)return c.json(err("NOT_FOUND","Kaynak profil bulunamadı."),404);const name=text(b.name)||`${source.name} Kopya`,code=safeCode(b.code||`${source.code}_COPY`),id=crypto.randomUUID(),ts=now();try{await c.env.DB.prepare(`INSERT INTO compliance_profiles(id,main_company_slug,code,name,version,description,source_url,is_active,metadata,created_at,updated_at) VALUES(?,?,?,?,?,?,?,1,?,?,?)`).bind(id,s.slug,code,name,text(b.version)||text(source.version),text(b.description)||text(source.description),text(source.source_url)||null,JSON.stringify({...json(source.metadata,{}),custom:true,clonedFrom:source.id}),ts,ts).run();}catch{return c.json(err("PROFILE_CODE_EXISTS","Bu profil kodu zaten kullanılıyor."),409)}const reqs=await c.env.DB.prepare(`SELECT * FROM compliance_requirements WHERE main_company_slug=? AND profile_id=? ORDER BY sort_order`).bind(s.slug,source.id).all<Row>();for(const r of reqs.results||[]){await c.env.DB.prepare(`INSERT INTO compliance_requirements(id,main_company_slug,profile_id,code,title,category,requirement_type,description,evidence_types,source_url,legal_basis,recurrence_rule,applicability_rule,is_active,custom_fields,mandatory,cycle_days,warning_days,critical_days,owner_department,sort_order,metadata,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),s.slug,id,r.code,r.title,r.category,r.requirement_type,r.description,r.evidence_types,r.source_url,r.legal_basis,r.recurrence_rule,r.applicability_rule,r.is_active,r.custom_fields,r.mandatory,r.cycle_days,r.warning_days,r.critical_days,r.owner_department,r.sort_order,r.metadata,ts,ts).run();}await event(c,s.slug,"PROFILE_CLONED","PROFILE",id,text(s.user?.id),{from:source.id});return c.json({ok:true,data:{id,code,requirements:(reqs.results||[]).length}},201)});
  app.get("/api/compliance/profiles/:id/export",async c=>{const s=await scope(c);if(!s.ok)return scopeError(c,s);const profile=await profileOwned(c,s.slug,c.req.param("id"));if(!profile)return c.json(err("NOT_FOUND","Profil bulunamadı."),404);const [reqs,fields]=await Promise.all([c.env.DB.prepare(`SELECT * FROM compliance_requirements WHERE main_company_slug=? AND profile_id=? ORDER BY sort_order`).bind(s.slug,profile.id).all<Row>(),c.env.DB.prepare(`SELECT * FROM compliance_field_definitions WHERE main_company_slug=? AND profile_id=? AND is_active=1 ORDER BY sort_order`).bind(s.slug,profile.id).all<Row>()]);return c.json({ok:true,data:{schemaVersion:1,profile:normalizeProfile(profile),requirements:(reqs.results||[]).map(normalizeRequirement),fields:(fields.results||[]).map((x:Row)=>({...x,options_json:json(x.options_json,[]),metadata:json(x.metadata,{})}))}})});
  app.post("/api/compliance/profiles/import",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);const payload=json(b.payload||b.data||b,{}),p=json(payload.profile,{}),requirements=Array.isArray(payload.requirements)?payload.requirements:[];const name=text(b.name||p.name),code=safeCode(b.code||p.code||name);if(!name||!code)return c.json(err("IMPORT_INVALID","İçe aktarma paketinde profil adı/kodu bulunamadı."),422);const id=crypto.randomUUID(),ts=now();try{await c.env.DB.prepare(`INSERT INTO compliance_profiles(id,main_company_slug,code,name,version,description,source_url,is_active,metadata,created_at,updated_at) VALUES(?,?,?,?,?,?,?,1,?,?,?)`).bind(id,s.slug,code,name,text(p.version)||"IMPORTED",text(p.description)||null,text(p.source_url||p.sourceUrl)||null,JSON.stringify({...json(p.metadata,{}),custom:true,imported:true}),ts,ts).run();}catch{return c.json(err("PROFILE_CODE_EXISTS","İçe aktarılacak profil kodu zaten mevcut."),409)}for(let i=0;i<requirements.length;i++){const r=requirements[i]||{},rCode=safeCode(r.code||`REQ_${i+1}`);if(!text(r.title)||!rCode)continue;await c.env.DB.prepare(`INSERT INTO compliance_requirements(id,main_company_slug,profile_id,code,title,category,requirement_type,description,evidence_types,source_url,legal_basis,recurrence_rule,applicability_rule,is_active,custom_fields,mandatory,cycle_days,warning_days,critical_days,owner_department,sort_order,metadata,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(crypto.randomUUID(),s.slug,id,rCode,text(r.title),text(r.category)||"Genel",upper(r.requirement_type||r.requirementType)||"DOCUMENT",text(r.description)||null,JSON.stringify(json(r.evidence_types||r.evidenceTypes,["DOCUMENT"])),text(r.source_url||r.sourceUrl)||null,text(r.legal_basis||r.legalBasis)||null,text(r.recurrence_rule||r.recurrenceRule)||null,text(r.applicability_rule||r.applicabilityRule)||null,r.is_active===0?0:1,JSON.stringify(json(r.custom_fields||r.customFields,{})),r.mandatory===0?0:1,r.cycle_days==null?null:Number(r.cycle_days),Number(r.warning_days??10),Number(r.critical_days??3),text(r.owner_department||r.ownerDepartment)||null,Number(r.sort_order||i+1),JSON.stringify(json(r.metadata,{})),ts,ts).run();}await event(c,s.slug,"PROFILE_IMPORTED","PROFILE",id,text(s.user?.id),{requirementCount:requirements.length});return c.json({ok:true,data:{id,code,requirements:requirements.length}},201)});
  app.post("/api/compliance/profiles/:id/requirements",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);const profile=await profileOwned(c,s.slug,c.req.param("id"));if(!profile)return c.json(err("NOT_FOUND","Denetim profili bulunamadı."),404);const title=text(b.title),code=safeCode(b.code||title);if(!title||!code)return c.json(err("REQUIREMENT_REQUIRED","Gereklilik adı ve kodu zorunludur."),422);const id=crypto.randomUUID(),ts=now(),sort=Number(b.sortOrder||await nextSort(c,s.slug,profile.id));try{await c.env.DB.prepare(`INSERT INTO compliance_requirements(id,main_company_slug,profile_id,code,title,category,requirement_type,description,evidence_types,source_url,legal_basis,recurrence_rule,applicability_rule,is_active,custom_fields,mandatory,cycle_days,warning_days,critical_days,owner_department,sort_order,metadata,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(id,s.slug,profile.id,code,title,text(b.category)||"Genel",upper(b.requirementType)||"DOCUMENT",text(b.description)||null,JSON.stringify(json(b.evidenceTypes,["DOCUMENT"])),text(b.sourceUrl)||null,text(b.legalBasis)||null,text(b.recurrenceRule)||null,text(b.applicabilityRule)||null,b.isActive===false?0:1,JSON.stringify(json(b.customFields,{})),b.mandatory===false?0:1,b.cycleDays==null?null:Number(b.cycleDays),Number(b.warningDays??10),Number(b.criticalDays??3),text(b.ownerDepartment)||null,sort,JSON.stringify(json(b.metadata,{})),ts,ts).run();}catch{return c.json(err("REQUIREMENT_CODE_EXISTS","Bu gereklilik kodu bu profilde zaten var."),409)}await event(c,s.slug,"REQUIREMENT_CREATED","REQUIREMENT",id,text(s.user?.id),{profileId:profile.id,code,title});return c.json({ok:true,data:{id,code}},201)});
  app.patch("/api/compliance/requirements/:id",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);const old=await requirementOwned(c,s.slug,c.req.param("id"));if(!old)return c.json(err("NOT_FOUND","Gereklilik bulunamadı."),404);const ts=now();await c.env.DB.prepare(`UPDATE compliance_requirements SET title=?,category=?,requirement_type=?,description=?,evidence_types=?,source_url=?,legal_basis=?,recurrence_rule=?,applicability_rule=?,is_active=?,custom_fields=?,mandatory=?,cycle_days=?,warning_days=?,critical_days=?,owner_department=?,sort_order=?,metadata=?,updated_at=? WHERE id=? AND main_company_slug=?`).bind(text(b.title??old.title),text(b.category??old.category),upper(b.requirementType??old.requirement_type)||"DOCUMENT",text(b.description??old.description)||null,JSON.stringify(b.evidenceTypes===undefined?json(old.evidence_types,[]):json(b.evidenceTypes,[])),text(b.sourceUrl??old.source_url)||null,text(b.legalBasis??old.legal_basis)||null,text(b.recurrenceRule??old.recurrence_rule)||null,text(b.applicabilityRule??old.applicability_rule)||null,b.isActive===undefined?old.is_active:(bool(b.isActive)?1:0),JSON.stringify(b.customFields===undefined?json(old.custom_fields,{}):json(b.customFields,{})),b.mandatory===undefined?old.mandatory:(bool(b.mandatory)?1:0),b.cycleDays===undefined?old.cycle_days:(b.cycleDays==null?null:Number(b.cycleDays)),Number(b.warningDays??old.warning_days??10),Number(b.criticalDays??old.critical_days??3),text(b.ownerDepartment??old.owner_department)||null,Number(b.sortOrder??old.sort_order??0),JSON.stringify(b.metadata===undefined?json(old.metadata,{}):json(b.metadata,{})),ts,old.id,s.slug).run();await event(c,s.slug,"REQUIREMENT_UPDATED","REQUIREMENT",old.id,text(s.user?.id));return c.json({ok:true})});
  app.delete("/api/compliance/requirements/:id",async c=>{const s=await scope(c,{},true);if(!s.ok)return scopeError(c,s);const old=await requirementOwned(c,s.slug,c.req.param("id"));if(!old)return c.json(err("NOT_FOUND","Gereklilik bulunamadı."),404);await c.env.DB.prepare(`UPDATE compliance_requirements SET is_active=0,updated_at=? WHERE id=? AND main_company_slug=?`).bind(now(),old.id,s.slug).run();await event(c,s.slug,"REQUIREMENT_ARCHIVED","REQUIREMENT",old.id,text(s.user?.id));return c.json({ok:true})});
  app.get("/api/compliance/documents/:id/detail",async c=>{const s=await scope(c);if(!s.ok)return scopeError(c,s);const id=c.req.param("id"),doc=await c.env.DB.prepare(`SELECT * FROM compliance_documents WHERE id=? AND main_company_slug=? AND archived_at IS NULL`).bind(id,s.slug).first<Row>();if(!doc)return c.json(err("NOT_FOUND","Evrak bulunamadı."),404);const [links,versions,events]=await Promise.all([c.env.DB.prepare(`SELECT l.*,r.code requirement_code,r.title requirement_title,r.category requirement_category,p.code profile_code,p.name profile_name FROM compliance_document_requirements l JOIN compliance_requirements r ON r.id=l.requirement_id LEFT JOIN compliance_profiles p ON p.id=r.profile_id WHERE l.main_company_slug=? AND l.document_id=? ORDER BY p.code,r.sort_order`).bind(s.slug,id).all<Row>(),c.env.DB.prepare(`SELECT * FROM compliance_document_versions WHERE main_company_slug=? AND document_id=? ORDER BY version_no DESC`).bind(s.slug,id).all<Row>(),c.env.DB.prepare(`SELECT * FROM compliance_events WHERE main_company_slug=? AND entity_type='DOCUMENT' AND entity_id=? ORDER BY created_at DESC LIMIT 50`).bind(s.slug,id).all<Row>()]);return c.json({ok:true,data:{document:normalizeDocument(doc),links:links.results||[],versions:(versions.results||[]).map((x:Row)=>({...x,metadata_snapshot:json(x.metadata_snapshot,{})})),events:(events.results||[]).map((x:Row)=>({...x,detail:json(x.detail,{})}))}})});
  app.post("/api/compliance/documents/:id/requirements",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);const id=c.req.param("id"),doc=await c.env.DB.prepare(`SELECT id,title,category FROM compliance_documents WHERE id=? AND main_company_slug=? AND archived_at IS NULL`).bind(id,s.slug).first<Row>();if(!doc)return c.json(err("NOT_FOUND","Evrak bulunamadı."),404);const count=await linkRequirements(c,s.slug,id,b.requirementIds||b.requirementId,"MANUAL");await event(c,s.slug,"DOCUMENT_LINKED","DOCUMENT",id,text(s.user?.id),{count});return c.json({ok:true,data:{linked:count}})});
  app.delete("/api/compliance/documents/:id/requirements/:requirementId",async c=>{const s=await scope(c,{},true);if(!s.ok)return scopeError(c,s);await c.env.DB.prepare(`DELETE FROM compliance_document_requirements WHERE main_company_slug=? AND document_id=? AND requirement_id=?`).bind(s.slug,c.req.param("id"),c.req.param("requirementId")).run();await event(c,s.slug,"DOCUMENT_UNLINKED","DOCUMENT",c.req.param("id"),text(s.user?.id),{requirementId:c.req.param("requirementId")});return c.json({ok:true})});
  app.post("/api/compliance/documents/:id/auto-link",async c=>{const s=await scope(c,{},true);if(!s.ok)return scopeError(c,s);const id=c.req.param("id"),doc=await c.env.DB.prepare(`SELECT id,title,category FROM compliance_documents WHERE id=? AND main_company_slug=? AND archived_at IS NULL`).bind(id,s.slug).first<Row>();if(!doc)return c.json(err("NOT_FOUND","Evrak bulunamadı."),404);const matches=await autoLink(c,s.slug,id,text(doc.title),text(doc.category));await event(c,s.slug,"DOCUMENT_AUTO_LINK","DOCUMENT",id,text(s.user?.id),{matches});return c.json({ok:true,data:{matches}})});
  app.post("/api/compliance/documents/:id/new-version",async c=>{const form=await c.req.parseBody({all:true}) as any,s=await scope(c,{mainCompanySlug:text(form.mainCompanySlug)},true);if(!s.ok)return scopeError(c,s);const candidate=Array.isArray(form.file)?form.file[0]:form.file,file=candidate instanceof File?candidate:null;if(!file)return c.json(err("FILE_REQUIRED","Yüklenecek dosya zorunludur."),400);if(file.size>40*1024*1024)return c.json(err("FILE_TOO_LARGE","Dosya en fazla 40 MB olabilir."),413);let uploaded;try{uploaded=await stageVersion(c,s.slug,c.req.param("id"),file,text(s.user?.id))}catch(e:any){return c.json(err(e?.code||"UPLOAD_FAILED",e?.message||"Dosya yüklenemedi."),e?.code==="NOT_FOUND"?404:500)}await event(c,s.slug,"DOCUMENT_NEW_VERSION","DOCUMENT",c.req.param("id"),text(s.user?.id),uploaded);return c.json({ok:true,data:uploaded})});
  app.patch("/api/compliance/documents/:id/tracking",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);const id=c.req.param("id"),old=await c.env.DB.prepare(`SELECT * FROM compliance_documents WHERE id=? AND main_company_slug=? AND archived_at IS NULL`).bind(id,s.slug).first<Row>();if(!old)return c.json(err("NOT_FOUND","Evrak bulunamadı."),404);const ts=now();await c.env.DB.prepare(`UPDATE compliance_documents SET tags=?,custom_fields=?,reminder_days=?,responsible_user_id=?,owner_department=?,updated_at=? WHERE id=? AND main_company_slug=?`).bind(JSON.stringify(b.tags===undefined?json(old.tags,[]):json(b.tags,[])),JSON.stringify(b.customFields===undefined?json(old.custom_fields,{}):json(b.customFields,{})),Number(b.reminderDays??old.reminder_days??10),text(b.responsibleUserId??old.responsible_user_id)||null,text(b.ownerDepartment??old.owner_department)||null,ts,id,s.slug).run();if(Array.isArray(b.requirementIds))await linkRequirements(c,s.slug,id,b.requirementIds,"MANUAL");await event(c,s.slug,"DOCUMENT_TRACKING_UPDATED","DOCUMENT",id,text(s.user?.id));return c.json({ok:true})});
  app.get("/api/compliance/fields",async c=>{const s=await scope(c);if(!s.ok)return scopeError(c,s);const profileId=text(c.req.query("profileId")),where=["main_company_slug=?","is_active=1"],args:any[]=[s.slug];if(profileId){where.push("profile_id=?");args.push(profileId)}const r=await c.env.DB.prepare(`SELECT * FROM compliance_field_definitions WHERE ${where.join(" AND ")} ORDER BY entity_type,sort_order,label`).bind(...args).all<Row>();return c.json({ok:true,data:(r.results||[]).map((x:Row)=>({...x,options_json:json(x.options_json,[]),metadata:json(x.metadata,{})}))})});
  app.post("/api/compliance/fields",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);const key=safeCode(b.fieldKey||b.label).toLocaleLowerCase("tr-TR"),label=text(b.label);if(!key||!label)return c.json(err("FIELD_REQUIRED","Alan adı ve anahtarı zorunludur."),422);const id=crypto.randomUUID(),ts=now();try{await c.env.DB.prepare(`INSERT INTO compliance_field_definitions(id,main_company_slug,profile_id,entity_type,field_key,label,field_type,options_json,required,sort_order,is_active,metadata,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,1,?,?,?)`).bind(id,s.slug,text(b.profileId)||null,upper(b.entityType)||"DOCUMENT",key,label,upper(b.fieldType)||"TEXT",JSON.stringify(json(b.options,[])),bool(b.required)?1:0,Number(b.sortOrder||0),JSON.stringify(json(b.metadata,{})),ts,ts).run();}catch{return c.json(err("FIELD_EXISTS","Bu özel alan zaten tanımlı."),409)}return c.json({ok:true,data:{id,fieldKey:key}},201)});
  app.patch("/api/compliance/fields/:id",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);const old=await c.env.DB.prepare(`SELECT * FROM compliance_field_definitions WHERE id=? AND main_company_slug=?`).bind(c.req.param("id"),s.slug).first<Row>();if(!old)return c.json(err("NOT_FOUND","Özel alan bulunamadı."),404);await c.env.DB.prepare(`UPDATE compliance_field_definitions SET label=?,field_type=?,options_json=?,required=?,sort_order=?,is_active=?,metadata=?,updated_at=? WHERE id=? AND main_company_slug=?`).bind(text(b.label??old.label),upper(b.fieldType??old.field_type)||"TEXT",JSON.stringify(b.options===undefined?json(old.options_json,[]):json(b.options,[])),b.required===undefined?old.required:(bool(b.required)?1:0),Number(b.sortOrder??old.sort_order??0),b.isActive===undefined?old.is_active:(bool(b.isActive)?1:0),JSON.stringify(b.metadata===undefined?json(old.metadata,{}):json(b.metadata,{})),now(),old.id,s.slug).run();return c.json({ok:true})});
  app.get("/api/compliance/settings",async c=>{const s=await scope(c);if(!s.ok)return scopeError(c,s);const r=await c.env.DB.prepare(`SELECT setting_key,setting_value FROM compliance_settings WHERE main_company_slug=?`).bind(s.slug).all<Row>();const data:Row={defaultWarningDays:10,secondaryWarningDays:30,criticalWarningDays:3,aiAutoReview:true};for(const x of r.results||[])data[x.setting_key]=json(x.setting_value,x.setting_value);return c.json({ok:true,data})});
  app.put("/api/compliance/settings",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);const ts=now(),entries=Object.entries(b).filter(([k])=>k!=="mainCompanySlug"&&k!=="main_company_slug");for(const [key,value] of entries){const old=await c.env.DB.prepare(`SELECT id FROM compliance_settings WHERE main_company_slug=? AND setting_key=?`).bind(s.slug,key).first<Row>();if(old)await c.env.DB.prepare(`UPDATE compliance_settings SET setting_value=?,updated_at=? WHERE id=?`).bind(JSON.stringify(value),ts,old.id).run();else await c.env.DB.prepare(`INSERT INTO compliance_settings(id,main_company_slug,setting_key,setting_value,created_at,updated_at) VALUES(?,?,?,?,?,?)`).bind(crypto.randomUUID(),s.slug,key,JSON.stringify(value),ts,ts).run();}await event(c,s.slug,"SETTINGS_UPDATED","SETTINGS","general",text(s.user?.id),{keys:entries.map(([k])=>k)});return c.json({ok:true})});
  app.get("/api/compliance/tasks",async c=>{const s=await scope(c);if(!s.ok)return scopeError(c,s);const status=upper(c.req.query("status")),where=["main_company_slug=?"],args:any[]=[s.slug];if(status){where.push("status=?");args.push(status)}const r=await c.env.DB.prepare(`SELECT * FROM compliance_tasks WHERE ${where.join(" AND ")} ORDER BY CASE priority WHEN 'CRITICAL' THEN 0 WHEN 'HIGH' THEN 1 WHEN 'NORMAL' THEN 2 ELSE 3 END,COALESCE(due_date,'9999-12-31'),created_at DESC LIMIT 300`).bind(...args).all<Row>();return c.json({ok:true,data:(r.results||[]).map((x:Row)=>({...x,metadata:json(x.metadata,{})}))})});
  app.post("/api/compliance/tasks",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);if(!text(b.title))return c.json(err("TASK_REQUIRED","Görev başlığı zorunludur."),422);const id=crypto.randomUUID(),ts=now();await c.env.DB.prepare(`INSERT INTO compliance_tasks(id,main_company_slug,task_type,title,entity_type,entity_id,due_date,warning_days,priority,status,responsible_user_id,source,metadata,created_by,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,'OPEN',?,?,?, ?,?,?)`).bind(id,s.slug,upper(b.taskType)||"CUSTOM",text(b.title),upper(b.entityType)||null,text(b.entityId)||null,dateOnly(b.dueDate)||null,Number(b.warningDays??10),upper(b.priority)||"NORMAL",text(b.responsibleUserId)||null,upper(b.source)||"MANUAL",JSON.stringify(json(b.metadata,{})),text(s.user?.id)||null,ts,ts).run();await event(c,s.slug,"TASK_CREATED","TASK",id,text(s.user?.id));return c.json({ok:true,data:{id}},201)});
  app.patch("/api/compliance/tasks/:id",async c=>{const b=await bodyOf(c),s=await scope(c,b,true);if(!s.ok)return scopeError(c,s);const old=await c.env.DB.prepare(`SELECT * FROM compliance_tasks WHERE id=? AND main_company_slug=?`).bind(c.req.param("id"),s.slug).first<Row>();if(!old)return c.json(err("NOT_FOUND","Görev bulunamadı."),404);const status=upper(b.status??old.status)||"OPEN",ts=now();await c.env.DB.prepare(`UPDATE compliance_tasks SET title=?,due_date=?,warning_days=?,priority=?,status=?,responsible_user_id=?,metadata=?,completed_at=?,updated_at=? WHERE id=? AND main_company_slug=?`).bind(text(b.title??old.title),dateOnly(b.dueDate??old.due_date)||null,Number(b.warningDays??old.warning_days??10),upper(b.priority??old.priority)||"NORMAL",status,text(b.responsibleUserId??old.responsible_user_id)||null,JSON.stringify(b.metadata===undefined?json(old.metadata,{}):json(b.metadata,{})),["DONE","CLOSED","COMPLETED"].includes(status)?ts:null,ts,old.id,s.slug).run();return c.json({ok:true})});
  app.get("/api/compliance/calendar",async c=>{const s=await scope(c);if(!s.ok)return scopeError(c,s);const [docs,audits,findings,tasks]=await Promise.all([c.env.DB.prepare(`SELECT id,title,expires_at due_date,reminder_days,'DOCUMENT' kind,status FROM compliance_documents WHERE main_company_slug=? AND archived_at IS NULL AND expires_at IS NOT NULL`).bind(s.slug).all<Row>(),c.env.DB.prepare(`SELECT id,name title,planned_date due_date,10 reminder_days,'AUDIT' kind,status FROM compliance_audits WHERE main_company_slug=? AND planned_date IS NOT NULL`).bind(s.slug).all<Row>(),c.env.DB.prepare(`SELECT id,title,due_date,10 reminder_days,'CAPA' kind,status FROM compliance_findings WHERE main_company_slug=? AND due_date IS NOT NULL AND UPPER(status) NOT IN ('CLOSED','VERIFIED')`).bind(s.slug).all<Row>(),c.env.DB.prepare(`SELECT id,title,due_date,warning_days reminder_days,'TASK' kind,status FROM compliance_tasks WHERE main_company_slug=? AND due_date IS NOT NULL AND UPPER(status) NOT IN ('DONE','CLOSED','COMPLETED')`).bind(s.slug).all<Row>()]);const data=[...(docs.results||[]),...(audits.results||[]),...(findings.results||[]),...(tasks.results||[])].sort((a:Row,b:Row)=>text(a.due_date).localeCompare(text(b.due_date)));return c.json({ok:true,data})});
}
