// @ts-nocheck
import type { Context } from "hono";

type AppEnv={Bindings:Cloudflare.Env;Variables:{requestId:string}};
type Row=Record<string,any>;
const text=(v:unknown)=>v==null?"":String(v).trim();
const upper=(v:unknown)=>text(v).toLocaleUpperCase("tr-TR");
const normalize=(v:unknown)=>upper(v).replace(/İ/g,"I").replace(/ı/g,"I").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^A-Z0-9]+/g," ").replace(/\s+/g," ").trim();
const numberValue=(v:unknown)=>{const n=Number(v??0);return Number.isFinite(n)?n:0};
const now=()=>new Date().toISOString();
const json=(v:unknown)=>{if(v&&typeof v==="object"&&!Array.isArray(v))return v as Row;try{const p=JSON.parse(text(v)||"{}");return p&&typeof p==="object"&&!Array.isArray(p)?p:{}}catch{return{}}};

async function tableExists(c:Context<AppEnv>,table:string){const row=await c.env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=? LIMIT 1").bind(table).first<Row>();return Boolean(row?.name)}
async function tableColumns(c:Context<AppEnv>,table:string){if(!(await tableExists(c,table)))return new Set<string>();const result=await c.env.DB.prepare(`PRAGMA table_info("${table.replace(/"/g,'""')}")`).all<Row>();return new Set((result.results||[]).map(row=>text(row.name)))}
async function jsonStoreList(c:Context<AppEnv>,scope:string,slug:string){if(!(await tableExists(c,"json_store")))return[];const result=await c.env.DB.prepare(`SELECT id,file_name,data,created_at,updated_at FROM json_store WHERE scope=? AND (main_company_slug=? OR main_company_slug IS NULL) ORDER BY updated_at DESC,id DESC`).bind(scope,slug).all<Row>();return(result.results||[]).map(row=>({...json(row.data),storeId:text(row.id),fileName:text(row.file_name),createdAt:text(json(row.data).createdAt||row.created_at),updatedAt:text(json(row.data).updatedAt||row.updated_at)}))}
async function jsonStorePut(c:Context<AppEnv>,scope:string,fileName:string,data:Row,slug:string){const existing=await c.env.DB.prepare(`SELECT id,data FROM json_store WHERE scope=? AND file_name=? AND (main_company_slug=? OR main_company_slug IS NULL) ORDER BY updated_at DESC LIMIT 1`).bind(scope,fileName,slug).first<Row>();const ts=now(),payload={...data,updatedAt:ts};if(existing?.id){await c.env.DB.prepare(`UPDATE json_store SET data=?,main_company_slug=COALESCE(main_company_slug,?),updated_at=? WHERE id=?`).bind(JSON.stringify(payload),slug,ts,existing.id).run();return{...payload,storeId:existing.id,fileName}}const id=crypto.randomUUID();await c.env.DB.prepare(`INSERT INTO json_store(id,scope,main_company_slug,file_name,data,created_at,updated_at) VALUES(?,?,?,?,?,?,?)`).bind(id,scope,slug,fileName,JSON.stringify({...payload,createdAt:payload.createdAt||ts}),ts,ts).run();return{...payload,storeId:id,fileName}}

function productView(row:Row,source:string){const raw=json(row.raw);const name=text(row.name||row.productName);return{...row,id:text(row.id||row.fileName||row.storeId),name,productName:name,code:text(row.code||row.legacy_id),unit:text(row.unit||"KG"),raw:{...raw,routingType:source==="BOYAHANE"?"BOYAHANE":raw.routingType||raw.routing_type||"",productGroup:source==="BOYAHANE"?"BOYAHANE":raw.productGroup||raw.product_group||""},_source:source}}
async function boyahaneProducts(c:Context<AppEnv>,slug:string){return(await jsonStoreList(c,"BOYAHANE_APPROVED_PRODUCT",slug)).filter(row=>row.isActive!==false&&text(row.approvalStatus||"APPROVED")==="APPROVED").map(row=>productView(row,"BOYAHANE"))}

export async function listEBelgeProducts(c:Context<AppEnv>,slug:string,q=""){const normalized=normalize(q),rows:Row[]=[];if(await tableExists(c,"products")){const cols=await tableColumns(c,"products"),terms:string[]=["main_company_slug=?"],args:any[]=[slug],or:string[]=[];if(q){if(cols.has("name")){or.push("UPPER(COALESCE(name,'')) LIKE UPPER(?)");args.push(`%${q}%`)}if(cols.has("normalized_name")){or.push("normalized_name=?");args.push(normalized)}if(cols.has("code")){or.push("UPPER(COALESCE(code,'')) LIKE UPPER(?)");args.push(`%${q}%`)}if(cols.has("legacy_id")){or.push("UPPER(COALESCE(legacy_id,'')) LIKE UPPER(?)");args.push(`%${q}%`)}if(or.length)terms.push(`(${or.join(" OR ")})`)}const result=await c.env.DB.prepare(`SELECT * FROM products WHERE ${terms.join(" AND ")} ORDER BY name COLLATE NOCASE LIMIT 50`).bind(...args).all<Row>();rows.push(...(result.results||[]).map(row=>productView(row,"PRODUCTS")))}rows.push(...(await boyahaneProducts(c,slug)).filter(row=>!q||normalize(`${row.name} ${row.code}`).includes(normalized)));const seen=new Set<string>();return rows.filter(row=>{const id=text(row.id);if(!id||seen.has(id))return false;seen.add(id);return true}).slice(0,50)}

export async function getEBelgeProduct(c:Context<AppEnv>,slug:string,id:string){const wanted=text(id);if(!wanted)return null;if(await tableExists(c,"products")){const row=await c.env.DB.prepare(`SELECT * FROM products WHERE main_company_slug=? AND id=? LIMIT 1`).bind(slug,wanted).first<Row>();if(row)return productView(row,"PRODUCTS")}return(await boyahaneProducts(c,slug)).find(row=>text(row.id)===wanted)||null}

export async function matchEBelgeProduct(c:Context<AppEnv>,slug:string,line:Row,companyId=""){const code=normalize(line.productCode||line.supplierProductCode),name=normalize(line.description);let product:Row|null=null;if(await tableExists(c,"products")){const cols=await tableColumns(c,"products"),or:string[]=[],args:any[]=[slug];if(code&&cols.has("code")){or.push("UPPER(COALESCE(code,''))=?");args.push(code)}if(code&&cols.has("legacy_id")){or.push("UPPER(COALESCE(legacy_id,''))=?");args.push(code)}if(name&&cols.has("normalized_name")){or.push("normalized_name=?");args.push(name)}if(name&&cols.has("name")){or.push("UPPER(COALESCE(name,''))=UPPER(?)");args.push(text(line.description))}if(or.length){const row=await c.env.DB.prepare(`SELECT * FROM products WHERE main_company_slug=? AND (${or.join(" OR ")}) LIMIT 1`).bind(...args).first<Row>();if(row)product=productView(row,"PRODUCTS")}}const boya=await boyahaneProducts(c,slug);if(!product)product=boya.find(row=>code&&[row.code,row.legacy_id].map(normalize).includes(code))||boya.find(row=>name&&normalize(row.name)===name)||null;if(!product&&name){const aliases=await jsonStoreList(c,"MUHASEBE_PRODUCT_ALIAS",slug);const alias=aliases.find(row=>{if(row.isActive===false)return false;if(normalize(row.rawName||row.raw_name)!==name)return false;const aliasCompanyId=text(row.companyId||row.supplierFirmId||row.supplierCompanyId);return !aliasCompanyId||Boolean(companyId&&aliasCompanyId===companyId)});if(alias)product=await getEBelgeProduct(c,slug,text(alias.productId))}return product?{productId:text(product.id),product,status:"AUTO_MATCHED",source:product._source==="BOYAHANE"?"BOYAHANE_PRODUCT":"PRODUCT_OR_ALIAS"}:{productId:"",product:null,status:"UNMATCHED",source:"NONE"}}

export function eBelgeProductRouting(product:Row|null,line:Row,supplierProfile:Row={}){const raw=json(product?.raw),routing=upper(raw.routingType||raw.routing_type),group=upper(raw.productGroup||raw.product_group),name=normalize(`${product?.name||product?.productName||""} ${line.description||""}`),supplierChemical=supplierProfile.isChemicalSupplier===true,detectedChemical=product?._source==="BOYAHANE"||routing==="BOYAHANE"||group==="BOYAHANE"||/BOYA|PIGMENT|KIMYA|WHITE|RETARDER|FIXATOR|FIXAT|SILIKON|SILICONE|EMULSIYON|TINER|GAZ|SPREY|SIM/.test(name),chemical=detectedChemical||supplierChemical&&Boolean(product),effectiveRouting=chemical?"BOYAHANE":routing==="STOCK"?"STOCK":routing||"EXPENSE",explicitLot=raw.requiresLot??raw.requireLot??raw.lotRequired??raw.lot_required,lotRequired=explicitLot===true||effectiveRouting==="BOYAHANE"||supplierChemical&&supplierProfile.requireLot!==false;return{routing:effectiveRouting,chemical,lotRequired,expenseCategoryId:text(raw.expenseCategoryId||raw.expense_category_id)||null,expenseCategoryName:text(raw.expenseCategoryName||raw.expense_category_name||raw.expenseCategory)||(effectiveRouting==="EXPENSE"?"Mal ve Hizmet Alımı":null),warehouse:text(raw.warehouse||supplierProfile.defaultWarehouse)||null,defaultUnit:text(raw.defaultUnit||supplierProfile.defaultUnit)||null,supplierChemical}}

export async function getEBelgeSupplierProfile(c:Context<AppEnv>,slug:string,companyId:string){const id=text(companyId);if(!id)return{companyId:"",isChemicalSupplier:false,requireLot:false,defaultWarehouse:"BOYAHANE",defaultUnit:"KG"};const rows=await jsonStoreList(c,"MUHASEBE_CHEMICAL_SUPPLIER",slug),stored=rows.find(row=>text(row.companyId||row.fileName)===id);return{companyId:id,isChemicalSupplier:stored?.isChemicalSupplier===true,requireLot:stored?.requireLot!==false,defaultWarehouse:text(stored?.defaultWarehouse)||"BOYAHANE",defaultUnit:text(stored?.defaultUnit)||"KG",allowNegativeStock:stored?.allowNegativeStock===true}}

export async function getEBelgeCompanyExpenseDefault(c:Context<AppEnv>,slug:string,companyId:string){const id=text(companyId);if(!id||!(await tableExists(c,"companies")))return{categoryId:null,categoryName:""};const row=await c.env.DB.prepare(`SELECT * FROM companies WHERE main_company_slug=? AND id=? AND deleted_at IS NULL LIMIT 1`).bind(slug,id).first<Row>();if(!row)return{categoryId:null,categoryName:""};const raw=json(row.raw);return{categoryId:text(row.expense_category_id||raw.expenseCategoryId||raw.defaultReportCategoryId||raw.varsayilanRaporKategoriId)||null,categoryName:text(row.expense_category||raw.expenseCategory||raw.giderKategorisi||raw.defaultExpenseCategory)}}

async function expenseRuleRows(c:Context<AppEnv>,slug:string){if(await tableExists(c,"accounting_expense_rules")){const r=await c.env.DB.prepare(`SELECT * FROM accounting_expense_rules WHERE main_company_slug=? AND is_active=1 ORDER BY priority ASC,updated_at DESC`).bind(slug).all<Row>();return r.results||[]}return jsonStoreList(c,"ACCOUNTING_EXPENSE_RULE",slug)}

export async function findEBelgeExpenseRule(c:Context<AppEnv>,slug:string,args:{companyId?:string;productId?:string;description?:string}){const companyId=text(args.companyId),productId=text(args.productId),description=normalize(args.description),rules=await expenseRuleRows(c,slug),matches=rules.map(rule=>{const ruleCompany=text(rule.company_id||rule.companyId),ruleProduct=text(rule.product_id||rule.productId),ruleDescription=normalize(rule.normalized_description||rule.normalizedDescription);if(ruleCompany&&ruleCompany!==companyId)return null;if(ruleProduct&&ruleProduct!==productId)return null;if(!ruleProduct&&ruleDescription&&ruleDescription!==description)return null;if(!ruleProduct&&!ruleDescription)return null;const score=(ruleCompany?1000:0)+(ruleProduct?500:0)+(ruleDescription?200:0)-numberValue(rule.priority||100);return{rule,score}}).filter(Boolean).sort((a:any,b:any)=>b.score-a.score);const row=(matches[0] as any)?.rule;return row?{id:text(row.id||row.fileName),companyId:text(row.company_id||row.companyId)||null,productId:text(row.product_id||row.productId)||null,normalizedDescription:normalize(row.normalized_description||row.normalizedDescription),categoryId:text(row.category_id||row.categoryId)||null,categoryName:text(row.category_name||row.categoryName),source:text(row.source)||"USER"}:null}

export async function resolveEBelgeExpenseCategory(c:Context<AppEnv>,slug:string,args:{companyId?:string;productId?:string;description?:string;fallbackName?:string;fallbackId?:string}){const rule=await findEBelgeExpenseRule(c,slug,args);if(rule?.categoryName)return{categoryId:rule.categoryId,categoryName:rule.categoryName,source:"EXPENSE_RULE",ruleId:rule.id};const company=await getEBelgeCompanyExpenseDefault(c,slug,text(args.companyId));if(company.categoryName)return{categoryId:company.categoryId,categoryName:company.categoryName,source:"COMPANY_DEFAULT",ruleId:null};return{categoryId:text(args.fallbackId)||null,categoryName:text(args.fallbackName)||"Mal ve Hizmet Alımı",source:"ROUTING_DEFAULT",ruleId:null}}

export async function saveEBelgeExpenseRule(c:Context<AppEnv>,slug:string,args:{companyId?:string;productId?:string;description?:string;categoryId?:string;categoryName:string;source?:string}){const companyId=text(args.companyId),productId=text(args.productId),normalizedDescription=productId?"":normalize(args.description),categoryName=text(args.categoryName);if(!categoryName)throw Object.assign(new Error("Gider kategorisi zorunludur."),{code:"EXPENSE_CATEGORY_REQUIRED"});if(!productId&&!normalizedDescription)throw Object.assign(new Error("Gider kuralı için ürün veya açıklama zorunludur."),{code:"EXPENSE_RULE_KEY_REQUIRED"});const ts=now();if(await tableExists(c,"accounting_expense_rules")){const existing=await c.env.DB.prepare(`SELECT id FROM accounting_expense_rules WHERE main_company_slug=? AND COALESCE(company_id,'')=? AND COALESCE(product_id,'')=? AND COALESCE(normalized_description,'')=? LIMIT 1`).bind(slug,companyId,productId,normalizedDescription).first<Row>();if(existing?.id){await c.env.DB.prepare(`UPDATE accounting_expense_rules SET category_id=?,category_name=?,routing_type='EXPENSE',is_active=1,source=?,updated_at=? WHERE id=? AND main_company_slug=?`).bind(text(args.categoryId)||null,categoryName,text(args.source)||"USER",ts,existing.id,slug).run();return{id:existing.id,companyId:companyId||null,productId:productId||null,normalizedDescription,categoryId:text(args.categoryId)||null,categoryName}}const id=crypto.randomUUID();await c.env.DB.prepare(`INSERT INTO accounting_expense_rules(id,main_company_slug,company_id,product_id,normalized_description,category_id,category_name,routing_type,priority,is_active,source,created_at,updated_at) VALUES(?,?,?,?,?,?,?,'EXPENSE',100,1,?,?,?)`).bind(id,slug,companyId||null,productId||null,normalizedDescription||null,text(args.categoryId)||null,categoryName,text(args.source)||"USER",ts,ts).run();return{id,companyId:companyId||null,productId:productId||null,normalizedDescription,categoryId:text(args.categoryId)||null,categoryName}}const key=`${companyId||"GLOBAL"}:${productId||normalizedDescription.replace(/\s+/g,"-")}`;return jsonStorePut(c,"ACCOUNTING_EXPENSE_RULE",key,{id:crypto.randomUUID(),companyId:companyId||null,productId:productId||null,normalizedDescription,categoryId:text(args.categoryId)||null,categoryName,routingType:"EXPENSE",priority:100,isActive:true,source:text(args.source)||"USER"},slug)}

export async function saveEBelgeProductAlias(c:Context<AppEnv>,slug:string,args:{companyId?:string;productId:string;productName?:string;rawName:string}){const rawName=text(args.rawName),normalized=normalize(rawName),companyId=text(args.companyId);if(!rawName||!normalized)throw Object.assign(new Error("Alias adı zorunludur."),{code:"ALIAS_REQUIRED"});const key=`${companyId||"GLOBAL"}:${normalized.replace(/\s+/g,"-")}`;return jsonStorePut(c,"MUHASEBE_PRODUCT_ALIAS",key,{id:crypto.randomUUID(),companyId:companyId||null,rawName,normalizedName:normalized,aliasName:text(args.productName)||rawName,productId:text(args.productId),productName:text(args.productName)||rawName,source:"E_BELGE",isActive:true},slug)}

export async function validateEBelgeChemicalReceipt(c:Context<AppEnv>,slug:string,args:{product:Row;lotNo:string}){const product=args.product,lotNo=text(args.lotNo),productId=text(product?.id);if(!productId)throw Object.assign(new Error("LOT için ürün kartı zorunludur."),{code:"PRODUCT_REQUIRED"});if(!lotNo)throw Object.assign(new Error("LOT numarası zorunludur."),{code:"LOT_REQUIRED"});const lotRows=await jsonStoreList(c,"BOYAHANE_LOT",slug),existing=lotRows.find(row=>normalize(row.lotNo)===normalize(lotNo));if(existing&&text(existing.productId||existing.inventoryId)&&text(existing.productId||existing.inventoryId)!==productId)throw Object.assign(new Error(`LOT ${lotNo} başka bir ürüne bağlı.`),{code:"LOT_PRODUCT_CONFLICT"});return{ok:true,existingLotId:text(existing?.id||existing?.fileName)||null}}

export async function recordEBelgeChemicalReceipt(c:Context<AppEnv>,slug:string,args:{document:Row;line:Row;product:Row;lotNo:string}){const {document:doc,line,product}=args,lotNo=text(args.lotNo),productId=text(product.id),productName=text(product.name||product.productName),qty=numberValue(line.quantity),unitPrice=numberValue(line.unit_price||line.unitPrice),movementId=`ebelge:${text(doc.id)}:${text(line.id)}`,priorMovement=await c.env.DB.prepare(`SELECT id FROM json_store WHERE scope='BOYAHANE_STOCK_MOVEMENT' AND main_company_slug=? AND file_name=? LIMIT 1`).bind(slug,movementId).first<Row>(),lotRows=await jsonStoreList(c,"BOYAHANE_LOT",slug);const existing=lotRows.find(row=>normalize(row.lotNo)===normalize(lotNo));if(existing&&text(existing.productId||existing.inventoryId)&&text(existing.productId||existing.inventoryId)!==productId)throw Object.assign(new Error(`LOT ${lotNo} başka bir ürüne bağlı.`),{code:"LOT_PRODUCT_CONFLICT"});if(priorMovement)return{lotId:text(existing?.id||existing?.fileName)||"",created:false,movementCreated:false,idempotent:true};const lotId=text(existing?.id||existing?.fileName)||crypto.randomUUID();const entryBefore=numberValue(existing?.entryKg||existing?.quantity),remainingBefore=numberValue(existing?.remainingKg??existing?.remainingQuantity??entryBefore);await jsonStorePut(c,"BOYAHANE_LOT",lotId,{...existing,id:lotId,inventoryId:productId,productId,productName,dyeType:text(product.dyeType||json(product.raw).dyeType||"GENEL"),lotNo,supplierName:text(doc.party_name),companyName:text(doc.party_name),supplierCompanyId:text(doc.party_company_id)||null,invoiceNo:text(doc.document_no),documentNo:text(doc.document_no),entryKg:entryBefore+qty,quantity:entryBefore+qty,usedKg:numberValue(existing?.usedKg),remainingKg:remainingBefore+qty,remainingQuantity:remainingBefore+qty,unit:text(line.unit_code||product.unit||"KG"),unitPrice,totalAmount:(entryBefore+qty)*unitPrice,status:"AVAILABLE",source:"E_BELGE",sourceDocumentId:text(doc.id),lastEntryAt:now()},slug);await jsonStorePut(c,"BOYAHANE_STOCK_MOVEMENT",movementId,{id:movementId,inventoryId:productId,productId,productName,lotId,lotNo,type:"IN",movementType:"IN",quantity:qty,amountKg:qty,unit:text(line.unit_code||product.unit||"KG"),unitPrice,totalAmount:numberValue(line.line_total),documentId:text(doc.id),documentLineId:text(line.id),documentNo:text(doc.document_no),supplierCompanyId:text(doc.party_company_id)||null,supplierName:text(doc.party_name),sourceType:"E_BELGE",movementDate:text(doc.issue_date)||now(),createdAt:now()},slug);return{lotId,created:!existing,movementCreated:true,idempotent:false}}
