// @ts-nocheck
import type { Context, Hono } from "hono";

type AppEnv = { Bindings: Cloudflare.Env; Variables: { requestId: string } };
type Row = Record<string, any>;

const SETTINGS_SCOPE = "ISNET_SETTINGS";
const PORTAL_SCOPE = "ISNET_PORTAL_DOCUMENT";
const STATE_SCOPE = "ISNET_DOCUMENT_STATE";
const SYNC_SCOPE = "ISNET_SYNC_RUN";
const API_BASE = "https://einvoiceapi.isnet.net.tr";
const PORTAL_BASE = "https://nettefatura.isnet.net.tr";

const text = (value: unknown) => value == null ? "" : String(value).trim();
const numberValue = (value: unknown) => {
  const parsed = Number(value ?? 0);
  return Number.isFinite(parsed) ? parsed : 0;
};
const nowIso = () => new Date().toISOString();
const normalize = (value: unknown) => text(value).toLocaleUpperCase("tr-TR").replace(/İ/g, "I").normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^A-Z0-9]+/g, " ").replace(/\s+/g, " ").trim();
const safeFile = (value: unknown) => text(value).replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/-+/g, "-").replace(/^-|-$/g, "") || "belge";

function obj(value: unknown): Row {
  if (value && typeof value === "object" && !Array.isArray(value)) return value as Row;
  if (typeof value !== "string" || !value.trim()) return {};
  try { const parsed = JSON.parse(value); return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed : {}; } catch { return {}; }
}
function err(code: string, message: string, details?: unknown) {
  return { ok: false, success: false, error: { code, message, ...(details === undefined ? {} : { details }) } };
}
async function bodyOf(c: Context<AppEnv>) { try { return obj(await c.req.json()); } catch { return {}; } }
function slugOf(c: Context<AppEnv>, body: Row = {}) { return text(body.mainCompanySlug || body.main_company_slug || c.req.query("mainCompanySlug") || c.req.query("mainCompanyId") || "mecit-hakan"); }
async function tableExists(c: Context<AppEnv>, table: string) { return Boolean((await c.env.DB.prepare("SELECT name FROM sqlite_master WHERE type='table' AND name=? LIMIT 1").bind(table).first<Row>())?.name); }
async function columns(c: Context<AppEnv>, table: string) { if (!(await tableExists(c, table))) return new Set<string>(); const rows = await c.env.DB.prepare(`PRAGMA table_info("${table.replace(/"/g, '""')}")`).all<Row>(); return new Set((rows.results || []).map((row) => text(row.name))); }

async function storeGet(c: Context<AppEnv>, scope: string, fileName: string, slug: string) {
  if (!(await tableExists(c, "json_store"))) return null;
  const row = await c.env.DB.prepare(`SELECT id,file_name,data,created_at,updated_at FROM json_store WHERE scope=? AND file_name=? AND (main_company_slug=? OR main_company_slug IS NULL) ORDER BY updated_at DESC LIMIT 1`).bind(scope, fileName, slug).first<Row>();
  if (!row) return null;
  return { ...obj(row.data), storeId: text(row.id), fileName: text(row.file_name) };
}
async function storePut(c: Context<AppEnv>, scope: string, fileName: string, data: Row, slug: string) {
  const existing = await storeGet(c, scope, fileName, slug); const ts = nowIso(); const payload = { ...data, updatedAt: ts, createdAt: data.createdAt || existing?.createdAt || ts };
  if (existing?.storeId) { await c.env.DB.prepare("UPDATE json_store SET data=?,updated_at=? WHERE id=?").bind(JSON.stringify(payload), ts, existing.storeId).run(); return payload; }
  await c.env.DB.prepare("INSERT INTO json_store(id,scope,main_company_slug,file_name,data,created_at,updated_at) VALUES(?,?,?,?,?,?,?)").bind(crypto.randomUUID(), scope, slug, fileName, JSON.stringify(payload), ts, ts).run(); return payload;
}

function normalizeCompanies(payload: any) {
  const source = Array.isArray(payload?.CompanyList) ? payload.CompanyList : Array.isArray(payload?.companyList) ? payload.companyList : Array.isArray(payload?.Companies) ? payload.Companies : Array.isArray(payload?.companies) ? payload.companies : Array.isArray(payload?.options) ? payload.options : Array.isArray(payload) ? payload : [];
  const seen = new Set<string>();
  return source.map((row: Row) => ({ id: text(row.IdFirma ?? row.idFirma ?? row.CompanyId ?? row.companyId ?? row.Id ?? row.id), parentId: text(row.IdAnaFirma ?? row.idAnaFirma ?? row.ParentId), name: text(row.FirmaAdi ?? row.firmaAdi ?? row.CompanyName ?? row.companyName ?? row.Name ?? row.name), schemaName: text(row.SchemaName ?? row.schemaName), hasRole: row.UserHasRole !== false && row.hasRole !== false })).filter((row: Row) => row.id && row.name && row.hasRole && !seen.has(row.id) && Boolean(seen.add(row.id)));
}
function payloadMessage(payload: any, fallback = "İşNet isteği başarısız oldu.") { return text(payload?.ErrorMessage || payload?.errorMessage || payload?.Message || payload?.message || payload?.error?.message) || fallback; }

async function loginApi(username: string, password: string) {
  const response = await fetch(`${API_BASE}/api/Account/Login`, { method: "POST", headers: { Accept: "application/json", "Content-Type": "application/json" }, body: JSON.stringify({ IdentificationNumber: username, Password: password }), signal: AbortSignal.timeout(25_000) });
  const raw = await response.text(); let payload: any = {}; try { payload = raw ? JSON.parse(raw) : {}; } catch { payload = {}; }
  if (!response.ok) throw new Error(`API ${response.status}: ${payloadMessage(payload, response.statusText)}`);
  const token = text(payload?.Token || payload?.token); const companies = normalizeCompanies(payload);
  if (!token) throw new Error(payloadMessage(payload, "API tokenı alınamadı."));
  if (!companies.length) throw new Error("API yetkili firma listesi dönmedi.");
  return { token, companies, expiresOn: text(payload?.ExpiresOn || payload?.expiresOn) || null };
}

function verificationToken(html: string) { return text(html.match(/name=["']__RequestVerificationToken["'][^>]*value=["']([^"']+)["']/i)?.[1] || html.match(/value=["']([^"']+)["'][^>]*name=["']__RequestVerificationToken["']/i)?.[1]); }
function mergeCookies(response: Response, jar: Map<string,string>) { const h = response.headers as Headers & {getSetCookie?:()=>string[]}; const values = h.getSetCookie?.() || (h.get("set-cookie") ? [h.get("set-cookie") as string] : []); for (const value of values) { const pair = text(value.split(";",1)[0]); const pos = pair.indexOf("="); if (pos>0) jar.set(pair.slice(0,pos),pair.slice(pos+1)); } }
function cookieHeader(jar: Map<string,string>) { return [...jar.entries()].map(([k,v])=>`${k}=${v}`).join("; "); }

async function portalLogin(username: string, password: string, companyId = "", companyName = "") {
  const jar = new Map<string,string>();
  const request = async (path: string, init: RequestInit = {}) => { const response = await fetch(`${PORTAL_BASE}${path}`, { ...init, headers: { "User-Agent":"KY-ERP-IsNet-Cloud/4.1", ...(init.headers||{}), ...(jar.size ? { Cookie: cookieHeader(jar)} : {}) }, redirect:"manual", signal: AbortSignal.timeout(30_000) }); mergeCookies(response, jar); return response; };
  let response = await request("/Account/Login"); let html = await response.text(); let token = verificationToken(html);
  if (!response.ok || !token) throw new Error("Portal giriş sayfasına ulaşılamadı.");
  response = await request("/Account/Login", { method:"POST", headers:{"Content-Type":"application/x-www-form-urlencoded",Origin:PORTAL_BASE,Referer:`${PORTAL_BASE}/Account/Login`}, body:new URLSearchParams({VknTckn:username,Password:password,RememberMe:"false",__RequestVerificationToken:token}).toString() });
  html = await response.text();
  const companyResponse = await request("/Account/GetCompanyList", { method:"POST", headers:{Accept:"application/json, text/javascript, */*; q=0.01","Content-Type":"application/x-www-form-urlencoded; charset=UTF-8",Origin:PORTAL_BASE,Referer:`${PORTAL_BASE}/Account/Login`,"X-Requested-With":"XMLHttpRequest"}, body:new URLSearchParams({q:""}).toString() });
  const companyRaw = await companyResponse.text(); let companyPayload:any={}; try{companyPayload=companyRaw?JSON.parse(companyRaw):{}}catch{companyPayload={}}; const companies=normalizeCompanies(companyPayload);
  if (!companies.length) throw new Error(/captcha|güvenlik kodu|hatalı giriş/i.test(html) ? "Portal kullanıcı adı/TCKN veya şifreyi kabul etmedi." : "Portal yetkili firma listesi alınamadı.");
  if (!companyId) return { companies, cookie: cookieHeader(jar), companySelected:false };
  const selected = companies.find((row:Row)=>text(row.id)===companyId); if (!selected) throw new Error("Seçilen firma İşNet yetki listesinde bulunamadı.");
  response = await request("/Account/Login"); html = await response.text(); token = verificationToken(html); if (!token) throw new Error("Portal firma seçimi başlatılamadı.");
  response = await request("/Account/Login", { method:"POST", headers:{"Content-Type":"application/x-www-form-urlencoded",Origin:PORTAL_BASE,Referer:`${PORTAL_BASE}/Account/Login`}, body:new URLSearchParams({VknTckn:username,Password:password,"validation[Companylist]":companyName || selected.name,CompanyId:companyId,RememberMe:"false",__RequestVerificationToken:token}).toString() });
  const location = text(response.headers.get("location")); if (response.status!==302 || location!=="/") throw new Error("İşNet firmasıyla portal oturumu açılamadı.");
  return { companies, cookie: cookieHeader(jar), companySelected:true };
}

function publicSettings(row:Row){return {username:text(row.username),companyId:text(row.companyId),companyName:text(row.companyName),companies:Array.isArray(row.companies)?row.companies:[],connectionMode:text(row.connectionMode||"portal"),hasPassword:false,sessionReady:Boolean(text(row.accessToken)||text(row.portalCookie)),apiSessionReady:Boolean(text(row.accessToken)),portalSessionReady:Boolean(text(row.portalCookie)&&row.portalCompanySelected===true),tokenExpiresOn:row.tokenExpiresOn||null,testedAt:row.testedAt||null,securityNote:"Şifre kaydedilmez; İşNet API tokenı ve/veya portal oturum çerezi saklanır."};}

const SOURCES = [
  {kind:"invoice",direction:"incoming",page:(min:string)=>`/IncomingInvoice/IncomingInvoiceList?minDate=${min}`,endpoint:"/IncomingInvoice/AllIncomingInvoiceByFilter"},
  {kind:"invoice",direction:"outgoing",page:(min:string)=>`/OutgoingInvoice/OutgoingInvoiceList?minDate=${min}`,endpoint:"/OutgoingInvoice/AllOutgoingInvoiceByFilter"},
  {kind:"dispatch",direction:"incoming",page:(min:string)=>`/IncomingDespatchAdvice/IncomingDespatchAdviceList?minDate=${min}`,endpoint:"/IncomingDespatchAdvice/AllIncomingDespatchAdviceByFilter"},
  {kind:"dispatch",direction:"outgoing",page:()=>"/OutgoingDespatch/OutgoingDespatchList",endpoint:"/OutgoingDespatch/AllOutgoingDespatchByFilter"},
] as const;
function portalDate(value:string){const [y,m,d]=value.split("-");return `${d}.${m}.${y}`;}
function normalizePortal(source:any,row:Row){const incoming=source.direction==="incoming";const invoice=source.kind==="invoice";const sourceId=text(invoice?(incoming?row.IdFaturaGelen:row.IdFatura):(incoming?row.IdIrsaliyeGelen:row.IdIrsaliye));return {id:`${source.direction}-${source.kind}-${sourceId}`,sourceId,kind:source.kind,direction:source.direction,documentNo:text(invoice?row.FaturaNo:row.IrsaliyeNo),dateText:text(invoice?row.FaturaTarihiFormated:row.IrsaliyeTarihiFormated),transferDateText:text(incoming?row.GelisTarihiFormated:row.GonderilmeTarihiFormated),partnerName:text(incoming?(row.FirmaAdi||row.AliciAdi):row.AliciAdi),partnerTaxNo:text(row.VknTckn||row.VNKTCKN||row.VKN||row.TCKN),scenarioText:text(row.SenaryoAdi),subtypeText:text(invoice?row.FaturaTipiAdi:row.IrsaliyeTipiAdi),statusText:text(row.DurumAdi||row.GonderimDurumAdi),amount:invoice?numberValue(row.OdenecekTutar):0,amountText:invoice?text(row.OdenecekTutarFormatted):"",currency:invoice?text(row.DovizKodu):"",uuid:invoice?text(row.Ettn||row.ETTN||row.UUID):"",raw:row};}

async function portalRequest(cookie:string,path:string,init:RequestInit={}){return fetch(`${PORTAL_BASE}${path}`,{...init,headers:{"User-Agent":"KY-ERP-IsNet-Cloud/4.1",...(init.headers||{}),Cookie:cookie},redirect:"manual",signal:AbortSignal.timeout(30_000)});}
async function fetchSource(cookie:string,source:any,companyId:string,startDate:string,endDate:string){const pagePath=source.page(startDate);const pageResponse=await portalRequest(cookie,pagePath);const pageHtml=await pageResponse.text();const token=verificationToken(pageHtml);if(!pageResponse.ok||!token)throw new Error(`${source.direction} ${source.kind} ekranı açılamadı; portal oturumunu yeniden test edin.`);const rows:Row[]=[];const length=300;let total=length;for(let start=0;start<total&&start<1500;start+=length){const form:Record<string,string>={draw:"1",start:String(start),length:String(length),"search[value]":"","search[regex]":"false",CompanyIdFilter:companyId,__RequestVerificationToken:token,IlkTarih:portalDate(startDate),SonTarih:portalDate(endDate)};if(source.kind==="invoice"){form.FaturaIlkTarihi=portalDate(startDate);form.FaturaSonTarihi=portalDate(endDate);}else{form.IrsaliyeIlkTarihi=portalDate(startDate);form.IrsaliyeSonTarihi=portalDate(endDate);}const response=await portalRequest(cookie,source.endpoint,{method:"POST",headers:{Accept:"application/json","Content-Type":"application/x-www-form-urlencoded; charset=UTF-8",Referer:`${PORTAL_BASE}${pagePath}`,"X-Requested-With":"XMLHttpRequest"},body:new URLSearchParams(form).toString()});const payload:any=await response.json().catch(()=>null);if(!response.ok||!Array.isArray(payload?.data))throw new Error(`${source.direction} ${source.kind} listesi alınamadı.`);rows.push(...payload.data);total=Math.min(numberValue(payload.recordsFiltered||payload.recordsTotal),5000);if(payload.data.length<length)break;}return rows.map((row)=>normalizePortal(source,row)).filter((row)=>row.sourceId&&row.documentNo);}

function xmlDecode(value:string){return value.replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&amp;/g,"&").replace(/&quot;/g,'"').replace(/&apos;/g,"'").trim();}
function tag(xml:string,name:string){const match=xml.match(new RegExp(`<(?:[A-Za-z0-9_-]+:)?${name}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/(?:[A-Za-z0-9_-]+:)?${name}>`,`i`));return match?xmlDecode(match[1].replace(/<[^>]+>/g," ").replace(/\s+/g," ")):"";}
function moneyTag(xml:string,name:string){const v=tag(xml,name).replace(/\./g,"").replace(",",".");const n=Number(v);return Number.isFinite(n)?n:0;}
function parseUbl(xml:string,kind:string){const documentNo=tag(xml,"ID");const issueDate=tag(xml,"IssueDate");const taxNo=text(xml.match(/<(?:\w+:)?CompanyID[^>]*>([^<]+)<\/[^>]*CompanyID>/i)?.[1]);const supplierName=tag(xml,"Name");const taxTotal=moneyTag(xml,"TaxAmount");const subtotal=moneyTag(xml,"TaxExclusiveAmount")||moneyTag(xml,"LineExtensionAmount");const total=moneyTag(xml,"PayableAmount")||moneyTag(xml,"TaxInclusiveAmount");let quantity=0;const qtyMatches=[...xml.matchAll(/<(?:\w+:)?(?:InvoicedQuantity|DeliveredQuantity)[^>]*>([^<]+)</gi)];for(const match of qtyMatches){const n=Number(text(match[1]).replace(",","."));if(Number.isFinite(n))quantity+=n;}return {documentNo,issueDate,taxNo,supplierName,taxTotal,subtotal,total,quantity,kind};}

async function findCompany(c:Context<AppEnv>,slug:string,name:string,taxNo:string){if(!(await tableExists(c,"companies")))return null;const cols=await columns(c,"companies");const clauses:string[]=[];const binds:any[]=[];if(cols.has("main_company_slug")){clauses.push("main_company_slug=?");binds.push(slug);}if(cols.has("deleted_at"))clauses.push("deleted_at IS NULL");const result=await c.env.DB.prepare(`SELECT * FROM companies${clauses.length?` WHERE ${clauses.join(" AND ")}`:""}`).bind(...binds).all<Row>();const tax=text(taxNo).replace(/\D/g,"");if(tax){const match=(result.results||[]).find((row)=>text(row.tax_no).replace(/\D/g,"")===tax);if(match)return match;}const n=normalize(name);return (result.results||[]).find((row)=>normalize(row.name)===n||normalize(row.normalized_name)===n)||null;}
async function insertDynamic(c:Context<AppEnv>,table:string,values:Row){const cols=await columns(c,table);const entries=Object.entries(values).filter(([key])=>cols.has(key));if(!entries.length)return;await c.env.DB.prepare(`INSERT INTO ${table} (${entries.map(([key])=>`"${key}"`).join(",")}) VALUES (${entries.map(()=>"?").join(",")})`).bind(...entries.map(([,value])=>typeof value==="object"&&value!==null?JSON.stringify(value):value)).run();}
async function ensureAccountingDocument(c:Context<AppEnv>,slug:string,doc:Row,xmlText:string){if(!(await tableExists(c,"documents")))return null;if(!(doc.direction==="incoming"&&["invoice","dispatch"].includes(doc.kind))&&!(doc.direction==="outgoing"&&doc.kind==="invoice"))return null;if(doc.direction==="incoming"&&doc.kind==="dispatch"){const company=await findCompany(c,slug,doc.partnerName,doc.partnerTaxNo);const role=normalize(company?.company_type||company?.type);if(/SUPPLIER|TEDARIK|SATICI/.test(role))return null;}const parsed=parseUbl(xmlText,doc.kind);const existing=await c.env.DB.prepare("SELECT id FROM documents WHERE main_company_slug=? AND document_no=? LIMIT 1").bind(slug,doc.documentNo).first<Row>();if(existing?.id)return text(existing.id);const company=await findCompany(c,slug,doc.partnerName||parsed.supplierName,doc.partnerTaxNo||parsed.taxNo);const id=crypto.randomUUID();const documentType=doc.direction==="outgoing"?"CUSTOMER_INVOICE":doc.kind==="invoice"?"SUPPLIER_INVOICE":"CUSTOMER_DISPATCH";const raw={source:"ISNET_DIRECT",direction:doc.direction,kind:doc.kind,companyName:doc.partnerName,supplierName:doc.partnerName,taxNo:doc.partnerTaxNo,quantity:parsed.quantity,portalSourceId:doc.sourceId,automationKey:doc.automationKey,pdfKey:doc.pdfKey,xmlKey:doc.xmlKey};await insertDynamic(c,"documents",{id,main_company_slug:slug,company_id:company?.id||null,document_type:documentType,detected_type:documentType,target_type:documentType,document_no:doc.documentNo,date:parsed.issueDate||doc.dateText||new Date().toISOString().slice(0,10),source_type:"ISNET_DIRECT",status:doc.direction==="incoming"&&doc.kind==="invoice"?"CONTROL_WAITING":"PROCESSED",firm_match_status:company?.id?"MATCHED":"PENDING",subtotal:parsed.subtotal,vat_total:parsed.taxTotal,grand_total:parsed.total||doc.amount,metadata:raw,raw,created_at:nowIso(),updated_at:nowIso()});return id;}

async function downloadFile(cookie:string,doc:Row,format:"pdf"|"xml"){const incoming=doc.direction==="incoming";const entity=doc.kind==="invoice"?"Invoice":"Despatch";const path=`/${entity}/Get${entity}${format==="pdf"?"Pdf":"Xml"}?InOrOut=${incoming}&${entity}Id=${encodeURIComponent(doc.sourceId)}`;const response=await portalRequest(cookie,path);const buffer=await response.arrayBuffer();if(!response.ok||!buffer.byteLength)throw new Error(`${doc.documentNo} ${format.toUpperCase()} indirilemedi.`);return {buffer,contentType:text(response.headers.get("content-type"))||(format==="pdf"?"application/pdf":"application/xml")};}

export function registerIsnetLiveSyncRoutes(app:Hono<AppEnv>){
  const getSettings=async(c:Context<AppEnv>)=>{const slug=slugOf(c);return c.json({ok:true,success:true,data:publicSettings((await storeGet(c,SETTINGS_SCOPE,slug,slug))||{})});};
  app.get("/api/isnet/settings",getSettings);app.get("/api/isnet/connection",getSettings);
  const test=async(c:Context<AppEnv>)=>{const body=await bodyOf(c);const slug=slugOf(c,body);const current=(await storeGet(c,SETTINGS_SCOPE,slug,slug))||{};const username=text(body.username||current.username);const password=text(body.password);if(!username||!password)return c.json(err("ISNET_CREDENTIALS_REQUIRED","İşNet kullanıcı adı/TCKN ve şifre zorunludur."),400);let api:any=null,portal:any=null,apiError="",portalError="";try{api=await loginApi(username,password)}catch(e:any){apiError=text(e?.message)}try{portal=await portalLogin(username,password)}catch(e:any){portalError=text(e?.message)}if(!api&&!portal)return c.json(err("ISNET_LOGIN_FAILED",`İşNet bağlantısı kurulamadı. API: ${apiError||"başarısız"} Portal: ${portalError||"başarısız"}`),502);const companies=api?.companies?.length?api.companies:portal.companies;const saved=await storePut(c,SETTINGS_SCOPE,slug,{...current,username,companies,accessToken:api?.token||current.accessToken||"",tokenExpiresOn:api?.expiresOn||current.tokenExpiresOn||null,portalCookie:portal?.cookie||current.portalCookie||"",portalCompanySelected:false,connectionMode:api?"api":"portal",testedAt:nowIso(),passwordStored:false,diagnostics:{api:api?"Bağlandı":apiError,portal:portal?"Bağlandı":portalError}},slug);return c.json({ok:true,success:true,data:{...publicSettings(saved),companies,authorizedCompanies:companies,message:"İşNet bağlantısı doğrulandı. Yetkili firmayı seçip Kaydet'e basın."}});};
  app.post("/api/isnet/settings/test",test);app.post("/api/isnet/connection/test",test);
  const save=async(c:Context<AppEnv>)=>{const body=await bodyOf(c);const slug=slugOf(c,body);let current=(await storeGet(c,SETTINGS_SCOPE,slug,slug))||{};const username=text(body.username||current.username);const password=text(body.password);const companyId=text(body.companyId||current.companyId);const companies=Array.isArray(current.companies)?current.companies:[];let selected=companies.find((row:Row)=>text(row.id)===companyId);if(!username||!companyId||!selected)return c.json(err("ISNET_COMPANY_REQUIRED","Önce bağlantıyı test edin ve yetkili firmayı seçin."),400);let apiToken=text(current.accessToken);let portalCookie=text(current.portalCookie);let apiExpires=current.tokenExpiresOn||null;if(password){try{const api=await loginApi(username,password);apiToken=api.token;apiExpires=api.expiresOn;current.companies=api.companies;selected=api.companies.find((row:Row)=>text(row.id)===companyId)||selected;}catch{/* portal may still work */}try{const portal=await portalLogin(username,password,companyId,text(selected.name));portalCookie=portal.cookie;}catch(e:any){if(!apiToken)return c.json(err("ISNET_PORTAL_COMPANY_LOGIN_FAILED",text(e?.message)||"Portal firma oturumu açılamadı."),502);}}const saved=await storePut(c,SETTINGS_SCOPE,slug,{...current,username,companyId,companyName:text(selected.name),companies:Array.isArray(current.companies)?current.companies:companies,accessToken:apiToken,tokenExpiresOn:apiExpires,portalCookie,portalCompanySelected:Boolean(portalCookie&&password),connectionMode:apiToken?"api":"portal",savedAt:nowIso(),passwordStored:false},slug);return c.json({ok:true,success:true,data:{...publicSettings(saved),message:saved.portalCompanySelected?"İşNet firması kaydedildi; portal senkronizasyon oturumu hazır.":"Firma kaydedildi. API oturumu hazır; portal oturumu yenilemek için şifreyle tekrar Kaydet kullanabilirsiniz."}});};
  app.put("/api/isnet/settings",save);app.put("/api/isnet/connection",save);

  app.post("/api/isnet/full-sync",async(c)=>{const body=await bodyOf(c);const slug=slugOf(c,body);const settings=(await storeGet(c,SETTINGS_SCOPE,slug,slug))||{};const cookie=text(settings.portalCookie);const companyId=text(settings.companyId);if(!cookie||!companyId||settings.portalCompanySelected!==true)return c.json(err("ISNET_PORTAL_SESSION_REQUIRED","İşNet portal oturumu hazır değil. Ayarlarda şifreyi girip Bağlantıyı Test Et, firmayı seçip Kaydet yapın."),409);const endDate=text(body.endDate)||new Date().toISOString().slice(0,10);const defaultStart=new Date(`${endDate}T00:00:00Z`);defaultStart.setUTCDate(defaultStart.getUTCDate()-31);const startDate=text(body.startDate)||defaultStart.toISOString().slice(0,10);const runId=crypto.randomUUID();await storePut(c,SYNC_SCOPE,"latest",{id:runId,status:"RUNNING",startedAt:nowIso(),startDate,endDate},slug);try{const groups=await Promise.all(SOURCES.map((source)=>fetchSource(cookie,source,companyId,startDate,endDate)));const docs=groups.flat();let downloaded=0,failed=0,accountingCreated=0;for(const base of docs){const automationKey=`${base.direction}:${base.kind}:${base.sourceId}`;let state=(await storeGet(c,STATE_SCOPE,automationKey,slug))||{};const month=(base.dateText&&/^\d{2}\.\d{2}\.\d{4}$/.test(base.dateText))?base.dateText.split(".").reverse().slice(0,2).join("-"):(base.dateText||new Date().toISOString()).slice(0,7);const folder=`${slug}/isnet/${base.direction}/${base.kind}/${month}/${safeFile(base.documentNo)}`;let pdfKey=text(state.pdfKey),xmlKey=text(state.xmlKey),xmlText="";try{if(!pdfKey){const pdf=await downloadFile(cookie,base,"pdf");pdfKey=`${folder}/${safeFile(base.documentNo)}.pdf`;await c.env.FILES.put(pdfKey,pdf.buffer,{httpMetadata:{contentType:pdf.contentType}});}if(!xmlKey){const xml=await downloadFile(cookie,base,"xml");xmlKey=`${folder}/${safeFile(base.documentNo)}.xml`;await c.env.FILES.put(xmlKey,xml.buffer,{httpMetadata:{contentType:xml.contentType}});xmlText=new TextDecoder().decode(xml.buffer);}else{const existing=await c.env.FILES.get(xmlKey);if(existing)xmlText=await existing.text();}downloaded++;}catch(e:any){failed++;state={...state,error:text(e?.message)};}const portal={...base,automationKey,pdfKey,xmlKey};await storePut(c,PORTAL_SCOPE,automationKey,portal,slug);state=await storePut(c,STATE_SCOPE,automationKey,{...state,...portal,completed:Boolean(pdfKey&&xmlKey),pdfSaved:Boolean(pdfKey),xmlSaved:Boolean(xmlKey),downloadedAt:pdfKey&&xmlKey?nowIso():state.downloadedAt||null,lastAttemptAt:nowIso()},slug);if(xmlText){const id=await ensureAccountingDocument(c,slug,portal,xmlText);if(id)accountingCreated++;}}
    const result={id:runId,status:"COMPLETED",startedAt:(await storeGet(c,SYNC_SCOPE,"latest",slug))?.startedAt,completedAt:nowIso(),startDate,endDate,portalCount:docs.length,downloaded,failed,accountingCreated,counts:{incomingInvoices:docs.filter((d)=>d.direction==="incoming"&&d.kind==="invoice").length,incomingDispatches:docs.filter((d)=>d.direction==="incoming"&&d.kind==="dispatch").length,outgoingDispatches:docs.filter((d)=>d.direction==="outgoing"&&d.kind==="dispatch").length,outgoingInvoices:docs.filter((d)=>d.direction==="outgoing"&&d.kind==="invoice").length}};await storePut(c,SYNC_SCOPE,"latest",result,slug);return c.json({ok:true,success:true,data:result});}catch(e:any){const result={id:runId,status:"FAILED",completedAt:nowIso(),error:text(e?.message)};await storePut(c,SYNC_SCOPE,"latest",result,slug);return c.json(err("ISNET_SYNC_FAILED",text(e?.message)||"İşNet senkronizasyonu tamamlanamadı."),502);}});
  app.get("/api/isnet/full-sync/status",async(c)=>{const slug=slugOf(c);return c.json({ok:true,success:true,data:(await storeGet(c,SYNC_SCOPE,"latest",slug))||{status:"NOT_RUN"}});});
}
