import { DefaultStorageRule } from "./storage.types";

export const DEFAULT_STORAGE_RULES: DefaultStorageRule[] = [
  {
    module: "DESEN",
    documentType: "DESEN_GORSEL",
    displayName: "Desen Gorseli",
    targetPathTemplate: "desen/modeller",
    allowedExtensions: "jpg,jpeg,png,webp",
    imageResizeEnabled: true,
    imageMaxWidth: 1200,
    imageMaxHeight: 1200,
    thumbEnabled: true,
    thumbWidth: 320,
    thumbHeight: 320,
    watchEnabled: true,
  },
  {
    module: "DESEN",
    documentType: "KANAL_GORSEL",
    displayName: "Kanal Gorseli",
    targetPathTemplate: "desen/{firma}/{model}/kanal",
    allowedExtensions: "jpg,jpeg,png,webp",
    imageResizeEnabled: true,
    imageMaxWidth: 1200,
    imageMaxHeight: 1200,
    thumbEnabled: true,
    thumbWidth: 320,
    thumbHeight: 320,
  },
  {
    module: "DESEN",
    documentType: "DESEN_PDF",
    displayName: "Desen PDF",
    targetPathTemplate: "desen/{firma}/{model}/pdf",
    allowedExtensions: "pdf",
  },
  {
    module: "MUHASEBE_MUSTERI",
    documentType: "MUSTERI_GELEN_IRSALIYE",
    displayName: "Musteriden Gelen Irsaliye",
    targetPathTemplate: "muhasebe/musteri/{firma}/{yil}/{ay}/gelen-irsaliye",
    allowedExtensions: "pdf,xml,zip",
    watchEnabled: true,
  },
  {
    module: "MUHASEBE_MUSTERI",
    documentType: "BIZIM_IRSALIYE",
    displayName: "Bizim Irsaliye",
    targetPathTemplate: "muhasebe/musteri/{firma}/{yil}/{ay}/bizim-irsaliye",
    allowedExtensions: "pdf,xml,zip",
    watchEnabled: true,
  },
  {
    module: "MUHASEBE_MUSTERI",
    documentType: "BIZIM_FATURA",
    displayName: "Bizim Fatura",
    targetPathTemplate: "muhasebe/musteri/{yil}/{ay}/bizim-fatura",
    allowedExtensions: "pdf,xml,zip",
    watchEnabled: true,
  },
  {
    module: "MUHASEBE_MUSTERI",
    documentType: "MUSTERI_FATURA",
    displayName: "Musteri Faturasi",
    targetPathTemplate: "muhasebe/musteri/{yil}/{ay}/musteri-fatura",
    allowedExtensions: "pdf,xml,zip",
    watchEnabled: true,
  },
  {
    module: "MUHASEBE_MUSTERI",
    documentType: "SATIS_FATURA",
    displayName: "Satis Faturasi",
    targetPathTemplate: "muhasebe/musteri/{firma}/{yil}/{ay}/satis-fatura",
    allowedExtensions: "pdf,xml,zip",
  },
  {
    module: "TASNIF",
    documentType: "TASNIF_RAPORU",
    displayName: "Tasnif Raporu",
    targetPathTemplate: "muhasebe/musteri/{firma}/{yil}/{ay}/tasnif",
    allowedExtensions: "xlsx,xls,pdf",
  },
  {
    module: "MUHASEBE_TEDARIKCI",
    documentType: "TEDARIKCI_FATURA",
    displayName: "Tedarikci Faturasi",
    targetPathTemplate: "muhasebe/tedarikci/{firma}/{yil}/{ay}/fatura",
    allowedExtensions: "pdf,xml,zip",
    watchEnabled: true,
  },
  {
    module: "MUHASEBE_TEDARIKCI",
    documentType: "TEDARIKCI_IRSALIYE",
    displayName: "Tedarikci Irsaliyesi",
    targetPathTemplate: "muhasebe/tedarikci/{firma}/{yil}/{ay}/irsaliye",
    allowedExtensions: "pdf,xml,zip",
    watchEnabled: true,
  },
  {
    module: "MUHASEBE_TEDARIKCI",
    documentType: "LOT_BELGESI",
    displayName: "Lot Belgesi",
    targetPathTemplate: "muhasebe/tedarikci/{firma}/{yil}/{ay}/lot-belgeleri",
    allowedExtensions: "pdf,jpg,jpeg,png",
  },
  {
    module: "CEK",
    documentType: "CEK_GORSEL",
    displayName: "Cek Gorseli",
    targetPathTemplate: "muhasebe/cekler/{yil}/{ay}/{cekTipi}",
    allowedExtensions: "jpg,jpeg,png,pdf",
    thumbEnabled: true,
    thumbWidth: 320,
    thumbHeight: 320,
  },
  {
    module: "IK_PERSONEL",
    documentType: "PERSONEL_KIMLIK",
    displayName: "Personel Kimlik",
    targetPathTemplate: "ik/personel/{personel}/kimlik",
    allowedExtensions: "pdf,jpg,jpeg,png",
  },
  {
    module: "IK_PERSONEL",
    documentType: "PERSONEL_SOZLESME",
    displayName: "Personel Sozlesme",
    targetPathTemplate: "ik/personel/{personel}/sozlesme",
    allowedExtensions: "pdf,doc,docx,jpg,jpeg,png",
  },
  {
    module: "IK_PERSONEL",
    documentType: "PERSONEL_SGK",
    displayName: "Personel SGK",
    targetPathTemplate: "ik/personel/{personel}/sgk",
    allowedExtensions: "pdf,jpg,jpeg,png",
  },
  {
    module: "IK_PERSONEL",
    documentType: "PERSONEL_IZIN",
    displayName: "Personel Izin",
    targetPathTemplate: "ik/personel/{personel}/izin",
    allowedExtensions: "pdf,doc,docx,jpg,jpeg,png",
  },
  {
    module: "IK_PERSONEL",
    documentType: "PERSONEL_DIGER",
    displayName: "Personel Evraklari",
    targetPathTemplate: "ik/personel/{personel}/diger",
    allowedExtensions: "pdf,doc,docx,jpg,jpeg,png",
  },
];