import { useCallback, useEffect, useMemo, useState } from "react";
import { apiFetch, apiGet, apiPost } from "../../utils/api";
import "./AdminManagement.css";
import "./StorageCloudHub.css";

const ROUTE_TO_TAB={"depolama-genel":"overview","depolama-kaynaklar":"connections","depolama-atamalar":"bindings","depolama-dosyalar":"files","depolama-senkronizasyon":"sync","depolama-yedekleme":"logs"};
const TABS=[["overview","Genel Bakış"],["connections","Servisler"],["bindings","Bölüm / Dosya Atamaları"],["files","Dosya İndeksi"],["sync","Senkronizasyon"],["logs","Loglar"]];
const MODULES=["DESEN","IMALAT","BOYAHANE","MUHASEBE","EBELGE","IK","DTF","STOK"];
const PURPOSES=["MODEL_IMAGE","MODEL_SOURCE","PLACEMENT","OUTGOING_DESIGN","RIP_PDF","INVOICE","DELIVERY_NOTE","E_DOCUMENT","PAYMENT_DOCUMENT","PERSONNEL_DOCUMENT","CONTRACT","RECIPE","TECHNICAL_SHEET","QUALITY","PRODUCTION_PHOTO","QUALITY_PHOTO","CUSTOMER_REFERENCE","GENERIC"];
const providerLabel=v=>({GOOGLE_DRIVE:"Google Drive",ONEDRIVE:"Microsoft OneDrive",SHAREPOINT:"Microsoft SharePoint",LOCAL_FOLDER:"Yerel Klasör",NAS:"NAS / Ağ Klasörü"})[v]||v||"-";
const moduleLabel=v=>({DESEN:"Desen",IMALAT:"İmalat",BOYAHANE:"Boyahane",MUHASEBE:"Muhasebe",EBELGE:"e-Belge Merkezi",ISNET:"e-Belge Merkezi (Eski)",IK:"İK",DTF:"DTF",STOK:"Stok"})[v]||v||"-";
const purposeLabel=v=>({MODEL_IMAGE:"Desen / Model Görseli",MODEL_SOURCE:"Kaynak Dosya (PSD / AI / TIFF)",PLACEMENT:"Yerleşim / Kalıp",OUTGOING_DESIGN:"Giden Desen / Takım",RIP_PDF:"DTF / RIP PDF",INVOICE:"Fatura",DELIVERY_NOTE:"İrsaliye",E_DOCUMENT:"e-Belge",PAYMENT_DOCUMENT:"Ödeme / Dekont / Çek",PERSONNEL_DOCUMENT:"Personel Evrakı",CONTRACT:"Sözleşme",RECIPE:"Reçete",TECHNICAL_SHEET:"Teknik Föy",QUALITY:"Kalite Belgesi",PRODUCTION_PHOTO:"Üretim Fotoğrafı",QUALITY_PHOTO:"Kalite Fotoğrafı",CUSTOMER_REFERENCE:"Müşteri Referansı",GENERIC:"Genel Ek / Diğer"})[v]||v||"-";
const statusLabel=v=>({CONNECTED:"Bağlı",DISCONNECTED:"Bağlantı Kesildi",ERROR:"Hata",UNKNOWN:"Bekliyor",AVAILABLE:"Mevcut",MISSING:"Kaynakta Yok",ONLINE:"Çevrimiçi",OFFLINE:"Çevrimdışı"})[v]||v||"-";
const formatDate=v=>v?new Date(v).toLocaleString("tr-TR"):"-";
const formatBytes=v=>{const n=Number(v||0);if(n<1024)return`${n} B`;if(n<1048576)return`${(n/1024).toFixed(1)} KB`;if(n<1073741824)return`${(n/1048576).toFixed(1)} MB`;return`${(n/1073741824).toFixed(2)} GB`};
const isCloud=p=>["GOOGLE_DRIVE","ONEDRIVE","SHAREPOINT"].includes(p);
const eventLabel=v=>({DISCOVERED:"Yeni dosya bulundu",UPDATED:"Dosya güncellendi",SEEN:"Dosya doğrulandı",MISSING:"Dosya kaynakta yok",CONNECTION_CREATED:"Servis eklendi",CONNECTION_UPDATED:"Servis güncellendi",BINDING_SAVED:"Klasör ataması kaydedildi",AGENT_CREDENTIAL_ROTATED:"Agent anahtarı yenilendi"})[v]||v||"Sistem olayı";

function FolderBrowser({slug,accountId,driveId="",initialRootId="root",initialRootName="Ana Klasör",onSelect,selectLabel="Bu Klasörü Seç"}){
 const[stack,setStack]=useState([{id:initialRootId||"root",name:initialRootName||"Ana Klasör",path:""}]),[folders,setFolders]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const current=stack[stack.length-1],path=stack.slice(1).map(x=>x.name).join("/");
 const load=useCallback(async()=>{if(!accountId)return;setLoading(true);setError("");try{const r=await apiGet("/file-hub/cloud/folders",{mainCompanySlug:slug,accountId,parentId:current.id,driveId:driveId||undefined});setFolders(r?.data||[])}catch(e){setError(e?.message||"Klasörler alınamadı.");setFolders([])}finally{setLoading(false)}},[accountId,current.id,driveId,slug]);
 useEffect(()=>{load()},[load]);
 return <div className="storage-folder-browser"><div className="storage-folder-toolbar"><button className="storage-secondary" type="button" disabled={stack.length===1} onClick={()=>setStack(x=>x.slice(0,-1))}>← Geri</button><div className="storage-breadcrumb">{stack.map(x=>x.name).join(" / ")}</div><button className="storage-primary" type="button" onClick={()=>onSelect?.({id:current.id,name:current.name,path})}>{selectLabel}</button></div>{error?<div className="storage-notice bad">{error}</div>:null}<div className="storage-folder-list">{loading?<div className="storage-empty-v2">Klasörler yükleniyor...</div>:folders.length?folders.map(f=><button type="button" className="storage-folder-row" key={f.id} onClick={()=>setStack(rows=>[...rows,{id:f.id,name:f.name,path:path?`${path}/${f.name}`:f.name}])}><span>📁 <strong>{f.name}</strong></span><small>Aç →</small></button>):<div className="storage-empty-v2"><strong>Alt klasör yok</strong><p>Bu klasörü doğrudan seçebilirsiniz.</p></div>}</div></div>;
}

function ServiceWizard({slug,providers,accounts,onClose,onSaved,initialAccountId="",initialProvider=""}){
 const[provider,setProvider]=useState(initialProvider),[accountId,setAccountId]=useState(initialAccountId),[step,setStep]=useState(initialAccountId?"folder":"provider"),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const[local,setLocal]=useState({name:"",path:"",isPrimary:false}),[root,setRoot]=useState(null),[name,setName]=useState(""),[isPrimary,setIsPrimary]=useState(false),[siteQuery,setSiteQuery]=useState(""),[sites,setSites]=useState([]),[site,setSite]=useState(null),[drives,setDrives]=useState([]),[drive,setDrive]=useState(null);
 const selectedProvider=providers.find(x=>x.providerType===provider),providerAccounts=accounts.filter(x=>x.provider_type===provider),selectedAccount=accounts.find(x=>x.id===accountId);
 useEffect(()=>{if(initialAccountId&&initialProvider){setProvider(initialProvider);setAccountId(initialAccountId);setStep(initialProvider==="SHAREPOINT"?"sharepoint":"folder")}},[initialAccountId,initialProvider]);
 async function authorize(){setBusy(true);setError("");try{const r=await apiPost("/file-hub/cloud/authorize",{mainCompanySlug:slug,providerType:provider,returnPath:"/depolama/depolama-kaynaklar"});if(!r?.data?.authorizeUrl)throw new Error("Sağlayıcı giriş adresi alınamadı.");window.location.assign(r.data.authorizeUrl)}catch(e){setError(e?.message||"Hesap bağlantısı başlatılamadı.");setBusy(false)}}
 async function searchSites(){if(siteQuery.trim().length<2)return;setBusy(true);setError("");try{const r=await apiGet("/file-hub/cloud/sharepoint/sites",{mainCompanySlug:slug,accountId,q:siteQuery});setSites(r?.data||[])}catch(e){setError(e?.message||"SharePoint siteleri alınamadı.")}finally{setBusy(false)}}
 async function chooseSite(row){setSite(row);setBusy(true);setError("");try{const r=await apiGet("/file-hub/cloud/sharepoint/drives",{mainCompanySlug:slug,accountId,siteId:row.id});setDrives(r?.data||[])}catch(e){setError(e?.message||"Belge kitaplıkları alınamadı.")}finally{setBusy(false)}}
 async function saveCloud(){if(!root)return;setBusy(true);setError("");try{await apiPost("/file-hub/cloud/connections",{mainCompanySlug:slug,accountId,rootFolderId:root.id,rootFolderName:root.name,driveId:drive?.id||"",name:name.trim()||`${providerLabel(provider)} · ${root.name}`,isPrimary});await onSaved?.();onClose()}catch(e){setError(e?.message||"Bulut servisi kaydedilemedi.")}finally{setBusy(false)}}
 async function saveLocal(){if(!local.name.trim()||!local.path.trim())return setError("Servis adı ve Windows / ağ klasörü zorunludur.");setBusy(true);setError("");try{await apiPost("/file-hub/connections",{mainCompanySlug:slug,providerType:provider,name:local.name.trim(),localRootPath:local.path.trim(),syncMode:"AGENT",isActive:true,isPrimary:local.isPrimary,connectionStatus:"UNKNOWN"});await onSaved?.();onClose()}catch(e){setError(e?.message||"Yerel servis kaydedilemedi.")}finally{setBusy(false)}}
 return <div className="storage-drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><aside className="storage-drawer"><header><div><small>DEPOLAMA SERVİSİ</small><h3>{provider?providerLabel(provider):"Servis Ekle"}</h3></div><button type="button" onClick={onClose}>×</button></header><div className="storage-drawer-body">{error?<div className="storage-notice bad">{error}</div>:null}
 {step==="provider"?<><div><strong>Depolama türünü seç</strong><p>Bulut servisleri hesabınıza doğrudan bağlanır. Yerel/NAS bağlantılarında KY File Agent kullanılır.</p></div><div className="storage-provider-list">{providers.map(item=><button type="button" className="storage-provider-card" key={item.providerType} onClick={()=>{setProvider(item.providerType);setStep(isCloud(item.providerType)?"account":"local")}}><strong>{item.label}</strong><span>{item.mode==="CLOUD_API"?"Doğrudan API · klasör ağacı · bulut senkron":"Yerel Agent · Windows / ağ klasörü"}</span><em>{item.configured?"Kullanılabilir":"OAuth yapılandırması gerekli"}</em></button>)}</div></>:null}
 {step==="account"?<><div><strong>{providerLabel(provider)} hesabı</strong><p>Bir kez hesap girişini yapın. Sonrasında seçtiğiniz klasörler doğrudan kullanılır.</p></div>{providerAccounts.map(a=><div className="storage-account-row" key={a.id}><div><strong>{a.display_name||a.account_email}</strong><small>{a.account_email}</small></div><button className="storage-secondary" type="button" onClick={()=>{setAccountId(a.id);setStep(provider==="SHAREPOINT"?"sharepoint":"folder")}}>Bu Hesabı Kullan</button></div>)}<button type="button" className="storage-primary" disabled={busy||!selectedProvider?.configured} onClick={authorize}>{busy?"Bağlantı açılıyor...":"+ Hesabı Bağla"}</button>{!selectedProvider?.configured?<div className="storage-notice bad">Bu sağlayıcının OAuth Client ID / Secret ayarı production ortamında henüz tanımlı değil.</div>:null}</>:null}
 {step==="sharepoint"?<><div><strong>SharePoint sitesi ve belge kitaplığı</strong><p>Siteyi bulun, sonra kullanılacak belge kitaplığını seçin.</p></div><div className="storage-field"><label>Site ara</label><div style={{display:"flex",gap:8}}><input value={siteQuery} onChange={e=>setSiteQuery(e.target.value)} placeholder="Örn. Hakan Emprime"/><button className="storage-secondary" type="button" onClick={searchSites}>Ara</button></div></div><div className="storage-site-results">{sites.map(row=><button type="button" key={row.id} onClick={()=>chooseSite(row)}><strong>{row.displayName||row.name}</strong><small>{row.webUrl}</small></button>)}</div>{site?<div className="storage-field"><label>Belge kitaplığı</label><select value={drive?.id||""} onChange={e=>setDrive(drives.find(x=>x.id===e.target.value)||null)}><option value="">Seçin</option>{drives.map(row=><option value={row.id} key={row.id}>{row.name}</option>)}</select></div>:null}{drive?<button className="storage-primary" type="button" onClick={()=>setStep("folder")}>Klasörleri Aç</button>:null}</>:null}
 {step==="folder"&&accountId?<><div><strong>Ana klasörü seç</strong><p>{selectedAccount?.account_email} hesabındaki klasörler doğrudan sağlayıcıdan geliyor.</p></div><FolderBrowser slug={slug} accountId={accountId} driveId={drive?.id||""} onSelect={v=>{setRoot(v);setName(x=>x||`${providerLabel(provider)} · ${v.name}`)}}/>{root?<><div className="storage-notice ok">Seçilen kök: <strong>{root.name}</strong>{root.path?` / ${root.path}`:""}</div><div className="storage-form-grid"><label>Servis adı<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Varsayılan servis<select value={isPrimary?"yes":"no"} onChange={e=>setIsPrimary(e.target.value==="yes")}><option value="no">Hayır</option><option value="yes">Evet</option></select></label></div><button type="button" className="storage-primary" disabled={busy} onClick={saveCloud}>{busy?"Kaydediliyor...":"Servisi Kaydet ve Bağla"}</button></>:null}</>:null}
 {step==="local"?<><div><strong>{providerLabel(provider)} ekle</strong><p>Bu servis KY File Agent üzerinden izlenir ve bulut servisleriyle birlikte çalışabilir.</p></div><div className="storage-form-grid"><label>Servis adı<input value={local.name} onChange={e=>setLocal(x=>({...x,name:e.target.value}))} placeholder={provider==="NAS"?"Fabrika NAS":"Ofis Yerel Dosyalar"}/></label><label>Windows / Ağ yolu<input value={local.path} onChange={e=>setLocal(x=>({...x,path:e.target.value}))} placeholder={provider==="NAS"?"\\\\SUNUCU\\KYERP":"D:\\KYERP"}/></label><label>Varsayılan<select value={local.isPrimary?"yes":"no"} onChange={e=>setLocal(x=>({...x,isPrimary:e.target.value==="yes"}))}><option value="no">Hayır</option><option value="yes">Evet</option></select></label></div><button type="button" className="storage-primary" disabled={busy} onClick={saveLocal}>{busy?"Kaydediliyor...":"Yerel Servisi Ekle"}</button></>:null}
 </div></aside></div>;
}
function LocalPath({onSelect}){const[path,setPath]=useState("");return <><div className="storage-field"><label>Servis köküne göre alt klasör</label><input value={path} onChange={e=>setPath(e.target.value)} placeholder="Örn. DESEN/Modeller"/></div><button className="storage-primary" type="button" onClick={()=>onSelect({id:"",name:path||"Kök",path})}>Bu Klasörü Seç</button></>}
function BindingFolderPicker({slug,connection,accounts,onClose,onSelect}){const meta=connection?.metadata||{},account=accounts.find(a=>a.provider_type===connection.provider_type&&(!meta.accountEmail||a.account_email===meta.accountEmail));if(!isCloud(connection?.provider_type))return <div className="storage-drawer-backdrop"><aside className="storage-drawer"><header><h3>Yerel Klasör Yolu</h3><button onClick={onClose}>×</button></header><div className="storage-drawer-body"><p>Yerel/NAS servisinde klasör yolu servis köküne göre göreli yazılır.</p><LocalPath onSelect={onSelect}/></div></aside></div>;return <div className="storage-drawer-backdrop"><aside className="storage-drawer"><header><h3>{connection.name} · Klasör Seç</h3><button onClick={onClose}>×</button></header><div className="storage-drawer-body">{account?<FolderBrowser slug={slug} accountId={account.id} driveId={meta.driveId||""} initialRootId={connection.remote_root_id||"root"} initialRootName={connection.remote_root_name||"Ana Klasör"} onSelect={onSelect}/>:<div className="storage-notice bad">Bu servisin bağlı bulut hesabı bulunamadı. Servisi yeniden bağlayın.</div>}</div></aside></div>}
function ServiceCard({row,loading,onSync,onDisconnect}){const meta=row.metadata||{};return <article className="storage-service"><div className="storage-service-head"><div><strong>{row.name}</strong><small>{providerLabel(row.provider_type)}{meta.accountEmail?` · ${meta.accountEmail}`:""}</small></div><span className={`storage-status ${row.connection_status==="CONNECTED"?"ok":row.connection_status==="ERROR"?"bad":""}`}>{statusLabel(row.connection_status)}</span></div><div className="storage-service-path">{row.sync_mode==="CLOUD_API"?`☁ ${row.remote_root_name||"Ana Klasör"}`:`🖥 ${row.local_root_path||"Yol tanımsız"}`}</div><div style={{fontSize:11,color:"#728096"}}>Son senkron: {formatDate(row.last_sync_at)}{row.last_error?` · ${row.last_error}`:""}</div><div className="storage-service-actions">{row.sync_mode==="CLOUD_API"?<button disabled={loading} type="button" onClick={()=>onSync(row)}>↻ Şimdi Senkronize Et</button>:<span className="storage-status">Agent</span>}{row.sync_mode==="CLOUD_API"?<button type="button" onClick={()=>onDisconnect(row)}>Bağlantıyı Kes</button>:null}</div></article>}

export default function AdminStorageCenter({activeMainCompany,activeTab,showToolbar=true}){
 const[tab,setTab]=useState(ROUTE_TO_TAB[activeTab]||"overview"),[overview,setOverview]=useState({}),[connections,setConnections]=useState([]),[bindings,setBindings]=useState([]),[files,setFiles]=useState([]),[providers,setProviders]=useState([]),[accounts,setAccounts]=useState([]),[credential,setCredential]=useState(null),[newSecret,setNewSecret]=useState(null),[wizard,setWizard]=useState(null),[folderPicker,setFolderPicker]=useState(null),[binding,setBinding]=useState({moduleCode:"DESEN",purposeCode:"MODEL_IMAGE",storageConnectionId:"",rootPath:"",readEnabled:true,writeEnabled:true,syncEnabled:true}),[search,setSearch]=useState(""),[statusFilter,setStatusFilter]=useState(""),[loading,setLoading]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");
 const slug=activeMainCompany?.slug||"mecit-hakan",companyName=activeMainCompany?.name||activeMainCompany?.title||slug,tenantParams=useMemo(()=>({mainCompanySlug:slug}),[slug]);
 useEffect(()=>{const mapped=ROUTE_TO_TAB[activeTab];if(mapped)setTab(mapped)},[activeTab]);
 const refresh=useCallback(async()=>{setLoading(true);setError("");try{const[o,c,b,f,p,a,cred]=await Promise.all([apiGet("/file-hub/overview",tenantParams),apiGet("/file-hub/connections",tenantParams),apiGet("/file-hub/bindings",tenantParams),apiGet("/file-hub/files",{...tenantParams,q:search||undefined,status:statusFilter||undefined,take:300}),apiGet("/file-hub/cloud/providers",tenantParams).catch(()=>({data:[]})),apiGet("/file-hub/cloud/accounts",tenantParams).catch(()=>({data:[]})),apiGet("/file-hub/agent-credential",tenantParams).catch(()=>null)]);setOverview(o?.data||{});setConnections(c?.data||[]);setBindings(b?.data||[]);setFiles(f?.data||[]);setProviders(p?.data||[]);setAccounts(a?.data||[]);setCredential(cred?.data||null)}catch(e){setError(e?.message||"Depolama Merkezi yüklenemedi.")}finally{setLoading(false)}},[search,statusFilter,tenantParams]);
 useEffect(()=>{refresh()},[refresh]);useEffect(()=>{setBinding(x=>({...x,storageConnectionId:x.storageConnectionId||connections.find(row=>row.isActive)?.id||""}))},[connections]);
 useEffect(()=>{const p=new URLSearchParams(window.location.search),accountId=p.get("storageAccount"),provider=p.get("storageProvider"),oauthError=p.get("storageError");if(oauthError)setError(`Bulut hesap bağlantısı tamamlanamadı: ${oauthError}`);if(accountId&&provider){setMessage("Hesap bağlandı. Şimdi ana klasörü seçin.");setWizard({accountId,provider})}if(accountId||oauthError)window.history.replaceState({},"",window.location.pathname)},[]);
 const activeConnections=connections.filter(row=>row.isActive!==false),cloudConnections=activeConnections.filter(row=>row.sync_mode==="CLOUD_API"),localConnections=activeConnections.filter(row=>row.sync_mode!=="CLOUD_API"),onlineAgents=(overview.agents||[]).filter(row=>row.last_seen_at&&Date.now()-new Date(row.last_seen_at).getTime()<5*60*1000);
 async function syncConnection(row){setLoading(true);setError("");setMessage("");try{const r=await apiPost(`/file-hub/cloud/connections/${row.id}/sync`,{mainCompanySlug:slug});const d=r?.data||{};setMessage(`${row.name}: ${d.files||0} dosya ve ${d.folders||0} klasör tarandı${d.truncated?". Limit nedeniyle devam taraması gerekebilir.":"."}`);await refresh()}catch(e){setError(e?.message||"Bulut senkronizasyonu başarısız.")}finally{setLoading(false)}}
 async function disconnect(row){if(!window.confirm(`${row.name} bağlantısı pasif yapılsın mı? Dosya indeks kayıtları silinmez.`))return;setLoading(true);try{await apiFetch(`/file-hub/cloud/connections/${row.id}`,{method:"DELETE",body:{mainCompanySlug:slug}});setMessage("Servis bağlantısı pasif yapıldı.");await refresh()}catch(e){setError(e?.message||"Bağlantı kesilemedi.")}finally{setLoading(false)}}
 async function saveBinding(){if(!binding.storageConnectionId)return setError("Önce depolama servisini seçin.");setLoading(true);setError("");try{await apiFetch("/file-hub/bindings",{method:"PUT",body:{...binding,mainCompanySlug:slug}});setMessage(`${moduleLabel(binding.moduleCode)} / ${purposeLabel(binding.purposeCode)} klasörü bağlandı.`);await refresh()}catch(e){setError(e?.message||"Klasör ataması kaydedilemedi.")}finally{setLoading(false)}}
 async function rotateCredential(){setLoading(true);setNewSecret(null);try{const r=await apiPost("/file-hub/agent-credential/rotate",{mainCompanySlug:slug,label:"KY File Agent"});setNewSecret(r?.data||r);setMessage("Yerel/NAS Agent anahtarı yenilendi. Anahtar yalnız bu ekranda bir kez gösterilir.");await refresh()}catch(e){setError(e?.message||"Agent anahtarı yenilenemedi.")}finally{setLoading(false)}}
 async function copy(v){try{await navigator.clipboard.writeText(String(v||""));setMessage("Agent anahtarı panoya kopyalandı.")}catch{setError("Anahtar kopyalanamadı.")}}
 return <div className="admpro-page storage-page-v2"><section className="storage-company-banner"><div><small>KY ERP · FILE HUB · AKTİF FİRMA</small><h2>{companyName} — Depolama Merkezi</h2><p style={{margin:"6px 0 0",color:"#65758b"}}>Bulut hesabını bağla, ana klasörü seç ve bölüm klasörlerini doğrudan o servis içinden ata. Yerel/NAS yalnız ihtiyaç varsa ek servis olarak çalışır.</p></div><div className="storage-company-pill">Firma: {companyName}</div></section><div className="storage-toolbar-v2">{showToolbar?<div className="storage-tabs-v2">{TABS.map(([k,l])=><button type="button" key={k} className={tab===k?"active":""} onClick={()=>setTab(k)}>{l}</button>)}</div>:<div/>}<div style={{display:"flex",gap:8}}><button className="storage-secondary" type="button" disabled={loading} onClick={refresh}>Yenile</button><button className="storage-primary" type="button" onClick={()=>{setTab("connections");setWizard({})}}>+ Servis Ekle</button></div></div>{message?<div className="storage-notice ok">{message}</div>:null}{error?<div className="storage-notice bad">{error}</div>:null}
 {tab==="overview"?<><div className="storage-stats-v2"><div className="storage-stat-v2"><span>Bağlı Servis</span><strong>{activeConnections.length}</strong><small>{cloudConnections.length} bulut · {localConnections.length} yerel/NAS</small></div><div className="storage-stat-v2"><span>Dosya İndeksi</span><strong>{overview.fileCount||0}</strong><small>Tek File Hub kimliği</small></div><div className="storage-stat-v2"><span>Klasör Ataması</span><strong>{bindings.length}</strong><small>Bölüm / dosya hedefi</small></div><div className="storage-stat-v2"><span>Yerel Agent</span><strong>{onlineAgents.length}</strong><small>Yalnız yerel/NAS için</small></div></div><section className="storage-card-v2"><h3>{companyName} Depolama Haritası</h3><p>Google Drive, OneDrive, SharePoint, yerel klasör ve NAS aynı File Hub altında birlikte kullanılabilir.</p>{activeConnections.length?<div className="storage-service-grid">{activeConnections.map(row=><ServiceCard key={row.id} row={row} loading={loading} onSync={syncConnection} onDisconnect={disconnect}/>)}</div>:<div className="storage-empty-v2"><strong>Henüz servis bağlı değil</strong><p>İlk servisi ekleyin. Bulut hesabında ana klasörü seçtiğiniz anda alt klasörler KY ERP içinde görünür.</p><button className="storage-primary" type="button" onClick={()=>setWizard({})}>+ İlk Servisi Ekle</button></div>}</section></>:null}
 {tab==="connections"?<section className="storage-card-v2"><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:12}}><div><h3>Bağlı Servisler</h3><p>Hesap ve ana klasör bazlı gerçek bağlantılar. Sağlayıcı seçme formu yalnız “Servis Ekle” içinde açılır.</p></div><button className="storage-primary" type="button" onClick={()=>setWizard({})}>+ Servis Ekle</button></div>{activeConnections.length?<div className="storage-service-grid">{activeConnections.map(row=><ServiceCard key={row.id} row={row} loading={loading} onSync={syncConnection} onDisconnect={disconnect}/>)}</div>:<div className="storage-empty-v2"><strong>{companyName} için servis yok</strong><p>Google Drive veya OneDrive hesabını bağlayıp ana klasörü seçerek başlayın.</p></div>}</section>:null}
 {tab==="bindings"?<div className="storage-binding-layout"><section className="storage-card-v2"><h3>Bölüm → Klasör Bağla</h3><p>Klasör yolu yazmak yerine bağlı servisi seçin ve gerçek klasör ağacından hedefi tıklayın.</p><div className="storage-form-grid"><label>Bölüm<select value={binding.moduleCode} onChange={e=>setBinding(x=>({...x,moduleCode:e.target.value}))}>{MODULES.map(x=><option key={x} value={x}>{moduleLabel(x)}</option>)}</select></label><label>Dosya türü<select value={binding.purposeCode} onChange={e=>setBinding(x=>({...x,purposeCode:e.target.value}))}>{PURPOSES.map(x=><option key={x} value={x}>{purposeLabel(x)}</option>)}</select></label><label style={{gridColumn:"1/-1"}}>Depolama servisi<select value={binding.storageConnectionId} onChange={e=>setBinding(x=>({...x,storageConnectionId:e.target.value,rootPath:""}))}><option value="">Servis seçin</option>{activeConnections.map(row=><option key={row.id} value={row.id}>{row.name} · {providerLabel(row.provider_type)}</option>)}</select></label></div><div className="storage-service-path">Seçilen klasör: <strong>{binding.rootPath||"Henüz seçilmedi"}</strong></div><div style={{display:"flex",gap:8,marginTop:10}}><button className="storage-secondary" type="button" disabled={!binding.storageConnectionId} onClick={()=>setFolderPicker(connections.find(x=>x.id===binding.storageConnectionId)||null)}>📁 Klasör Seç</button><button className="storage-primary" type="button" disabled={!binding.storageConnectionId} onClick={saveBinding}>Atamayı Kaydet</button></div></section><section className="storage-card-v2"><h3>Aktif Atamalar</h3><p>{companyName} bölümlerinin hangi gerçek klasöre yazdığı burada görünür.</p>{bindings.length?<div className="storage-binding-list">{bindings.map(row=><div className="storage-binding-row" key={row.id}><div><strong>{moduleLabel(row.module_code)}</strong><small>{purposeLabel(row.purpose_code)}</small></div><div><strong>{row.connection_name}</strong><small>{providerLabel(row.provider_type)}</small></div><div><strong>{row.root_path||"Servis kökü"}</strong><small>{row.syncEnabled===false?"Senkron kapalı":"Senkron açık"}</small></div></div>)}</div>:<div className="storage-empty-v2"><strong>Henüz klasör ataması yok</strong><p>Önce servis ekleyin, sonra Desen/Boyahane/e‑Belge/Muhasebe gibi bölümleri gerçek klasörlere bağlayın.</p></div>}</section></div>:null}
 {tab==="files"?<section className="storage-card-v2"><h3>Dosya İndeksi</h3><p>Tüm servislerdeki dosyaların ortak KY ERP indeksi.</p><div className="storage-form-grid" style={{marginBottom:10}}><label>Arama<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Dosya adı / yol"/></label><label>Durum<select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Tümü</option><option value="AVAILABLE">Mevcut</option><option value="MISSING">Kaynakta Yok</option></select></label></div><div style={{overflow:"auto"}}><table className="storage-file-table"><thead><tr><th>Dosya</th><th>Servis</th><th>Yol</th><th>Boyut</th><th>Durum</th><th>Son Görülme</th></tr></thead><tbody>{files.map(row=><tr key={row.id}><td><strong>{row.file_name}</strong></td><td>{row.connection_name||"-"}</td><td>{row.relative_path||"-"}</td><td>{formatBytes(row.size_bytes)}</td><td>{statusLabel(row.status)}</td><td>{formatDate(row.last_seen_at)}</td></tr>)}</tbody></table>{!files.length?<div className="storage-empty-v2"><strong>İndeks boş</strong><p>Bulut servisinde “Şimdi Senkronize Et” dediğinizde dosyalar burada görünür.</p></div>:null}</div></section>:null}
 {tab==="sync"?<section className="storage-card-v2"><h3>Senkronizasyon</h3><p>Bulut servisleri doğrudan API ile; yerel/NAS servisleri KY File Agent ile izlenir.</p><div className="storage-service-grid">{activeConnections.map(row=><ServiceCard key={row.id} row={row} loading={loading} onSync={syncConnection} onDisconnect={disconnect}/>)}</div>{localConnections.length?<div className="storage-agent-box"><strong>Yerel / NAS Agent</strong><p>Yalnız yerel dosya sistemi için gereklidir. Google Drive/OneDrive/SharePoint doğrudan API kullanır.</p><div>Kimlik: <strong>{credential?.keyId||"Henüz oluşturulmadı"}</strong></div><button className="storage-secondary" type="button" onClick={rotateCredential}>{credential?.keyId?"Agent Anahtarını Yenile":"Agent Anahtarı Oluştur"}</button>{newSecret?.secret?<><code>{newSecret.secret}</code><button className="storage-secondary" type="button" onClick={()=>copy(newSecret.secret)}>Kopyala</button></>:null}</div>:null}</section>:null}
 {tab==="logs"?<section className="storage-card-v2"><h3>File Hub Olayları</h3><p>Servis, senkron ve indeks hareketleri.</p><div className="storage-binding-list">{(overview.recentEvents||[]).map(row=><div className="storage-binding-row" key={row.id}><div><strong>{eventLabel(row.event_type)}</strong><small>{formatDate(row.created_at)}</small></div><div><strong>{row.actor_type||"SYSTEM"}</strong><small>{row.device_name||"-"}</small></div><div><small>{row.details||""}</small></div></div>)}</div></section>:null}
 {wizard?<ServiceWizard slug={slug} providers={providers.length?providers:[{providerType:"GOOGLE_DRIVE",label:"Google Drive",configured:false,mode:"CLOUD_API"},{providerType:"ONEDRIVE",label:"Microsoft OneDrive",configured:false,mode:"CLOUD_API"},{providerType:"SHAREPOINT",label:"Microsoft SharePoint",configured:false,mode:"CLOUD_API"},{providerType:"LOCAL_FOLDER",label:"Yerel Klasör",configured:true,mode:"AGENT"},{providerType:"NAS",label:"NAS / Ağ Klasörü",configured:true,mode:"AGENT"}]} accounts={accounts} initialAccountId={wizard.accountId||""} initialProvider={wizard.provider||""} onClose={()=>setWizard(null)} onSaved={refresh}/>:null}
 {folderPicker?<BindingFolderPicker slug={slug} connection={folderPicker} accounts={accounts} onClose={()=>setFolderPicker(null)} onSelect={v=>{setBinding(x=>({...x,rootPath:v.path||v.name||""}));setFolderPicker(null)}}/>:null}</div>;
}
