import { useCallback, useEffect, useMemo, useState } from "react";
import {
  createBackup,
  downloadBackupSql,
  generateBackupSql,
  getLogs,
  listBackups,
  listSecurityAuditLog,
  listSessionHistory,
  restoreBackup,
} from "../../services/adminApi";
import "./AdminManagement.css";

function rowsOf(value){const data=value?.data??value;if(Array.isArray(data))return data;if(Array.isArray(data?.items))return data.items;return []}
function dateText(value){if(!value)return"-";const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleString("tr-TR")}
function stringifyDetail(value){if(!value)return"";if(typeof value==="string")return value;try{return JSON.stringify(value)}catch{return String(value)}}
function mirrorText(row){const mirror=row?.archiveMirror||{};const completed=Array.isArray(mirror.completed)?mirror.completed:[];const failed=Array.isArray(mirror.failed)?mirror.failed:[];if(!completed.length&&!failed.length)return"Yalnız R2";const ok=completed.map(x=>x.provider).join(", ");const bad=failed.map(x=>x.provider).join(", ");return [ok?`Arşiv: ${ok}`:"",bad?`Hata: ${bad}`:""].filter(Boolean).join(" · ")}
function sqlName(row,slug){const safe=String(row?.mainCompanySlug||slug||"firma").replace(/[^a-zA-Z0-9._-]+/g,"-");const date=String(row?.createdAt||row?.completedAt||new Date().toISOString()).slice(0,10);return `KYERP-${safe}-${date}.sql`}

export default function AdminBackupLogs({activeMainCompany}){
 const [tab,setTab]=useState("BACKUP"),[logs,setLogs]=useState([]),[security,setSecurity]=useState([]),[sessions,setSessions]=useState([]),[backups,setBackups]=useState([]),[lastBackup,setLastBackup]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("Yedekleme ve log kayıtları hazırlanıyor..."),[search,setSearch]=useState(""),[restore,setRestore]=useState({backup:null,password:"",confirmText:""});
 const companyParams=useMemo(()=>({mainCompanyId:activeMainCompany?.id||"",mainCompanySlug:activeMainCompany?.slug||""}),[activeMainCompany?.id,activeMainCompany?.slug]);
 const load=useCallback(async()=>{if(!companyParams.mainCompanyId&&!companyParams.mainCompanySlug){setMessage("Önce aktif ana firma seçin.");return}setBusy(true);const [backupJob,logJob,secJob,sesJob]=await Promise.allSettled([listBackups({...companyParams,_ts:Date.now()}),getLogs({limit:250,_ts:Date.now()}),listSecurityAuditLog(250),listSessionHistory(250)]);if(backupJob.status==="fulfilled")setBackups(rowsOf(backupJob.value));if(logJob.status==="fulfilled")setLogs(rowsOf(logJob.value));if(secJob.status==="fulfilled")setSecurity(rowsOf(secJob.value));if(sesJob.status==="fulfilled")setSessions(rowsOf(sesJob.value));const failed=[backupJob,logJob,secJob,sesJob].filter(x=>x.status==="rejected").length;setMessage(failed?`${failed} yönetim kaynağı yanıt vermedi; alınan kayıtlar gösteriliyor.`:"Yedekleme ve denetim kayıtları güncel.");setBusy(false)},[companyParams]);
 useEffect(()=>{load()},[load]);
 async function backupNow(){if(!companyParams.mainCompanySlug)return setMessage("Aktif ana firma kısa kodu bulunamadı.");setBusy(true);try{const result=await createBackup({...companyParams,reason:"MANUAL_ADMIN_BACKUP",requestedAt:new Date().toISOString()});let complete=result;try{const sql=await generateBackupSql(result.id,{...companyParams});complete={...result,...sql};setMessage(`Tam firma yedeği tamamlandı. ${Number(result?.totalRows||0)} satır, ${Number(result?.totalFiles||0)} dosya ve SQL arşivi hazır.`)}catch(sqlError){setMessage(`R2/D1 yedeği tamamlandı ancak SQL dosyası hazırlanamadı: ${sqlError?.message||"SQL yedek hatası"}. Bu yedek geri yüklenebilir; SQL üretimini tekrar deneyin.`)}setLastBackup(complete);await load()}catch(error){setMessage(`Hata: ${error?.message||"Yedekleme tamamlanamadı."}`)}finally{setBusy(false)}}
 async function prepareOrDownloadSql(row,download=true){if(!row?.id)return;setBusy(true);try{let current=row;if(!row.sqlKey)current=await generateBackupSql(row.id,{...companyParams});if(download)await downloadBackupSql(row.id,sqlName(current,companyParams.mainCompanySlug));setMessage(download?"Firma SQL yedeği indirilmeye hazırlandı.":"Firma SQL yedeği R2 üzerinde hazırlandı.");await load()}catch(error){setMessage(`Hata: ${error?.message||"SQL yedek işlemi tamamlanamadı."}`)}finally{setBusy(false)}}
 async function restoreNow(){if(!restore.backup)return; if(!restore.password.trim())return setMessage("Geri yükleme için yönetici şifresi zorunludur.");if(restore.confirmText.trim().toLocaleUpperCase("tr-TR").replace(/İ/g,"I")!=="GERI YUKLE")return setMessage("Onay alanına GERI YUKLE yazın.");setBusy(true);try{const result=await restoreBackup(restore.backup.id,{...companyParams,adminPassword:restore.password,confirmText:restore.confirmText});setMessage(`Geri yükleme tamamlandı. İşlem öncesi güvenlik yedeği: ${result?.safetyBackupId||"oluşturuldu"}.`);setRestore({backup:null,password:"",confirmText:""});await load()}catch(error){setMessage(`Hata: ${error?.message||"Geri yükleme tamamlanamadı."}`)}finally{setBusy(false)}}
 const term=search.trim().toLocaleLowerCase("tr-TR");
 const visibleLogs=useMemo(()=>logs.filter(r=>!term||stringifyDetail(r).toLocaleLowerCase("tr-TR").includes(term)),[logs,term]);
 const visibleSecurity=useMemo(()=>security.filter(r=>!term||`${r.action||""} ${r.actorName||""} ${r.targetName||""} ${r.ipAddress||""}`.toLocaleLowerCase("tr-TR").includes(term)),[security,term]);
 const visibleSessions=useMemo(()=>sessions.filter(r=>!term||`${r.fullName||r.username||""} ${r.closureReason||""} ${r.deviceLabel||""} ${r.ipAddress||""}`.toLocaleLowerCase("tr-TR").includes(term)),[sessions,term]);
 return <div className="admpro-page">
 <header className="admpro-head"><div><span className="admpro-kicker">YÖNETİM / YEDEKLEME & DENETİM</span><h2>Yedekleme & Denetim Logları</h2><p>Firma bazlı D1 + R2 + SQL yedeği, güvenli geri dönüş, sistem olayları ve oturum geçmişi.</p></div><div className="admpro-actions"><button type="button" onClick={load} disabled={busy}>Yenile</button><button type="button" className="primary" onClick={backupNow} disabled={busy}>{busy?"İşleniyor...":"Şimdi Tam Yedek Al"}</button></div></header>
 <div className={`admpro-notice ${message.startsWith("Hata")?"error":message.includes("yanıt vermedi")||message.includes("hazırlanamadı")?"warn":"success"}`}>{message}</div>
 <section className="admpro-stats"><div className="admpro-stat"><span>Firma Yedeği</span><strong>{backups.length}</strong><small>{activeMainCompany?.name||activeMainCompany?.slug||"Firma seçilmedi"}</small></div><div className="admpro-stat"><span>Sistem Logu</span><strong>{logs.length}</strong><small>Son alınan kayıtlar</small></div><div className="admpro-stat"><span>Güvenlik Olayı</span><strong>{security.length}</strong><small>Giriş ve yönetim olayları</small></div><div className="admpro-stat"><span>Oturum Geçmişi</span><strong>{sessions.length}</strong><small>Aktif ve kapanmış oturumlar</small></div></section>
 <nav className="admpro-section-tabs"><button className={tab==="BACKUP"?"active":""} onClick={()=>setTab("BACKUP")}>Yedekleme</button><button className={tab==="SYSTEM"?"active":""} onClick={()=>setTab("SYSTEM")}>Sistem Logu</button><button className={tab==="SECURITY"?"active":""} onClick={()=>setTab("SECURITY")}>Güvenlik Logu</button><button className={tab==="SESSIONS"?"active":""} onClick={()=>setTab("SESSIONS")}>Oturum Geçmişi</button></nav>
 {tab!=="BACKUP"?<div className="admpro-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Log, kullanıcı, işlem veya IP ara"/></div>:null}
 {tab==="BACKUP"?<><section className="admpro-grid-2"><div className="admpro-card"><div className="admpro-card-head"><div><h3>Firma Bazlı Tam Yedek</h3><p>D1 tenant verileri, ilgili R2 dosyaları, manifest ve ayrıca taşınabilir SQL dosyası birlikte hazırlanır.</p></div></div><div className="admpro-notice success">Ana yedek R2 üzerindedir. SQL dosyası aynı yedeğin veri kopyasıdır. Google Drive/OneDrive seçili ve bağlıysa ayrıca dış arşiv kopyası oluşturulur.</div><div className="admpro-actions" style={{justifyContent:"flex-start",marginTop:12}}><button className="primary" onClick={backupNow} disabled={busy}>Yeni Tam Yedek Oluştur</button></div></div><div className="admpro-card"><div className="admpro-card-head"><div><h3>Son İşlem Sonucu</h3><p>Bu ekran oturumunda oluşturulan son yedek.</p></div></div>{lastBackup?<div className="admpro-list"><div className="admpro-list-item"><div><strong>{lastBackup.id||"Yedek oluşturuldu"}</strong><small>{dateText(lastBackup.createdAt||lastBackup.completedAt)} · {lastBackup.totalRows||0} satır · {lastBackup.totalFiles||0} dosya · {mirrorText(lastBackup)}</small><small className="admpro-code">{lastBackup.sqlKey?`SQL: ${lastBackup.sqlKey}`:lastBackup.manifestKey||"Manifest yolu raporlanmadı"}</small></div><span className={`admpro-badge ${lastBackup.sqlKey?"ok":"warn"}`}>{lastBackup.sqlKey?"SQL Hazır":"R2 Hazır"}</span></div></div>:<div className="admpro-empty">Bu oturumda yeni yedek alınmadı.</div>}</div></section>
 <section className="admpro-card"><div className="admpro-card-head"><div><h3>Yedek Geçmişi</h3><p>Geri yükleme başlamadan önce sistem otomatik yeni bir güvenlik yedeği daha alır.</p></div><span className="admpro-badge">{backups.length} yedek</span></div><div className="admpro-table"><table><thead><tr><th>Tarih</th><th>Firma</th><th>Veri</th><th>Dosya</th><th>Dış Arşiv</th><th>SQL</th><th>Manifest</th><th>İşlem</th></tr></thead><tbody>{backups.map(r=><tr key={r.id}><td>{dateText(r.createdAt||r.completedAt)}</td><td><strong>{r.companyName||r.mainCompanySlug||"-"}</strong><small>{r.reason||"-"}</small></td><td>{Number(r.totalRows||0).toLocaleString("tr-TR")} satır</td><td>{Number(r.totalFiles||0).toLocaleString("tr-TR")}</td><td>{mirrorText(r)}</td><td>{r.sqlKey?<button onClick={()=>prepareOrDownloadSql(r,true)} disabled={busy}>SQL İndir</button>:<button onClick={()=>prepareOrDownloadSql(r,false)} disabled={busy}>SQL Hazırla</button>}</td><td className="admpro-code">{r.manifestKey||"-"}</td><td><button className="danger" onClick={()=>setRestore({backup:r,password:"",confirmText:""})}>Geri Yükle</button></td></tr>)}{!backups.length?<tr><td colSpan="8">Bu ana firma için henüz yedek kaydı yok.</td></tr>:null}</tbody></table></div></section>
 {restore.backup?<section className="admpro-card"><div className="admpro-card-head"><div><h3>Geri Yükleme Doğrulaması</h3><p>{dateText(restore.backup.createdAt)} tarihli yedek aktif firmaya geri yüklenecek.</p></div><button onClick={()=>setRestore({backup:null,password:"",confirmText:""})}>İptal</button></div><div className="admpro-notice warn">Bu işlem mevcut firma verisini değiştirir. Başlamadan önce sistem otomatik PRE_RESTORE güvenlik yedeği oluşturur. Güvenlik yedeği alınamazsa geri yükleme hiç başlamaz.</div><div className="admpro-form-grid" style={{marginTop:12}}><label>Yönetici Şifresi<input type="password" value={restore.password} onChange={e=>setRestore(o=>({...o,password:e.target.value}))}/></label><label>Onay Metni<input value={restore.confirmText} onChange={e=>setRestore(o=>({...o,confirmText:e.target.value}))} placeholder="GERI YUKLE"/></label></div><div className="admpro-actions" style={{justifyContent:"flex-start",marginTop:12}}><button className="danger" onClick={restoreNow} disabled={busy}>Güvenlik Yedeği Al ve Geri Yükle</button></div></section>:null}</>:null}
 {tab==="SYSTEM"?<section className="admpro-card"><div className="admpro-table"><table><thead><tr><th>Zaman</th><th>Seviye</th><th>Kaynak</th><th>Mesaj</th><th>Detay</th></tr></thead><tbody>{visibleLogs.map((r,i)=><tr key={r.id||i}><td>{dateText(r.createdAt||r.timestamp||r.time)}</td><td><span className="admpro-badge">{r.level||r.type||"INFO"}</span></td><td>{r.source||r.module||r.category||"Sistem"}</td><td>{r.message||r.action||r.title||"-"}</td><td className="admpro-code">{stringifyDetail(r.detail||r.data||"").slice(0,180)}</td></tr>)}{!visibleLogs.length?<tr><td colSpan="5">Sistem logu yok.</td></tr>:null}</tbody></table></div></section>:null}
 {tab==="SECURITY"?<section className="admpro-card"><div className="admpro-table"><table><thead><tr><th>Zaman</th><th>İşlem</th><th>Uygulayan</th><th>Hedef</th><th>IP</th><th>Detay</th></tr></thead><tbody>{visibleSecurity.map((r,i)=><tr key={r.id||i}><td>{dateText(r.createdAt)}</td><td><strong>{r.action||"-"}</strong></td><td>{r.actorName||"Sistem"}</td><td>{r.targetName||"-"}</td><td>{r.ipAddress||"-"}</td><td className="admpro-code">{stringifyDetail(r.detail).slice(0,180)}</td></tr>)}{!visibleSecurity.length?<tr><td colSpan="6">Güvenlik kaydı yok.</td></tr>:null}</tbody></table></div></section>:null}
 {tab==="SESSIONS"?<section className="admpro-card"><div className="admpro-table"><table><thead><tr><th>Kullanıcı</th><th>Durum</th><th>Giriş</th><th>Son Hareket</th><th>Kapanış</th><th>Cihaz / IP</th></tr></thead><tbody>{visibleSessions.map((r,i)=><tr key={r.id||i}><td><strong>{r.fullName||r.username||"-"}</strong></td><td><span className={`admpro-badge ${r.closureReason==="ACTIVE"?"ok":""}`}>{r.closureReason||"-"}</span></td><td>{dateText(r.createdAt)}</td><td>{dateText(r.lastSeenAt)}</td><td>{r.revokedAt?dateText(r.revokedAt):r.expiresAt?dateText(r.expiresAt):"-"}</td><td>{r.deviceLabel||"Tarayıcı"}<small>{r.ipAddress||""}</small></td></tr>)}{!visibleSessions.length?<tr><td colSpan="6">Oturum geçmişi yok.</td></tr>:null}</tbody></table></div></section>:null}
 </div>
}
