import { useCallback, useEffect, useMemo, useState } from "react";
import { apiGet, apiPatch, apiPost } from "../../utils/api";
import "./AdminManagement.css";

function rowsOf(value){const data=value?.data??value;if(Array.isArray(data))return data;if(Array.isArray(data?.items))return data.items;return []}
function dateText(value){if(!value)return"-";const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleString("tr-TR")}
const EMPTY_COMPANY={id:"",rawName:"",matchedCompanyId:"",sourceType:"MANUAL",isActive:true,note:""};
const EMPTY_PRODUCT={id:"",rawName:"",matchedProductId:"",sourceType:"MANUAL",isActive:true,note:""};

export default function AdminMappings({activeMainCompany}){
 const [tab,setTab]=useState("COMPANY"),[companyAliases,setCompanyAliases]=useState([]),[productAliases,setProductAliases]=useState([]),[companies,setCompanies]=useState([]),[products,setProducts]=useState([]),[companyForm,setCompanyForm]=useState(EMPTY_COMPANY),[productForm,setProductForm]=useState(EMPTY_PRODUCT),[search,setSearch]=useState(""),[showDeleted,setShowDeleted]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState("Eşleştirme merkezi hazırlanıyor...");
 const params=useMemo(()=>({mainCompanyId:activeMainCompany?.id||"",mainCompanySlug:activeMainCompany?.slug||""}),[activeMainCompany?.id,activeMainCompany?.slug]);
 const load=useCallback(async()=>{if(!params.mainCompanyId&&!params.mainCompanySlug){setMessage("Önce aktif ana firma seçin.");return}setBusy(true);const q={...params,includeDeleted:showDeleted};const [ca,pa,co,pr]=await Promise.allSettled([apiGet("/admin/company-aliases",q),apiGet("/admin/product-aliases",q),apiGet("/muhasebe/firma-kartlari",params),apiGet("/muhasebe/urunler",params)]);if(ca.status==="fulfilled")setCompanyAliases(rowsOf(ca.value));if(pa.status==="fulfilled")setProductAliases(rowsOf(pa.value));if(co.status==="fulfilled")setCompanies(rowsOf(co.value));if(pr.status==="fulfilled")setProducts(rowsOf(pr.value));const failed=[ca,pa,co,pr].filter(x=>x.status==="rejected").length;setMessage(failed?`${failed} eşleştirme kaynağı alınamadı; mevcut veriler korunuyor.`:"Firma ve ürün eşleştirmeleri güncel.");setBusy(false)},[params,showDeleted]);
 useEffect(()=>{load()},[load]);
 const term=search.trim().toLocaleLowerCase("tr-TR");
 const visibleCompany=companyAliases.filter(r=>!term||`${r.rawName||""} ${r.normalizedRawName||""} ${r.matchedCompanyName||""} ${r.note||""}`.toLocaleLowerCase("tr-TR").includes(term));
 const visibleProduct=productAliases.filter(r=>!term||`${r.rawName||""} ${r.normalizedRawName||""} ${r.matchedProductName||""} ${r.matchedProductCode||""} ${r.note||""}`.toLocaleLowerCase("tr-TR").includes(term));
 async function saveCompany(e){e.preventDefault();if(!companyForm.rawName.trim()||!companyForm.matchedCompanyId)return setMessage("Ham firma adı ve eşleşecek firma zorunludur.");setBusy(true);try{const body={...companyForm,...params};if(companyForm.id)await apiPatch(`/admin/company-aliases/${encodeURIComponent(companyForm.id)}`,body);else await apiPost("/admin/company-aliases",body);setCompanyForm(EMPTY_COMPANY);setMessage("Firma eşleştirmesi kaydedildi.");await load()}catch(err){setMessage(`Hata: ${err?.message||"Firma eşleştirmesi kaydedilemedi."}`)}finally{setBusy(false)}}
 async function saveProduct(e){e.preventDefault();if(!productForm.rawName.trim()||!productForm.matchedProductId)return setMessage("Ham ürün adı ve eşleşecek ürün zorunludur.");setBusy(true);try{const body={...productForm,...params};if(productForm.id)await apiPatch(`/admin/product-aliases/${encodeURIComponent(productForm.id)}`,body);else await apiPost("/admin/product-aliases",body);setProductForm(EMPTY_PRODUCT);setMessage("Ürün eşleştirmesi kaydedildi.");await load()}catch(err){setMessage(`Hata: ${err?.message||"Ürün eşleştirmesi kaydedilemedi."}`)}finally{setBusy(false)}}
 async function action(kind,id,actionName){setBusy(true);try{await apiPost(`/admin/${kind}-aliases/${encodeURIComponent(id)}/${actionName}`,params);setMessage("Eşleştirme durumu güncellendi.");await load()}catch(err){setMessage(`Hata: ${err?.message||"İşlem tamamlanamadı."}`)}finally{setBusy(false)}}
 return <div className="admpro-page"><header className="admpro-head"><div><span className="admpro-kicker">YÖNETİM / EŞLEŞTİRME</span><h2>Eşleştirme Merkezi</h2><p>İşNet, fatura, irsaliye ve içe aktarımdan gelen ham adları temiz ana kayıtlara bağlar.</p></div><div className="admpro-actions"><button className="primary" onClick={load} disabled={busy}>Yenile</button></div></header><div className={`admpro-notice ${message.startsWith("Hata")?"error":message.includes("alınamadı")?"warn":"success"}`}>{message}</div><nav className="admpro-section-tabs"><button className={tab==="COMPANY"?"active":""} onClick={()=>setTab("COMPANY")}>Firma Eşleştirmeleri · {companyAliases.length}</button><button className={tab==="PRODUCT"?"active":""} onClick={()=>setTab("PRODUCT")}>Ürün Eşleştirmeleri · {productAliases.length}</button></nav><div className="admpro-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ham ad, temiz ad veya kod ara"/><label className="admpro-check"><input type="checkbox" checked={showDeleted} onChange={e=>setShowDeleted(e.target.checked)}/> Silinmiş kayıtları göster</label><span className="admpro-badge">Ana Firma: {activeMainCompany?.name||activeMainCompany?.slug||"Seçilmedi"}</span></div>
 {tab==="COMPANY"?<><section className="admpro-card"><div className="admpro-card-head"><div><h3>{companyForm.id?"Firma Eşleştirmesini Düzenle":"Yeni Firma Eşleştirmesi"}</h3><p>Ham isim bir kez tanımlandığında sonraki belgelerde aynı temiz firma önerilebilir.</p></div>{companyForm.id?<button onClick={()=>setCompanyForm(EMPTY_COMPANY)}>Yeni Kayıt</button>:null}</div><form onSubmit={saveCompany}><div className="admpro-form-grid"><label>Ham Firma Adı<input value={companyForm.rawName} onChange={e=>setCompanyForm(o=>({...o,rawName:e.target.value}))}/></label><label>Eşleşen Temiz Firma<select value={companyForm.matchedCompanyId} onChange={e=>setCompanyForm(o=>({...o,matchedCompanyId:e.target.value}))}><option value="">Firma seçin</option>{companies.map(c=><option key={c.id} value={c.id}>{c.firma||c.name||c.firmaAdi||c.unvan||c.id}</option>)}</select></label><label>Kaynak<input value={companyForm.sourceType} onChange={e=>setCompanyForm(o=>({...o,sourceType:e.target.value}))}/></label><label>Not<input value={companyForm.note} onChange={e=>setCompanyForm(o=>({...o,note:e.target.value}))}/></label><label className="admpro-check wide"><input type="checkbox" checked={companyForm.isActive} onChange={e=>setCompanyForm(o=>({...o,isActive:e.target.checked}))}/> Aktif eşleştirme</label></div><div className="admpro-actions" style={{justifyContent:"flex-start",marginTop:12}}><button className="primary" type="submit" disabled={busy}>{companyForm.id?"Güncelle":"Eşleştirmeyi Kaydet"}</button></div></form></section><section className="admpro-card"><div className="admpro-table"><table><thead><tr><th>Ham Ad</th><th>Normalize</th><th>Eşleşen Firma</th><th>Kaynak</th><th>Kullanım</th><th>Son Görülme</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{visibleCompany.map(r=><tr key={r.id}><td><strong>{r.rawName||"-"}</strong><small>{r.note||""}</small></td><td>{r.normalizedRawName||"-"}</td><td>{r.matchedCompanyName||r.matchedCompanyId||"-"}</td><td>{r.sourceType||"-"}</td><td>{r.hitCount||0}</td><td>{dateText(r.lastSeenAt)}</td><td><span className={`admpro-badge ${r.isDeleted?"bad":r.isActive!==false?"ok":"warn"}`}>{r.isDeleted?"Silinmiş":r.isActive!==false?"Aktif":"Pasif"}</span></td><td><div className="admpro-row-actions"><button onClick={()=>setCompanyForm({id:String(r.id||""),rawName:String(r.rawName||""),matchedCompanyId:String(r.matchedCompanyId||""),sourceType:String(r.sourceType||"MANUAL"),isActive:r.isActive!==false,note:String(r.note||"")})}>Düzenle</button>{r.isDeleted?<button onClick={()=>action("company",r.id,"restore")}>Geri Al</button>:<><button onClick={()=>action("company",r.id,r.isActive!==false?"deactivate":"activate")}>{r.isActive!==false?"Pasife Al":"Aktif Et"}</button><button className="danger" onClick={()=>action("company",r.id,"delete")}>Sil</button></>}</div></td></tr>)}{!visibleCompany.length?<tr><td colSpan="8">Eşleştirme kaydı yok.</td></tr>:null}</tbody></table></div></section></>:null}
 {tab==="PRODUCT"?<><section className="admpro-card"><div className="admpro-card-head"><div><h3>{productForm.id?"Ürün Eşleştirmesini Düzenle":"Yeni Ürün Eşleştirmesi"}</h3><p>Fatura/irsaliye kalemlerindeki ham ürün adını tek ürün kartına bağlar.</p></div>{productForm.id?<button onClick={()=>setProductForm(EMPTY_PRODUCT)}>Yeni Kayıt</button>:null}</div><form onSubmit={saveProduct}><div className="admpro-form-grid"><label>Ham Ürün Adı<input value={productForm.rawName} onChange={e=>setProductForm(o=>({...o,rawName:e.target.value}))}/></label><label>Eşleşen Ürün<select value={productForm.matchedProductId} onChange={e=>setProductForm(o=>({...o,matchedProductId:e.target.value}))}><option value="">Ürün seçin</option>{products.map(p=><option key={p.id} value={p.id}>{p.urunAdi||p.ticariAdi||p.name||p.productName||p.id}{p.kod||p.code?` · ${p.kod||p.code}`:""}</option>)}</select></label><label>Kaynak<input value={productForm.sourceType} onChange={e=>setProductForm(o=>({...o,sourceType:e.target.value}))}/></label><label>Not<input value={productForm.note} onChange={e=>setProductForm(o=>({...o,note:e.target.value}))}/></label><label className="admpro-check wide"><input type="checkbox" checked={productForm.isActive} onChange={e=>setProductForm(o=>({...o,isActive:e.target.checked}))}/> Aktif eşleştirme</label></div><div className="admpro-actions" style={{justifyContent:"flex-start",marginTop:12}}><button className="primary" type="submit" disabled={busy}>{productForm.id?"Güncelle":"Eşleştirmeyi Kaydet"}</button></div></form></section><section className="admpro-card"><div className="admpro-table"><table><thead><tr><th>Ham Ad</th><th>Normalize</th><th>Eşleşen Ürün</th><th>Kod</th><th>Kullanım</th><th>Son Görülme</th><th>Durum</th><th>İşlem</th></tr></thead><tbody>{visibleProduct.map(r=><tr key={r.id}><td><strong>{r.rawName||"-"}</strong><small>{r.note||""}</small></td><td>{r.normalizedRawName||"-"}</td><td>{r.matchedProductName||r.matchedProductId||"-"}</td><td>{r.matchedProductCode||"-"}</td><td>{r.hitCount||0}</td><td>{dateText(r.lastSeenAt)}</td><td><span className={`admpro-badge ${r.isDeleted?"bad":r.isActive!==false?"ok":"warn"}`}>{r.isDeleted?"Silinmiş":r.isActive!==false?"Aktif":"Pasif"}</span></td><td><div className="admpro-row-actions"><button onClick={()=>setProductForm({id:String(r.id||""),rawName:String(r.rawName||""),matchedProductId:String(r.matchedProductId||""),sourceType:String(r.sourceType||"MANUAL"),isActive:r.isActive!==false,note:String(r.note||"")})}>Düzenle</button>{r.isDeleted?<button onClick={()=>action("product",r.id,"restore")}>Geri Al</button>:<><button onClick={()=>action("product",r.id,r.isActive!==false?"deactivate":"activate")}>{r.isActive!==false?"Pasife Al":"Aktif Et"}</button><button className="danger" onClick={()=>action("product",r.id,"delete")}>Sil</button></>}</div></td></tr>)}{!visibleProduct.length?<tr><td colSpan="8">Eşleştirme kaydı yok.</td></tr>:null}</tbody></table></div></section></>:null}
 </div>
}
