import { useCallback, useEffect, useMemo, useState } from "react";
import {
  createBackup,
  getLogs,
  listSecurityAuditLog,
  listSessionHistory,
} from "../../services/adminApi";
import "./AdminManagement.css";

function rowsOf(value){const data=value?.data??value;if(Array.isArray(data))return data;if(Array.isArray(data?.items))return data.items;return []}
function dateText(value){if(!value)return"-";const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleString("tr-TR")}
function stringifyDetail(value){if(!value)return"";if(typeof value==="string")return value;try{return JSON.stringify(value)}catch{return String(value)}}

export default function AdminBackupLogs(){
 const [tab,setTab]=useState("BACKUP"),[logs,setLogs]=useState([]),[security,setSecurity]=useState([]),[sessions,setSessions]=useState([]),[backup,setBackup]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("Yedekleme ve log kayıtları hazırlanıyor..."),[search,setSearch]=useState("");
 const load=useCallback(async()=>{setBusy(true);const [logJob,secJob,sesJob]=await Promise.allSettled([getLogs({limit:250,_ts:Date.now()}),listSecurityAuditLog(250),listSessionHistory(250)]);if(logJob.status==="fulfilled")setLogs(rowsOf(logJob.value));if(secJob.status==="fulfilled")setSecurity(rowsOf(secJob.value));if(sesJob.status==="fulfilled")setSessions(rowsOf(sesJob.value));const failed=[logJob,secJob,sesJob].filter(x=>x.status==="rejected").length;setMessage(failed?`${failed} log kaynağı yanıt vermedi; alınan kayıtlar gösteriliyor.`:"Yedekleme ve denetim kayıtları güncel.");setBusy(false)},[]);
 useEffect(()=>{load()},[load]);
 async function backupNow(){setBusy(true);try{const result=await createBackup({reason:"MANUAL_ADMIN_BACKUP",requestedAt:new Date().toISOString()});setBackup(result?.data||result);setMessage("Yedekleme isteği tamamlandı.");await load()}catch(error){setMessage(`Hata: ${error?.message||"Yedekleme başlatılamadı."}`)}finally{setBusy(false)}}
 const term=search.trim().toLocaleLowerCase("tr-TR");
 const visibleLogs=useMemo(()=>logs.filter(r=>!term||stringifyDetail(r).toLocaleLowerCase("tr-TR").includes(term)),[logs,term]);
 const visibleSecurity=useMemo(()=>security.filter(r=>!term||`${r.action||""} ${r.actorName||""} ${r.targetName||""} ${r.ipAddress||""}`.toLocaleLowerCase("tr-TR").includes(term)),[security,term]);
 const visibleSessions=useMemo(()=>sessions.filter(r=>!term||`${r.fullName||r.username||""} ${r.closureReason||""} ${r.deviceLabel||""} ${r.ipAddress||""}`.toLocaleLowerCase("tr-TR").includes(term)),[sessions,term]);
 return <div className="admpro-page"><header className="admpro-head"><div><span className="admpro-kicker">YÖNETİM / YEDEKLEME & DENETİM</span><h2>Yedekleme & Denetim Logları</h2><p>Yedek, sistem olayları, güvenlik hareketleri ve oturum geçmişi tek noktada.</p></div><div className="admpro-actions"><button type="button" onClick={load} disabled={busy}>Yenile</button><button type="button" className="primary" onClick={backupNow} disabled={busy}>{busy?"İşleniyor...":"Şimdi Yedek Al"}</button></div></header><div className={`admpro-notice ${message.startsWith("Hata")?"error":message.includes("yanıt vermedi")?"warn":"success"}`}>{message}</div>
 <section className="admpro-stats"><div className="admpro-stat"><span>Sistem Logu</span><strong>{logs.length}</strong><small>Son alınan kayıtlar</small></div><div className="admpro-stat"><span>Güvenlik Olayı</span><strong>{security.length}</strong><small>Giriş ve yönetim olayları</small></div><div className="admpro-stat"><span>Oturum Geçmişi</span><strong>{sessions.length}</strong><small>Aktif ve kapanmış oturumlar</small></div><div className="admpro-stat"><span>Son Manuel Yedek</span><strong>{backup?"OK":"-"}</strong><small>{backup?.createdAt||backup?.timestamp?dateText(backup.createdAt||backup.timestamp):"Bu ekran oturumunda alınmadı"}</small></div></section>
 <nav className="admpro-section-tabs"><button className={tab==="BACKUP"?"active":""} onClick={()=>setTab("BACKUP")}>Yedekleme</button><button className={tab==="SYSTEM"?"active":""} onClick={()=>setTab("SYSTEM")}>Sistem Logu</button><button className={tab==="SECURITY"?"active":""} onClick={()=>setTab("SECURITY")}>Güvenlik Logu</button><button className={tab==="SESSIONS"?"active":""} onClick={()=>setTab("SESSIONS")}>Oturum Geçmişi</button></nav>
 {tab!=="BACKUP"?<div className="admpro-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Log, kullanıcı, işlem veya IP ara"/></div>:null}
 {tab==="BACKUP"?<section className="admpro-grid-2"><div className="admpro-card"><div className="admpro-card-head"><div><h3>Manuel Güvenli Yedek</h3><p>Canlı veri üzerinde kritik değişiklikten önce yedek alınması için yönetim noktası.</p></div></div><div className="admpro-notice warn">Yedekleme yalnız kayıt üretmekle yetinmemeli; API gerçek yedek dosyasını oluşturduğunu doğrulamadıkça “başarılı” kabul edilmez.</div><div className="admpro-actions" style={{justifyContent:"flex-start",marginTop:12}}><button className="primary" onClick={backupNow} disabled={busy}>Yedek Oluştur</button></div></div><div className="admpro-card"><div className="admpro-card-head"><div><h3>Son İşlem Sonucu</h3><p>Backend tarafından dönen yedekleme kanıtı.</p></div></div>{backup?<div className="admpro-list"><div className="admpro-list-item"><div><strong>{backup.fileName||backup.name||backup.id||"Yedek oluşturuldu"}</strong><small>{dateText(backup.createdAt||backup.timestamp)} · {backup.location||backup.path||backup.bucket||"Konum backend tarafından bildirilmedi"}</small></div><span className="admpro-badge ok">Tamamlandı</span></div></div>:<div className="admpro-empty">Bu oturumda manuel yedek alınmadı.</div>}</div></section>:null}
 {tab==="SYSTEM"?<section className="admpro-card"><div className="admpro-table"><table><thead><tr><th>Zaman</th><th>Seviye</th><th>Kaynak</th><th>Mesaj</th><th>Detay</th></tr></thead><tbody>{visibleLogs.map((r,i)=><tr key={r.id||i}><td>{dateText(r.createdAt||r.timestamp||r.time)}</td><td><span className="admpro-badge">{r.level||r.type||"INFO"}</span></td><td>{r.source||r.module||r.category||"Sistem"}</td><td>{r.message||r.action||r.title||"-"}</td><td className="admpro-code">{stringifyDetail(r.detail||r.data||"").slice(0,180)}</td></tr>)}{!visibleLogs.length?<tr><td colSpan="5">Sistem logu yok veya endpoint henüz veri üretmiyor.</td></tr>:null}</tbody></table></div></section>:null}
 {tab==="SECURITY"?<section className="admpro-card"><div className="admpro-table"><table><thead><tr><th>Zaman</th><th>İşlem</th><th>Uygulayan</th><th>Hedef</th><th>IP</th><th>Detay</th></tr></thead><tbody>{visibleSecurity.map((r,i)=><tr key={r.id||i}><td>{dateText(r.createdAt)}</td><td><strong>{r.action||"-"}</strong></td><td>{r.actorName||"Sistem"}</td><td>{r.targetName||"-"}</td><td>{r.ipAddress||"-"}</td><td className="admpro-code">{stringifyDetail(r.detail).slice(0,180)}</td></tr>)}{!visibleSecurity.length?<tr><td colSpan="6">Güvenlik kaydı yok.</td></tr>:null}</tbody></table></div></section>:null}
 {tab==="SESSIONS"?<section className="admpro-card"><div className="admpro-table"><table><thead><tr><th>Kullanıcı</th><th>Durum</th><th>Giriş</th><th>Son Hareket</th><th>Kapanış</th><th>Cihaz / IP</th></tr></thead><tbody>{visibleSessions.map((r,i)=><tr key={r.id||i}><td><strong>{r.fullName||r.username||"-"}</strong></td><td><span className={`admpro-badge ${r.closureReason==="ACTIVE"?"ok":""}`}>{r.closureReason||"-"}</span></td><td>{dateText(r.createdAt)}</td><td>{dateText(r.lastSeenAt)}</td><td>{r.revokedAt?dateText(r.revokedAt):r.expiresAt?dateText(r.expiresAt):"-"}</td><td>{r.deviceLabel||"Tarayıcı"}<small>{r.ipAddress||""}</small></td></tr>)}{!visibleSessions.length?<tr><td colSpan="6">Oturum geçmişi yok.</td></tr>:null}</tbody></table></div></section>:null}
 </div>
}
