import { useCallback, useEffect, useMemo, useState } from "react";
import { getPdksModernConfig, savePdksModernConfig, savePdksWorkGroupRules } from "../../services/pdksApi";
import "./PdksRulesCenter.css";

const DAYS = [[1,"Pzt"],[2,"Sal"],[3,"Çar"],[4,"Per"],[5,"Cum"],[6,"Cmt"],[0,"Paz"]];
const parseDays=(value,fallback=[])=>{if(Array.isArray(value))return value.map(Number);try{const rows=JSON.parse(String(value||"[]"));return Array.isArray(rows)?rows.map(Number):fallback}catch{return fallback}};
const num=(value,fallback=0)=>Number.isFinite(Number(value))?Number(value):fallback;
const bool=(value)=>value===true||value===1||String(value).toLowerCase()==="true";

function DayPicker({value,onChange,label}){
  const list=Array.isArray(value)?value:[];
  const toggle=(day)=>onChange(list.includes(day)?list.filter(v=>v!==day):[...list,day]);
  return <div className="prc-dayfield"><span>{label}</span><div>{DAYS.map(([key,name])=><button type="button" key={key} className={list.includes(key)?"active":""} onClick={()=>toggle(key)}>{name}</button>)}</div></div>;
}

function NumberField({label,value,onChange,suffix,min=0,max=9999}){return <label className="prc-field"><span>{label}</span><div><input type="number" min={min} max={max} value={value} onChange={e=>onChange(Number(e.target.value))}/>{suffix?<em>{suffix}</em>:null}</div></label>}

export default function PdksRulesCenter({activeMainCompany,isAuditAccount=false}){
  const company=activeMainCompany?.slug||activeMainCompany?.id||"mecit-hakan";
  const [config,setConfig]=useState(null),[companyRule,setCompanyRule]=useState(null),[selectedGroup,setSelectedGroup]=useState(""),[groupRule,setGroupRule]=useState(null);
  const [busy,setBusy]=useState(false),[message,setMessage]=useState(""),[error,setError]=useState("");

  const load=useCallback(async()=>{setBusy(true);setError("");try{const result=await getPdksModernConfig({mainCompanyId:company});setConfig(result||{});const p=result?.profile||{};setCompanyRule({workDays:p.workDays||[1,2,3,4,5,6],restDays:p.restDays||[0],annualCountDays:p.annualCountDays||[1,2,3,4,5,6],breakMinutes:num(p.breakMinutes,60),overtimeMin:num(p.overtimeMin,15),overtimeRound:num(p.overtimeRound,15),duplicateWindow:num(p.duplicateWindow,60),halfDayMinutes:num(p.halfDayMinutes,240),maxDailyMinutes:num(p.maxDailyMinutes,660),maxWeeklyMinutes:num(p.maxWeeklyMinutes,2700)});setSelectedGroup(current=>(result?.groups||[]).some(g=>g.id===current)?current:(result?.groups?.[0]?.id||""))}catch(cause){setError(cause?.message||"PDKS kural tanımları alınamadı.")}finally{setBusy(false)}},[company]);
  useEffect(()=>{load()},[load]);

  const group=useMemo(()=>(config?.groups||[]).find(row=>row.id===selectedGroup)||null,[config?.groups,selectedGroup]);
  useEffect(()=>{if(!group){setGroupRule(null);return}setGroupRule({workDays:parseDays(group.work_days_json,[1,2,3,4,5,6]),restDays:parseDays(group.weekly_rest_days_json,[0]),breakMinutes:num(group.break_minutes??companyRule?.breakMinutes,60),overtimeMin:num(group.overtime_min_minutes??companyRule?.overtimeMin,15),overtimeRound:num(group.overtime_round_minutes??companyRule?.overtimeRound,15),duplicateWindow:num(group.duplicate_punch_window_seconds??companyRule?.duplicateWindow,60),halfDayMinutes:num(group.half_day_minutes??companyRule?.halfDayMinutes,240),maxDailyMinutes:num(group.max_daily_minutes??companyRule?.maxDailyMinutes,660),maxWeeklyMinutes:num(group.max_weekly_minutes??companyRule?.maxWeeklyMinutes,2700),crossMidnight:bool(group.cross_midnight),flexible:bool(group.flexible),flexibleStart:group.flexible_start||"",flexibleEnd:group.flexible_end||"",nightShift:bool(group.night_shift),overtimeRequiresApproval:bool(group.overtime_requires_approval)})},[companyRule,group]);

  const saveCompany=async()=>{if(isAuditAccount||!companyRule)return;setBusy(true);setError("");setMessage("");try{await savePdksModernConfig({mainCompanyId:company,...companyRule});setMessage("Genel PDKS çalışma ve puantaj kuralları kaydedildi.");await load()}catch(cause){setError(cause?.message||"Genel kurallar kaydedilemedi.")}finally{setBusy(false)}};
  const saveGroup=async()=>{if(isAuditAccount||!groupRule||!selectedGroup)return;setBusy(true);setError("");setMessage("");try{await savePdksWorkGroupRules(selectedGroup,{mainCompanyId:company,...groupRule});setMessage(`${group?.name||"Vardiya"} özel kuralları kaydedildi.`);await load()}catch(cause){setError(cause?.message||"Vardiya kuralları kaydedilemedi.")}finally{setBusy(false)}};

  if(!companyRule)return <div className="prc-page"><div className="prc-loading">{busy?"Kurallar yükleniyor...":error||"Kural verisi yok."}</div></div>;
  return <div className="prc-page">
    <header className="prc-head"><div><small>PDKS / PUANTAJ MOTORU V3</small><h1>Çalışma & Puantaj Kuralları</h1><p>Cumartesi/Pazar, mola, geç/erken toleransı, fazla mesai, yarım gün ve vardiya istisnaları tek merkezden yönetilir.</p></div><div><span className="prc-engine">● MOTOR AKTİF</span><button type="button" onClick={load} disabled={busy}>Yenile</button></div></header>
    {message?<div className="prc-message">{message}</div>:null}{error?<div className="prc-error">{error}</div>:null}

    <section className="prc-card"><div className="prc-card-title"><div><span>ŞİRKET VARSAYILANI</span><h2>Genel Çalışma Takvimi</h2></div><b>Vardiyada özel kural yoksa bunlar uygulanır</b></div>
      <div className="prc-days"><DayPicker label="Çalışma günleri" value={companyRule.workDays} onChange={v=>setCompanyRule({...companyRule,workDays:v})}/><DayPicker label="Hafta tatili" value={companyRule.restDays} onChange={v=>setCompanyRule({...companyRule,restDays:v})}/><DayPicker label="Yıllık izinden sayılan hafta günleri" value={companyRule.annualCountDays} onChange={v=>setCompanyRule({...companyRule,annualCountDays:v})}/></div>
      <div className="prc-numbers"><NumberField label="Günlük mola" value={companyRule.breakMinutes} suffix="dk" onChange={v=>setCompanyRule({...companyRule,breakMinutes:v})}/><NumberField label="Mesai başlama eşiği" value={companyRule.overtimeMin} suffix="dk" onChange={v=>setCompanyRule({...companyRule,overtimeMin:v})}/><NumberField label="Mesai yuvarlama" value={companyRule.overtimeRound} suffix="dk" min={1} onChange={v=>setCompanyRule({...companyRule,overtimeRound:v})}/><NumberField label="Mükerrer basım aralığı" value={companyRule.duplicateWindow} suffix="sn" onChange={v=>setCompanyRule({...companyRule,duplicateWindow:v})}/><NumberField label="Yarım gün süresi" value={companyRule.halfDayMinutes} suffix="dk" onChange={v=>setCompanyRule({...companyRule,halfDayMinutes:v})}/><NumberField label="Günlük üst kontrol" value={companyRule.maxDailyMinutes} suffix="dk" onChange={v=>setCompanyRule({...companyRule,maxDailyMinutes:v})}/><NumberField label="Haftalık üst kontrol" value={companyRule.maxWeeklyMinutes} suffix="dk" onChange={v=>setCompanyRule({...companyRule,maxWeeklyMinutes:v})}/></div>
      {!isAuditAccount?<div className="prc-actions"><button className="primary" type="button" onClick={saveCompany} disabled={busy}>Genel Kuralları Kaydet</button></div>:null}
    </section>

    <section className="prc-card"><div className="prc-card-title"><div><span>VARDİYA ÖZELİ</span><h2>Grup / Vardiya Kuralı</h2></div><select value={selectedGroup} onChange={e=>setSelectedGroup(e.target.value)}>{(config?.groups||[]).map(row=><option key={row.id} value={row.id}>{row.name} · {row.entryTime}-{row.exitTime}</option>)}</select></div>
      {group&&groupRule?<><div className="prc-shift-banner"><div><span>Vardiya</span><strong>{group.name}</strong></div><div><span>Giriş / Çıkış</span><strong>{group.entryTime} – {group.exitTime}</strong></div><div><span>Geç Toleransı</span><strong>{group.lateTolerance} dk</strong></div><div><span>Erken Toleransı</span><strong>{group.earlyTolerance} dk</strong></div></div>
        <div className="prc-days two"><DayPicker label="Bu vardiyanın çalışma günleri" value={groupRule.workDays} onChange={v=>setGroupRule({...groupRule,workDays:v})}/><DayPicker label="Bu vardiyanın hafta tatili" value={groupRule.restDays} onChange={v=>setGroupRule({...groupRule,restDays:v})}/></div>
        <div className="prc-numbers"><NumberField label="Mola" value={groupRule.breakMinutes} suffix="dk" onChange={v=>setGroupRule({...groupRule,breakMinutes:v})}/><NumberField label="Mesai eşiği" value={groupRule.overtimeMin} suffix="dk" onChange={v=>setGroupRule({...groupRule,overtimeMin:v})}/><NumberField label="Mesai yuvarlama" value={groupRule.overtimeRound} suffix="dk" min={1} onChange={v=>setGroupRule({...groupRule,overtimeRound:v})}/><NumberField label="Mükerrer basım" value={groupRule.duplicateWindow} suffix="sn" onChange={v=>setGroupRule({...groupRule,duplicateWindow:v})}/><NumberField label="Yarım gün" value={groupRule.halfDayMinutes} suffix="dk" onChange={v=>setGroupRule({...groupRule,halfDayMinutes:v})}/><NumberField label="Günlük kontrol" value={groupRule.maxDailyMinutes} suffix="dk" onChange={v=>setGroupRule({...groupRule,maxDailyMinutes:v})}/><NumberField label="Haftalık kontrol" value={groupRule.maxWeeklyMinutes} suffix="dk" onChange={v=>setGroupRule({...groupRule,maxWeeklyMinutes:v})}/></div>
        <div className="prc-switches"><label><input type="checkbox" checked={groupRule.crossMidnight} onChange={e=>setGroupRule({...groupRule,crossMidnight:e.target.checked})}/><span><b>Geceye sarkan vardiya</b><small>Çıkış saati ertesi güne geçebilir.</small></span></label><label><input type="checkbox" checked={groupRule.nightShift} onChange={e=>setGroupRule({...groupRule,nightShift:e.target.checked})}/><span><b>Gece vardiyası</b><small>Raporlarda gece vardiyası olarak ayrılır.</small></span></label><label><input type="checkbox" checked={groupRule.flexible} onChange={e=>setGroupRule({...groupRule,flexible:e.target.checked})}/><span><b>Esnek mesai</b><small>Başlangıç/bitiş penceresi uygulanabilir.</small></span></label><label><input type="checkbox" checked={groupRule.overtimeRequiresApproval} onChange={e=>setGroupRule({...groupRule,overtimeRequiresApproval:e.target.checked})}/><span><b>Mesai onayı zorunlu</b><small>Hesaplanan fazla mesai onay akışına alınır.</small></span></label></div>
        {groupRule.flexible?<div className="prc-flex"><label>Esnek Başlangıç<input type="time" value={groupRule.flexibleStart} onChange={e=>setGroupRule({...groupRule,flexibleStart:e.target.value})}/></label><label>Esnek Bitiş<input type="time" value={groupRule.flexibleEnd} onChange={e=>setGroupRule({...groupRule,flexibleEnd:e.target.value})}/></label></div>:null}
        {!isAuditAccount?<div className="prc-actions"><button className="primary" type="button" onClick={saveGroup} disabled={busy}>Vardiya Özel Kurallarını Kaydet</button></div>:null}
      </>:<div className="prc-empty">Vardiya seçin.</div>}
    </section>

    <section className="prc-card"><div className="prc-card-title"><div><span>İZİN MOTORU</span><h2>Tanımlı İzin Türleri</h2></div><b>{config?.leaveTypes?.length||0} tip</b></div><div className="prc-leaves">{(config?.leaveTypes||[]).map(row=><article key={row.code}><div><strong>{row.name}</strong><code>{row.code}</code></div><span>{row.unit} · {row.paid?"Ücretli":"Ücretsiz"}{row.annualBalanceEffect?" · Yıllık bakiyeden düşer":""}</span><small>{row.legalNote||"Şirket kuralı"}</small></article>)}</div></section>
  </div>;
}
