using FirebirdSql.Data.FirebirdClient;
using System.Data;
using System.Globalization;
using KYERP.PDKS.Core;
using KYERP.PDKS.Core.Payroll;
using KYERP.PDKS.Core.Leave;

namespace HKN.Personel.Native;

public partial class PersonelForm
{
    void ShowGirisCikisEklemeClassic()
    {
        using var d=new Form{Text="Giriş Çıkış Ekleme",StartPosition=FormStartPosition.CenterParent,Size=new Size(760,465),FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,Font=Font};
        var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,RowCount=2,Padding=new Padding(8)};
        root.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,245));root.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,275));root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));
        root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.Absolute,58));
        var left=PeopleGrid();var right=PeopleGrid();var all=LoadGirisPeople();var chosen=all.Clone();left.DataSource=all;right.DataSource=chosen;SetupPeopleGrid(left);SetupPeopleGrid(right);
        if(currentPk!=""){var rr=all.Select("PKNO='"+currentPk.Replace("'","''")+"'");if(rr.Length>0)chosen.ImportRow(rr[0]);}
        root.Controls.Add(left,0,0);root.Controls.Add(right,2,0);
        var c=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=15,Padding=new Padding(8,4,8,2)};c.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,80));c.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));
        var title=new Label{Text="Seçenekler",Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleCenter,Font=new Font(Font.FontFamily,11,FontStyle.Bold)};c.Controls.Add(title,0,0);c.SetColumnSpan(title,2);
        var boxes=new[]{NewFilterBox(),NewFilterBox(),NewFilterBox(),NewFilterBox(),NewFilterBox(),NewFilterBox()};FillFilterBoxes(boxes,all);string[] labs={"Grup","Bölüm","Servis","Durum","Görev","Firma"};
        for(int i=0;i<6;i++){c.Controls.Add(new Label{Text=labs[i],Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft},0,i+1);c.Controls.Add(boxes[i],1,i+1);boxes[i].SelectedIndexChanged+=(_,_)=>FilterPeople(all,boxes,left);}
        var gd=new DateTimePicker{Dock=DockStyle.Fill,Format=DateTimePickerFormat.Custom,CustomFormat="dd MMMM yyyy dddd"};var gt=ClassicTimeBox("08:30");var cd=new DateTimePicker{Dock=DockStyle.Fill,Format=DateTimePickerFormat.Custom,CustomFormat="dd MMMM yyyy dddd"};var ct=ClassicTimeBox("19:00");
        AddClassicDialogRow(c,7,"Giriş Tarihi",gd);AddClassicDialogRow(c,8,"Giriş Saati",gt);AddClassicDialogRow(c,9,"Çıkış Tarihi",cd);AddClassicDialogRow(c,10,"Çıkış Saati",ct);
        var tol=new NumericUpDown{Minimum=0,Maximum=180,Width=52};var tp=new FlowLayoutPanel{Dock=DockStyle.Fill,WrapContents=false};tp.Controls.Add(tol);tp.Controls.Add(new Label{Text=" Dakika",AutoSize=true,Padding=new Padding(0,5,0,0)});c.Controls.Add(new Label{Text="Tolerans ±",Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft},0,11);c.Controls.Add(tp,1,11);
        root.Controls.Add(c,1,0);
        var lbar=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(70,8,0,0)};var one=new Button{Text=">",Width=38,Height=30};var allb=new Button{Text=">>",Width=38,Height=30};lbar.Controls.Add(one);lbar.Controls.Add(allb);root.Controls.Add(lbar,0,1);
        var rbar=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(55,8,0,0)};var backAll=new Button{Text="<<",Width=38,Height=30};var back=new Button{Text="<",Width=38,Height=30};rbar.Controls.Add(backAll);rbar.Controls.Add(back);root.Controls.Add(rbar,2,1);
        var acts=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(15,5,0,0)};var add=new Button{Text="Ekle",Width=105,Height=34,Font=new Font(Font,FontStyle.Bold),ForeColor=Color.Navy,Image=ClassicGlyph("Yeni"),ImageAlign=ContentAlignment.MiddleLeft};var close=new Button{Text="Kapat",Width=105,Height=34,DialogResult=DialogResult.Cancel,Font=new Font(Font,FontStyle.Bold),ForeColor=Color.Navy,Image=ClassicGlyph("Sil"),ImageAlign=ContentAlignment.MiddleLeft};acts.Controls.Add(add);acts.Controls.Add(close);root.Controls.Add(acts,1,1);
        one.Click+=(_,_)=>MoveSelected(left,chosen);allb.Click+=(_,_)=>MoveAll(left,chosen);back.Click+=(_,_)=>RemoveSelected(right,chosen);backAll.Click+=(_,_)=>chosen.Clear();
        add.Click+=(_,_)=>{try{if(chosen.Rows.Count==0)throw new Exception("En az bir personel seçin.");var gi=ClassicDateTime(gd.Value,gt.Text);var ci=ClassicDateTime(cd.Value,ct.Text);PdksValidation.AttendanceRange(gi,ci);int n=InsertGirisCikis(chosen,gi,ci,(int)tol.Value);MessageBox.Show($"{n} personel için kayıt eklendi.","Giriş Çıkış Ekleme");RefreshFullTabs();d.DialogResult=DialogResult.OK;d.Close();}catch(Exception ex){MessageBox.Show(ex.Message,"Giriş Çıkış Ekleme");}};
        d.Controls.Add(root);d.CancelButton=close;d.ShowDialog(this);
    }

    void ShowIzinEditorClassic(bool edit)
    {
        if(currentPk=="")return;if(edit&&gIzin.CurrentRow==null)return;
        using var d=new Form{Text="Personel İzin Girişi",StartPosition=FormStartPosition.CenterParent,Size=new Size(780,520),FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,Font=Font};
        var root=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=3,RowCount=2,Padding=new Padding(8)};root.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,235));root.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,300));root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.Percent,100));root.RowStyles.Add(new RowStyle(SizeType.Absolute,58));
        var people=LoadAllDialogPeople();var chosen=people.Clone();var left=PeopleGrid();var right=PeopleGrid();left.DataSource=people;right.DataSource=chosen;SetupPeopleGrid(left);SetupPeopleGrid(right);root.Controls.Add(left,0,0);root.Controls.Add(right,2,0);
        if(currentPk!=""){var rr=people.Select("PKNO='"+currentPk.Replace("'","''")+"'");if(rr.Length>0)chosen.ImportRow(rr[0]);}
        var c=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=17,Padding=new Padding(8,2,8,2)};c.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,105));c.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));
        var grp=new GroupBox{Text="Filtreleme",Dock=DockStyle.Fill};var radios=new FlowLayoutPanel{Dock=DockStyle.Fill};var ra=new RadioButton{Text="Aktif Çalışanlar",Checked=true,AutoSize=true};var rt=new RadioButton{Text="Tümü",AutoSize=true};var rx=new RadioButton{Text="İşten Ayrılanlar",AutoSize=true};radios.Controls.Add(rt);radios.Controls.Add(ra);radios.Controls.Add(rx);grp.Controls.Add(radios);c.Controls.Add(grp,0,0);c.SetColumnSpan(grp,2);
        var boxes=new[]{NewFilterBox(),NewFilterBox(),NewFilterBox(),NewFilterBox(),NewFilterBox(),NewFilterBox()};FillFilterBoxes(boxes,people);string[] labs={"Grup","Bölüm","Servis","Durum","Görev","Firma"};for(int i=0;i<6;i++){c.Controls.Add(new Label{Text=labs[i],Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft},0,i+1);c.Controls.Add(boxes[i],1,i+1);boxes[i].SelectedIndexChanged+=(_,_)=>FilterIzinPeople(people,boxes,left,ra.Checked?1:rx.Checked?2:0);}ra.CheckedChanged+=(_,_)=>FilterIzinPeople(people,boxes,left,ra.Checked?1:rx.Checked?2:0);rt.CheckedChanged+=(_,_)=>FilterIzinPeople(people,boxes,left,ra.Checked?1:rx.Checked?2:0);rx.CheckedChanged+=(_,_)=>FilterIzinPeople(people,boxes,left,ra.Checked?1:rx.Checked?2:0);
        var tipBox=new GroupBox{Text="İzin Tipi",Dock=DockStyle.Fill};var tipFlow=new FlowLayoutPanel{Dock=DockStyle.Fill};var ucretli=new RadioButton{Text="Ücretli",AutoSize=true};var ucretsiz=new RadioButton{Text="Ücretsiz",Checked=true,AutoSize=true};tipFlow.Controls.Add(ucretli);tipFlow.Controls.Add(ucretsiz);tipBox.Controls.Add(tipFlow);c.Controls.Add(tipBox,0,7);
        var sureBox=new GroupBox{Text="Süre",Dock=DockStyle.Fill};var sureFlow=new FlowLayoutPanel{Dock=DockStyle.Fill};var saatlik=new RadioButton{Text="Saatlik İzin",Checked=true,AutoSize=true};var tam=new RadioButton{Text="Tam Günlük İzin",AutoSize=true};sureFlow.Controls.Add(saatlik);sureFlow.Controls.Add(tam);sureBox.Controls.Add(sureFlow);c.Controls.Add(sureBox,1,7);
        var basD=new DateTimePicker{Dock=DockStyle.Fill,Format=DateTimePickerFormat.Custom,CustomFormat="dd MMMM yyyy dddd"};var bitD=new DateTimePicker{Dock=DockStyle.Fill,Format=DateTimePickerFormat.Custom,CustomFormat="dd MMMM yyyy dddd"};var basS=ClassicTimeBox("08:30");var bitS=ClassicTimeBox("16:00");var hak=ClassicTimeBox("07:30");var maz=new ComboBox{Dock=DockStyle.Fill,DropDownStyle=ComboBoxStyle.DropDown};maz.Items.AddRange(new object[]{"Belirtin","MAZERET","YILLIK İZİN","RAPORLU"});maz.SelectedIndex=0;var alan=new ComboBox{Dock=DockStyle.Fill,DropDownStyle=ComboBoxStyle.DropDownList,DisplayMember=nameof(LeaveAreaItem.Name),DataSource=new[]{new LeaveAreaItem("Ücretsiz İzin",LeavePayrollArea.Unpaid),new LeaveAreaItem("Ücretli İzin",LeavePayrollArea.Paid)}};
        AddClassicDialogRow(c,8,"Başlangıç Tarihi",basD);AddClassicDialogRow(c,9,"Bitiş Tarihi",bitD);AddClassicDialogRow(c,10,"Başlangıç Saati",basS);AddClassicDialogRow(c,11,"Bitiş Saati",bitS);AddClassicDialogRow(c,12,"Hakediş Süre",hak);AddClassicDialogRow(c,13,"Mazeret",maz);AddClassicDialogRow(c,14,"Ekleneceği Alan",alan);root.Controls.Add(c,1,0);
        if(edit){var r=gIzin.CurrentRow!;basD.Value=Convert.ToDateTime(r.Cells["TARIH"].Value);bitD.Value=basD.Value;basS.Text=Convert.ToString(r.Cells["BASSAAT"].Value)??"08:30";bitS.Text=Convert.ToString(r.Cells["BITSAAT"].Value)??"16:00";hak.Text=Convert.ToString(r.Cells["SURESAAT"].Value)??"07:30";string t=Convert.ToString(r.Cells["TIP"].Value)??"";ucretli.Checked=t.Contains("ÜCRETLİ")&&!t.Contains("ÜCRETSİZ");ucretsiz.Checked=!ucretli.Checked;maz.Text=Convert.ToString(r.Cells["MAZERET"].Value)??"";var area=r.Cells["EBALAN"].Value==DBNull.Value?(ucretli.Checked?LeavePayrollArea.Paid:LeavePayrollArea.Unpaid):Convert.ToInt32(r.Cells["EBALAN"].Value);alan.SelectedIndex=area==LeavePayrollArea.Paid?1:0;tam.Checked=Convert.ToString(r.Cells["SURESAAT"].Value)==LeaveEntryValidator.FullDayDuration;if(IsAnnualLeave(maz.Text)){tam.Checked=true;bitD.Value=basD.Value.AddDays(1);}}
        maz.TextChanged+=(_,_)=>{if(IsAnnualLeave(maz.Text)){ucretli.Checked=true;tam.Checked=true;alan.SelectedIndex=1;}};alan.SelectedIndexChanged+=(_,_)=>{if(alan.SelectedItem is LeaveAreaItem item){ucretli.Checked=item.Code==LeavePayrollArea.Paid;ucretsiz.Checked=item.Code==LeavePayrollArea.Unpaid;}};
        var lbar=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(65,8,0,0)};var one=new Button{Text=">",Width=38,Height=30};var allb=new Button{Text=">>",Width=38,Height=30};lbar.Controls.Add(one);lbar.Controls.Add(allb);root.Controls.Add(lbar,0,1);var rbar=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(50,8,0,0)};var backAll=new Button{Text="<<",Width=38,Height=30};var back=new Button{Text="<",Width=38,Height=30};rbar.Controls.Add(backAll);rbar.Controls.Add(back);root.Controls.Add(rbar,2,1);
        var acts=new FlowLayoutPanel{Dock=DockStyle.Fill,Padding=new Padding(20,5,0,0)};var add=new Button{Text=edit?"Kaydet":"Ekle",Width=102,Height=34,Font=new Font(Font,FontStyle.Bold),ForeColor=Color.Navy,Image=ClassicGlyph("Yeni"),ImageAlign=ContentAlignment.MiddleLeft};var close=new Button{Text="Kapat",Width=102,Height=34,DialogResult=DialogResult.Cancel,Font=new Font(Font,FontStyle.Bold),ForeColor=Color.Navy,Image=ClassicGlyph("Sil"),ImageAlign=ContentAlignment.MiddleLeft};acts.Controls.Add(add);acts.Controls.Add(close);root.Controls.Add(acts,1,1);
        one.Click+=(_,_)=>MoveSelected(left,chosen);allb.Click+=(_,_)=>MoveAll(left,chosen);back.Click+=(_,_)=>RemoveSelected(right,chosen);backAll.Click+=(_,_)=>chosen.Clear();
        add.Click+=(_,_)=>{try{var annual=IsAnnualLeave(maz.Text);var area=annual?LeavePayrollArea.Paid:(alan.SelectedItem as LeaveAreaItem??throw new Exception("İzin bordro alanını seçin.")).Code;LeavePayrollArea.Validate(area);IReadOnlyList<DateTime> dates;int minutes;string startTime,endTime;if(tam.Checked){dates=annual?AnnualLeaveDateExpander.Expand(basD.Value,bitD.Value):FullDayLeaveDateExpander.Expand(basD.Value,bitD.Value);minutes=LeaveEntryValidator.FullDayMinutes;startTime=basS.Text.Trim();endTime=bitS.Text.Trim();}else{var duration=LeaveEntryValidator.ValidateHourly(basD.Value,basS.Text,bitD.Value,bitS.Text);dates=[basD.Value.Date];minutes=duration.Minutes;startTime=duration.StartTime;endTime=duration.EndTime;}if(edit&&dates.Count!=1)throw new InvalidOperationException("Çok günlük izin aralığı tek satır üzerinden düzenlenemez. Aralığı silip yeniden oluşturun.");var type=area==LeavePayrollArea.Paid?"ÜCRETLİ":"ÜCRETSİZ";var reason=annual?"YILLIK İZİN":maz.Text.Trim();var repository=new LeaveRepository(db);if(edit){var sequence=Convert.ToInt32(gIzin.CurrentRow!.Cells["SIRA"].Value);repository.UpdateSingle(sequence,new LeaveRecord(currentPk,dates[0],startTime,endTime,minutes,type,reason,area));}else{if(chosen.Rows.Count==0)throw new Exception("En az bir personel seçin.");var records=(from DataRow person in chosen.Rows from date in dates select new LeaveRecord(Convert.ToString(person["PKNO"])??"",date,startTime,endTime,minutes,type,reason,area)).ToArray();var result=repository.AddMany(records);MessageBox.Show($"Eklenen: {result.Inserted}\nDuplicate: {result.Duplicates}","Personel İzin Girişi");}RefreshFullTabs();d.DialogResult=DialogResult.OK;d.Close();}catch(Exception ex){MessageBox.Show(ex.Message,"Personel İzin Girişi");}};
        d.Controls.Add(root);d.CancelButton=close;d.ShowDialog(this);
    }

    void ShowEkkEditorClassic(bool edit)
    {
        if(currentPk=="")return;if(edit&&gEkk.CurrentRow==null)return;
        using var d=new Form{Text="Ek Kazanç ve Kesinti Girişi",StartPosition=FormStartPosition.CenterParent,Size=new Size(330,365),FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,Font=Font};
        var p=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=10,Padding=new Padding(12)};p.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,105));p.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));
        var pk=new TextBox{Text=currentPk,ReadOnly=true,Dock=DockStyle.Fill};var ad=new TextBox{Text=f.GetValueOrDefault("AD")?.Text??"",ReadOnly=true,Dock=DockStyle.Fill};var soy=new TextBox{Text=f.GetValueOrDefault("SOYAD")?.Text??"",ReadOnly=true,Dock=DockStyle.Fill};AddClassicDialogRow(p,0,"Kart Numarası",pk);AddClassicDialogRow(p,1,"Adı",ad);AddClassicDialogRow(p,2,"Soyadı",soy);
        var islem=new DateTimePicker{Dock=DockStyle.Fill,Format=DateTimePickerFormat.Custom,CustomFormat="dd MMMM yyyy dddd"};var ver=new DateTimePicker{Dock=DockStyle.Fill,Format=DateTimePickerFormat.Custom,CustomFormat="dd MMMM yyyy dddd"};var mik=new TextBox{Dock=DockStyle.Fill};var tak=new NumericUpDown{Minimum=1,Maximum=120,Value=1,Dock=DockStyle.Fill};var tur=new ComboBox{Dock=DockStyle.Fill,DropDownStyle=ComboBoxStyle.DropDownList};tur.Items.AddRange(new object[]{"Ek Kazanç","Kesinti"});tur.SelectedIndex=1;var ac=new TextBox{Dock=DockStyle.Fill};AddClassicDialogRow(p,3,"İşlem Tarihi",islem);AddClassicDialogRow(p,4,"Veriliş Tarihi",ver);AddClassicDialogRow(p,5,"Miktar",mik);AddClassicDialogRow(p,6,"Taksit Sayısı",tak);AddClassicDialogRow(p,7,"Türü",tur);AddClassicDialogRow(p,8,"Açıklama",ac);
        if(edit){var r=gEkk.CurrentRow!;islem.Value=Convert.ToDateTime(r.Cells["ISLEM_TARIHI"].Value);if(r.Cells["VERILIS_TARIHI"].Value is DateTime vd)ver.Value=vd;int tk=Convert.ToInt32(r.Cells["TURU"].Value);tur.SelectedIndex=tk==1?0:1;mik.Text=Convert.ToString(r.Cells["MIKTAR"].Value)??"";ac.Text=Convert.ToString(r.Cells["ACIKLAMA"].Value)??"";}
        var bar=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.RightToLeft,Padding=new Padding(0,7,0,0)};var cancel=new Button{Text="İptal",Width=112,Height=34,DialogResult=DialogResult.Cancel,ForeColor=Color.Navy,Font=new Font(Font,FontStyle.Bold),Image=ClassicGlyph("Sil"),ImageAlign=ContentAlignment.MiddleLeft};var save=new Button{Text="Kaydet",Width=112,Height=34,ForeColor=Color.Navy,Font=new Font(Font,FontStyle.Bold),Image=ClassicGlyph("Yeni"),ImageAlign=ContentAlignment.MiddleLeft};bar.Controls.Add(cancel);bar.Controls.Add(save);p.Controls.Add(bar,0,9);p.SetColumnSpan(bar,2);
        save.Click+=(_,_)=>{try{var m=PdksValidation.ParseMoney(mik.Text,"Miktar");int tk=tur.SelectedIndex==0?1:2;if(edit){int k=Convert.ToInt32(gEkk.CurrentRow!.Cells["KOD"].Value);Exec("update AVANS set TARIH=@D,VTARIH=@V,TURKOD=@T,MIKTAR=@M,TOPMIKTAR=@A,TAKSITSAYISI=@TS,ACIKLAMA=@C where KOD=@K and PKNO=@PK",new FbParameter("@D",islem.Value.Date),new FbParameter("@V",ver.Value.Date),new FbParameter("@T",tk),new FbParameter("@M",m),new FbParameter("@A",m),new FbParameter("@TS",(int)tak.Value),new FbParameter("@C",ac.Text.Trim()),new FbParameter("@K",k),new FbParameter("@PK",currentPk));}else{Exec("insert into AVANS (PKNO,TARIH,MIKTAR,VTARIH,TURKOD,KOD,TOPMIKTAR,TAKSITSAYISI,TAKSITNO,ACIKLAMA) values (@PK,@D,@M,@V,@T,@K,@A,@TS,1,@C)",new FbParameter("@PK",currentPk),new FbParameter("@D",islem.Value.Date),new FbParameter("@M",m),new FbParameter("@V",ver.Value.Date),new FbParameter("@T",tk),new FbParameter("@K",Next("AVANS","KOD")),new FbParameter("@A",m),new FbParameter("@TS",(int)tak.Value),new FbParameter("@C",ac.Text.Trim()));}RefreshFullTabs();d.DialogResult=DialogResult.OK;d.Close();}catch(Exception ex){MessageBox.Show(ex.Message,"Ek Kazanç ve Kesinti Girişi");}};
        d.Controls.Add(p);d.CancelButton=cancel;d.ShowDialog(this);
    }

    TextBox ClassicTimeBox(string value)=>new(){Text=value,Dock=DockStyle.Fill,BackColor=Color.Black,ForeColor=Color.Lime,Font=new Font(Font,FontStyle.Bold),TextAlign=HorizontalAlignment.Center};
    void AddClassicDialogRow(TableLayoutPanel p,int row,string label,Control c){p.Controls.Add(new Label{Text=label,Dock=DockStyle.Fill,TextAlign=ContentAlignment.MiddleLeft},0,row);p.Controls.Add(c,1,row);}
    DateTime ClassicDateTime(DateTime date,string time){if(!DateTime.TryParseExact(time.Trim(),"HH:mm",CultureInfo.InvariantCulture,DateTimeStyles.None,out var t))throw new Exception("Saat HH:mm biçiminde olmalı.");return date.Date.Add(t.TimeOfDay);}
    static bool IsAnnualLeave(string? value)=>string.Equals(value?.Trim(),"YILLIK İZİN",StringComparison.OrdinalIgnoreCase);
    sealed record LeaveAreaItem(string Name,int Code);
    void ShowPaymentClassic()
    {
        if(currentPk=="")return;var pd=PeriodDates(periodO);using var d=new Form{Text="Maaş ve Mesai Ödemesi",StartPosition=FormStartPosition.CenterParent,Size=new Size(390,310),FormBorderStyle=FormBorderStyle.FixedDialog,MaximizeBox=false,MinimizeBox=false,Font=Font};var p=new TableLayoutPanel{Dock=DockStyle.Fill,ColumnCount=2,RowCount=8,Padding=new Padding(14)};p.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute,145));p.ColumnStyles.Add(new ColumnStyle(SizeType.Percent,100));
        var normal=new TextBox{Dock=DockStyle.Fill};var mesai=new TextBox{Dock=DockStyle.Fill};var nd=new DateTimePicker{Dock=DockStyle.Fill,Format=DateTimePickerFormat.Short};var md=new DateTimePicker{Dock=DockStyle.Fill,Format=DateTimePickerFormat.Short};AddClassicDialogRow(p,0,"Kart Numarası",new TextBox{Text=currentPk,ReadOnly=true,Dock=DockStyle.Fill});AddClassicDialogRow(p,1,"Personel",new TextBox{Text=(f.GetValueOrDefault("AD")?.Text+" "+f.GetValueOrDefault("SOYAD")?.Text).Trim(),ReadOnly=true,Dock=DockStyle.Fill});AddClassicDialogRow(p,2,"Dönem",new TextBox{Text=$"{pd.A:dd.MM.yyyy} - {pd.B:dd.MM.yyyy}",ReadOnly=true,Dock=DockStyle.Fill});AddClassicDialogRow(p,3,"Ödenen Maaş",normal);AddClassicDialogRow(p,4,"Maaş Ödeme Tarihi",nd);AddClassicDialogRow(p,5,"Ödenen Mesai",mesai);AddClassicDialogRow(p,6,"Mesai Ödeme Tarihi",md);
        try{var q=Q("select first 1 NODENEN,NOTARIH,FMODENEN,FMOTARIH from ODEME where PKNO=@PK and BASTAR=@A and BITTAR=@B",new FbParameter("@PK",currentPk),new FbParameter("@A",pd.A),new FbParameter("@B",pd.B));if(q.Rows.Count>0){var r=q.Rows[0];normal.Text=r["NODENEN"]==DBNull.Value?"":Convert.ToDecimal(r["NODENEN"]).ToString("0.00");mesai.Text=r["FMODENEN"]==DBNull.Value?"":Convert.ToDecimal(r["FMODENEN"]).ToString("0.00");if(r["NOTARIH"] is DateTime a)nd.Value=a;if(r["FMOTARIH"] is DateTime b)md.Value=b;}}catch{}
        var bar=new FlowLayoutPanel{Dock=DockStyle.Fill,FlowDirection=FlowDirection.RightToLeft};var cancel=new Button{Text="İptal",Width=95,DialogResult=DialogResult.Cancel};var save=new Button{Text="Kaydet",Width=100,Font=new Font(Font,FontStyle.Bold),ForeColor=Color.Navy};bar.Controls.Add(cancel);bar.Controls.Add(save);p.Controls.Add(bar,0,7);p.SetColumnSpan(bar,2);save.Click+=(_,_)=>{try{decimal n=string.IsNullOrWhiteSpace(normal.Text)?0:PdksValidation.ParseMoney(normal.Text,"Maaş tutarı");decimal m=string.IsNullOrWhiteSpace(mesai.Text)?0:PdksValidation.ParseMoney(mesai.Text,"Mesai tutarı");new PaymentRepository(db).Save(new PaymentRecord(currentPk,pd.A,pd.B,n,nd.Value,m,md.Value));RefreshFullTabs();d.DialogResult=DialogResult.OK;d.Close();}catch(Exception ex){MessageBox.Show(ex.Message,"Maaş ve Mesai Ödemesi");}};d.Controls.Add(p);d.CancelButton=cancel;d.ShowDialog(this);
    }

    DataTable LoadAllDialogPeople()=>Q("select K.PKNO,K.AD,K.SOYAD,K.ICTARIH,coalesce((select AD from GRUP G where G.KOD=K.GRUP),'') GRUPAD,coalesce((select AD from BOLUM B where B.KOD=K.BOLUM),'') BOLUMAD,coalesce((select AD from SERVIS S where S.KOD=K.SERVIS),'') SERVISAD,coalesce((select AD from DURUM D where D.KOD=K.DURUM),'') DURUMAD,coalesce((select AD from GOREV R where R.KOD=K.GOREV),'') GOREVAD,coalesce((select AD from FIRMA F where F.KOD=K.SIRKET),'') FIRMAAD from KIMLIK K order by K.PKNO");
    void FilterIzinPeople(DataTable t,ComboBox[] boxes,DataGridView left,int mode){string[] cols={"GRUPAD","BOLUMAD","SERVISAD","DURUMAD","GOREVAD","FIRMAAD"};var parts=new List<string>();for(int x=0;x<boxes.Length;x++)if(boxes[x].SelectedIndex>0)parts.Add(cols[x]+"='"+boxes[x].Text.Replace("'","''")+"'");if(mode==1)parts.Add("ICTARIH IS NULL");else if(mode==2)parts.Add("ICTARIH IS NOT NULL");t.DefaultView.RowFilter=string.Join(" AND ",parts);left.DataSource=t;}

}
