export const products = [
  {
    code: "S10",
    commercialCode: "ECOFLEX S-10 CLEAR",
    name: "S 10 ŞEFFAF",
    shortName: "S 10 CLEAR",
    type: "SUBAZLI",
    supplier: "URAS",
    defaultLot: "LOT-24",
    lots: [
      { lot: "LOT-24", status: "Aktif", isDefault: true, entryKg: 520, usedKg: 184, invoiceNo: "HMD-2026-118" },
      { lot: "LOT-18", status: "Pasif", note: "Biten", entryKg: 310, usedKg: 310, invoiceNo: "HMD-2025-774" },
      { lot: "LOT-30", status: "Aktif", entryKg: 240, usedKg: 28, invoiceNo: "HMD-2026-142" },
    ],
  },
  {
    code: "S20",
    commercialCode: "ECOFLEX S-20 WHITE",
    name: "S 20 BEYAZ",
    shortName: "S 20 WHITE",
    type: "SUBAZLI",
    supplier: "URAS",
    defaultLot: "LOT-31",
    lots: [
      { lot: "LOT-31", status: "Kritik", isDefault: true, entryKg: 400, usedKg: 358, invoiceNo: "HMD-2026-121" },
      { lot: "LOT-21", status: "Pasif", note: "Biten", entryKg: 280, usedKg: 280, invoiceNo: "HMD-2025-802" },
    ],
  },
  {
    code: "KGC",
    commercialCode: "PIG-RED-KGC",
    name: "KIRMIZI KGC",
    shortName: "KIRMIZI KGC",
    type: "PIGMENT",
    supplier: "KIMYA GRUP",
    defaultLot: "LOT-56",
    lots: [{ lot: "LOT-56", status: "Aktif", isDefault: true, entryKg: 90, usedKg: 36, invoiceNo: "PIG-2026-044" }],
  },
  {
    code: "KBD",
    commercialCode: "PIG-RED-KBD",
    name: "KIRMIZI KBD",
    shortName: "KIRMIZI KBD",
    type: "PIGMENT",
    supplier: "KIMYA GRUP",
    defaultLot: "LOT-75",
    lots: [{ lot: "LOT-75", status: "Aktif", isDefault: true, entryKg: 75, usedKg: 21, invoiceNo: "PIG-2026-051" }],
  },
  {
    code: "ORG",
    commercialCode: "PIG-ORANGE-KG",
    name: "ORANJ KG",
    shortName: "ORANJ KG",
    type: "PIGMENT",
    supplier: "KIMYA GRUP",
    defaultLot: "LOT-88",
    lots: [{ lot: "LOT-88", status: "Aktif", isDefault: true, entryKg: 55, usedKg: 8, invoiceNo: "PIG-2026-058" }],
  },
  {
    code: "STB",
    commercialCode: "GEN-STRETCH-BASE",
    name: "STREÇ BASE",
    shortName: "STREÇ BASE",
    type: "GENEL",
    supplier: "ECOFLEX",
    defaultLot: "LOT-24",
    lots: [{ lot: "LOT-24", status: "Aktif", isDefault: true, entryKg: 220, usedKg: 92, invoiceNo: "GEN-2026-017" }],
  },
  {
    code: "S10STB",
    commercialCode: "GEN-S10-STRETCH",
    name: "S10 STRETCH BASE",
    shortName: "S10 STRETCH BASE",
    type: "GENEL",
    supplier: "ECOFLEX",
    defaultLot: "LOT-24",
    lots: [{ lot: "LOT-24", status: "Aktif", isDefault: true, entryKg: 160, usedKg: 44, invoiceNo: "GEN-2026-020" }],
  },
  {
    code: "ECP-B",
    commercialCode: "ECP-BASE",
    name: "ECOPLAST BASE",
    shortName: "ECOPLAST BASE",
    type: "ECOPLAST",
    supplier: "ECOFLEX",
    defaultLot: "ECP-14",
    lots: [{ lot: "ECP-14", status: "Aktif", isDefault: true, entryKg: 210, usedKg: 35, invoiceNo: "ECP-2026-014" }],
  },
  {
    code: "ECP-W",
    commercialCode: "ECP-WHITE",
    name: "ECOPLAST BEYAZ",
    shortName: "ECOPLAST WHITE",
    type: "ECOPLAST",
    supplier: "ECOFLEX",
    defaultLot: "ECP-21",
    lots: [{ lot: "ECP-21", status: "Aktif", isDefault: true, entryKg: 185, usedKg: 22, invoiceNo: "ECP-2026-021" }],
  },
  {
    code: "BFN",
    commercialCode: "GEN-WHITE-FON",
    name: "BEYAZ FON",
    shortName: "BEYAZ FON",
    type: "GENEL",
    supplier: "ECOFLEX",
    defaultLot: "BF-11",
    lots: [{ lot: "BF-11", status: "Aktif", isDefault: true, entryKg: 180, usedKg: 64, invoiceNo: "GEN-2026-019" }],
  },
];

export const initialRecipeRows = [
  { id: 1, productName: "S 10 ŞEFFAF", totalGr: 155, trial1: 120, trial2: 20, trial3: 15, productionGr: 155, lot: "LOT-24", dyeType: "SUBAZLI" },
  { id: 2, productName: "S 20 BEYAZ", totalGr: 400, trial1: 400, trial2: 0, trial3: 0, productionGr: 400, lot: "LOT-31", dyeType: "SUBAZLI" },
  { id: 3, productName: "KIRMIZI KGC", totalGr: 25, trial1: 15, trial2: 5, trial3: 0, productionGr: 25, lot: "LOT-56", dyeType: "PIGMENT" },
];

export const modelPool = [
  {
    id: "model-a150",
    modelOrderId: "order-a150",
    modelName: "A-150 MODEL",
    company: "TAHA GİYİM",
    orderNo: "A-2026-001",
    dispatchNo: "TIA202600080737",
    incomingQty: 15000,
    printStructure: "Ön + Arka + Sağ Kol + Sol Kol",
    owner: "Mecit Hakan",
    designStatus: "Desen hazır",
    dyehouseStatus: "Reçete bekliyor",
    colorCount: 15,
    undefinedColorCount: 3,
    completedColors: 3,
    lotPending: 1,
    readyColors: 3,
    status: "Reçete bekliyor",
    colors: [
      { id: "a150-ekru", order: 1, label: "1 EKRU", colorName: "EKRU", pantone: "11-0103", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 2, preview: "#e8dcc3" },
      { id: "a150-kirmizi", order: 2, label: "2 KIRMIZI", colorName: "KIRMIZI", pantone: "18-1663", dyeType: "SUBAZLI", version: "v2", saved: true, status: "Lot kontrol", lotStatus: "Kontrol", multiplier: 2, preview: "#b91c1c" },
      { id: "a150-siyah", order: 3, label: "3 SİYAH", colorName: "SİYAH", pantone: "19-0303", dyeType: "PIGMENT", version: "v1", saved: false, status: "Reçete oluştur", lotStatus: "Eksik", multiplier: 1, preview: "#111827" },
      { id: "a150-beyaz", order: 4, label: "4 BEYAZ", colorName: "BEYAZ", pantone: "11-0601", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Gramaj eksik", lotStatus: "Tamam", multiplier: 2, preview: "#f8fafc" },
      { id: "a150-sari", order: 5, label: "5 SARI", colorName: "SARI", pantone: "13-0858", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#facc15" },
      { id: "a150-lacivert", order: 6, label: "6 LACİVERT", colorName: "LACİVERT", pantone: "19-4052", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#1e3a8a" },
      { id: "a150-jc7", order: 7, label: "7 JC7", colorName: "JC7", customerColorCode: "JC7", pantone: "", dyeType: "SUBAZLI", version: "v1", saved: false, status: "Tanımla", lotStatus: "Eksik", multiplier: 1, preview: "#94a3b8" },
      { id: "a150-102a", order: 8, label: "8 102-A", colorName: "102-A", customerColorCode: "102-A", pantone: "", dyeType: "PIGMENT", version: "v1", saved: false, status: "Tanımla", lotStatus: "Eksik", multiplier: 1, preview: "#cbd5e1" },
      { id: "a150-must101", order: 9, label: "9 MUST-101", colorName: "MUST-101", customerColorCode: "MUST-101", pantone: "", dyeType: "SUBAZLI", version: "v1", saved: false, status: "Tanımla", lotStatus: "Eksik", multiplier: 1, preview: "#e2e8f0" },
      { id: "a150-yesil", order: 10, label: "10 YEŞİL", colorName: "YEŞİL", pantone: "16-6340", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#16a34a" },
      { id: "a150-mor", order: 11, label: "11 MOR", colorName: "MOR", pantone: "18-3838", dyeType: "PIGMENT", version: "v1", saved: true, status: "Gramaj eksik", lotStatus: "Tamam", multiplier: 1, preview: "#7e22ce" },
      { id: "a150-gri", order: 12, label: "12 GRİ", colorName: "GRİ", pantone: "17-4402", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#64748b" },
      { id: "a150-turkuaz", order: 13, label: "13 TURKUAZ", colorName: "TURKUAZ", pantone: "15-5519", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#0f766e" },
      { id: "a150-pembe", order: 14, label: "14 PEMBE", colorName: "PEMBE", pantone: "16-2126", dyeType: "PIGMENT", version: "v1", saved: true, status: "Lot kontrol", lotStatus: "Kontrol", multiplier: 1, preview: "#db2777" },
      { id: "a150-kahve", order: 15, label: "15 KAHVE", colorName: "KAHVE", pantone: "18-1142", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#92400e" },
    ],
  },
  {
    id: "model-lmaries",
    modelOrderId: "order-lmaries",
    modelName: "L-MARIES-YD",
    company: "TAHA GİYİM",
    orderNo: "TIA202600080737-01",
    dispatchNo: "TIA202600080737",
    incomingQty: 10830,
    printStructure: "Ön + 2 Kol",
    owner: "Mecit Hakan",
    designStatus: "Kanal onaylı",
    dyehouseStatus: "Gramaj kontrol",
    colorCount: 12,
    undefinedColorCount: 3,
    completedColors: 2,
    lotPending: 1,
    readyColors: 2,
    status: "Gramaj kontrol",
    colors: [
      { id: "lmaries-ekru", order: 1, label: "1 EKRU", colorName: "EKRU", pantone: "11-0103", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#e8dcc3" },
      { id: "lmaries-kirmizi", order: 2, label: "2 KIRMIZI", colorName: "KIRMIZI", pantone: "18-1663", dyeType: "SUBAZLI", version: "v2", saved: true, status: "Lot kontrol", lotStatus: "Kontrol", multiplier: 2, preview: "#b91c1c" },
      { id: "lmaries-beyaz", order: 3, label: "3 BEYAZ", colorName: "BEYAZ", pantone: "11-0601", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Gramaj eksik", lotStatus: "Tamam", multiplier: 1, preview: "#f8fafc" },
      { id: "lmaries-lacivert", order: 4, label: "4 LACİVERT", colorName: "LACİVERT", pantone: "19-4052", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#1e3a8a" },
      { id: "lmaries-jc7", order: 5, label: "5 JC7", colorName: "JC7", customerColorCode: "JC7", pantone: "", dyeType: "SUBAZLI", version: "v1", saved: false, status: "Tanımla", lotStatus: "Eksik", multiplier: 1, preview: "#94a3b8" },
      { id: "lmaries-101", order: 6, label: "6 KIRMIZI-1", colorName: "KIRMIZI-1", customerColorCode: "KIRMIZI-1", pantone: "", dyeType: "PIGMENT", version: "v1", saved: false, status: "Tanımla", lotStatus: "Eksik", multiplier: 1, preview: "#cbd5e1" },
      { id: "lmaries-must", order: 7, label: "7 MUST-101", colorName: "MUST-101", customerColorCode: "MUST-101", pantone: "", dyeType: "SUBAZLI", version: "v1", saved: false, status: "Tanımla", lotStatus: "Eksik", multiplier: 1, preview: "#e2e8f0" },
      { id: "lmaries-sari", order: 8, label: "8 SARI", colorName: "SARI", pantone: "13-0858", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#facc15" },
      { id: "lmaries-yesil", order: 9, label: "9 YEŞİL", colorName: "YEŞİL", pantone: "16-6340", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#16a34a" },
      { id: "lmaries-gri", order: 10, label: "10 GRİ", colorName: "GRİ", pantone: "17-4402", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#64748b" },
      { id: "lmaries-turkuaz", order: 11, label: "11 TURKUAZ", colorName: "TURKUAZ", pantone: "15-5519", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#0f766e" },
      { id: "lmaries-pembe", order: 12, label: "12 PEMBE", colorName: "PEMBE", pantone: "16-2126", dyeType: "PIGMENT", version: "v1", saved: true, status: "Lot kontrol", lotStatus: "Kontrol", multiplier: 1, preview: "#db2777" },
    ],
  },
  {
    id: "model-ponyka",
    modelOrderId: "order-ponyka",
    modelName: "PONYKA",
    company: "TAHA GİYİM",
    orderNo: "PNY-2026-004",
    dispatchNo: "PNY-IRS-004",
    incomingQty: 8500,
    printStructure: "Ön",
    owner: "Ayşe Sorumlu",
    designStatus: "Desen hazır",
    dyehouseStatus: "Hazır",
    colorCount: 3,
    undefinedColorCount: 0,
    completedColors: 3,
    lotPending: 0,
    readyColors: 3,
    status: "Hazır",
    colors: [
      { id: "ponyka-ekru", order: 1, label: "1 EKRU", colorName: "EKRU", pantone: "11-0103", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#e8dcc3" },
      { id: "ponyka-siyah", order: 2, label: "2 SİYAH", colorName: "SİYAH", pantone: "19-0303", dyeType: "PIGMENT", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#111827" },
      { id: "ponyka-beyaz", order: 3, label: "3 BEYAZ", colorName: "BEYAZ", pantone: "11-0601", dyeType: "SUBAZLI", version: "v1", saved: true, status: "Hazır", lotStatus: "Tamam", multiplier: 1, preview: "#f8fafc" },
    ],
  },
];

export const registeredColors = [
  { id: "kirmizi-v1", color: "#c21f32", pantone: "18-1663", customerColorCode: "", name: "KIRMIZI", dyeType: "SUBAZLI", version: "v1", combination: "S10 + S20 + KIRMIZI KGC", modelCount: 3, status: "Aktif", lastModel: "A-150 MODEL" },
  { id: "kirmizi-v2", color: "#b91c1c", pantone: "18-1663", customerColorCode: "", name: "KIRMIZI", dyeType: "SUBAZLI", version: "v2", combination: "S10 + S20 + KBD + ORANJ", modelCount: 5, status: "Aktif", lastModel: "L-MARIES-YD" },
  { id: "kirmizi-pigment", color: "#dc2626", pantone: "18-1663", customerColorCode: "", name: "KIRMIZI", dyeType: "PIGMENT", version: "v1", combination: "KIRMIZI KGC + ORANJ KG", modelCount: 2, status: "Kontrol", lastModel: "M-247" },
  { id: "ekru-v1", color: "#e8dcc3", pantone: "12-0804", customerColorCode: "", name: "EKRU", dyeType: "SUBAZLI", version: "v1", combination: "S10 + BEYAZ FON", modelCount: 4, status: "Aktif", lastModel: "M-245" },
  { id: "jc7-v1", color: "#94a3b8", pantone: "", customerColorCode: "JC7", name: "JC7", dyeType: "SUBAZLI", version: "v1", combination: "S10 + S20", modelCount: 1, status: "Yeni", lastModel: "A-150 MODEL" },
];

export const colorUsageRows = [
  { model: "A-150 MODEL", color: "KIRMIZI", pantone: "18-1663", customerColorCode: "", dyeType: "SUBAZLI", version: "v2", combination: "S10 + S20 + KBD + ORANJ", lastUse: "23.05.2026", status: "Aktif" },
  { model: "L-MARIES-YD", color: "KIRMIZI", pantone: "18-1663", customerColorCode: "", dyeType: "SUBAZLI", version: "v2", combination: "S10 + S20 + KBD + ORANJ", lastUse: "22.05.2026", status: "Aktif" },
  { model: "M-245", color: "EKRU", pantone: "12-0804", customerColorCode: "", dyeType: "SUBAZLI", version: "v1", combination: "S10 + BEYAZ FON", lastUse: "20.05.2026", status: "Aktif" },
  { model: "A-150 MODEL", color: "JC7", pantone: "", customerColorCode: "JC7", dyeType: "SUBAZLI", version: "v1", combination: "S10 + S20", lastUse: "23.05.2026", status: "Yeni" },
];

export const approvedInventory = [
  { code: "ECOFLEX S-10 CLEAR", name: "S 10 ŞEFFAF", shortName: "S 10 CLEAR", company: "URAS", type: "SUBAZLI", useStatus: "Aktif", cas: "Uygun", lcw: "Alındı", msds: "Var", tds: "Var", zdhc: "Var", activeLot: "LOT-24", recipeUsable: "Evet", usage: "Kullanımda", status: "Kullanılabilir" },
  { code: "ECOFLEX S-20 WHITE", name: "S 20 BEYAZ", shortName: "S 20 WHITE", company: "URAS", type: "SUBAZLI", useStatus: "Aktif", cas: "Uygun", lcw: "Alındı", msds: "Var", tds: "Var", zdhc: "Var", activeLot: "LOT-31", recipeUsable: "Evet", usage: "Kritik lot", status: "Stok kritik" },
  { code: "PIG-RED-KGC", name: "KIRMIZI KGC", shortName: "KIRMIZI KGC", company: "KIMYA GRUP", type: "PIGMENT", useStatus: "Aktif", cas: "Uygun", lcw: "Bekliyor", msds: "Var", tds: "Var", zdhc: "Eksik", activeLot: "LOT-56", recipeUsable: "Kontrol", usage: "Kullanımda", status: "Eksik Onay" },
  { code: "PIG-RED-KBD", name: "KIRMIZI KBD", shortName: "KIRMIZI KBD", company: "KIMYA GRUP", type: "PIGMENT", useStatus: "Aktif", cas: "Uygun", lcw: "Alındı", msds: "Var", tds: "Var", zdhc: "Var", activeLot: "LOT-75", recipeUsable: "Evet", usage: "Kullanımda", status: "Kullanılabilir" },
  { code: "PIG-ORANGE-KG", name: "ORANJ KG", shortName: "ORANJ KG", company: "KIMYA GRUP", type: "PIGMENT", useStatus: "Aktif", cas: "Uygun", lcw: "Alındı", msds: "Var", tds: "Var", zdhc: "Var", activeLot: "LOT-88", recipeUsable: "Evet", usage: "Kullanımda", status: "Kullanılabilir" },
  { code: "GEN-STRETCH-BASE", name: "STREÇ BASE", shortName: "STREÇ BASE", company: "ECOFLEX", type: "GENEL", useStatus: "Aktif", cas: "Uygun", lcw: "Alındı", msds: "Var", tds: "Var", zdhc: "Var", activeLot: "LOT-24", recipeUsable: "Evet", usage: "Genel gider", status: "Kullanılabilir" },
  { code: "GEN-S10-STRETCH", name: "S10 STRETCH BASE", shortName: "S10 STRETCH BASE", company: "ECOFLEX", type: "GENEL", useStatus: "Aktif", cas: "Uygun", lcw: "Alındı", msds: "Var", tds: "Var", zdhc: "Var", activeLot: "LOT-24", recipeUsable: "Evet", usage: "Genel gider", status: "Kullanılabilir" },
  { code: "ECP-BASE", name: "ECOPLAST BASE", shortName: "ECOPLAST BASE", company: "ECOFLEX", type: "ECOPLAST", useStatus: "Aktif", cas: "Uygun", lcw: "Alındı", msds: "Var", tds: "Var", zdhc: "Var", activeLot: "ECP-14", recipeUsable: "Evet", usage: "Kullanımda", status: "Kullanılabilir" },
  { code: "ECP-WHITE", name: "ECOPLAST BEYAZ", shortName: "ECOPLAST WHITE", company: "ECOFLEX", type: "ECOPLAST", useStatus: "Aktif", cas: "Uygun", lcw: "Alındı", msds: "Var", tds: "Var", zdhc: "Var", activeLot: "ECP-21", recipeUsable: "Evet", usage: "Kullanımda", status: "Kullanılabilir" },
  { code: "GEN-WHITE-FON", name: "BEYAZ FON", shortName: "BEYAZ FON", company: "ECOFLEX", type: "GENEL", useStatus: "Aktif", cas: "Uygun", lcw: "Alındı", msds: "Var", tds: "Var", zdhc: "Var", activeLot: "BF-11", recipeUsable: "Evet", usage: "Genel gider", status: "Kullanılabilir" },
];

export const documents = [
  { product: "S 10 ŞEFFAF", supplier: "URAS", type: "ZDHC", no: "ZDHC-241", validUntil: "31.12.2026", uploadDate: "12.04.2026", lot: "LOT-24", audit: "Ekolojik", status: "Onaylı" },
  { product: "S 20 BEYAZ", supplier: "URAS", type: "MSDS", no: "MSDS-882", validUntil: "15.11.2026", uploadDate: "10.04.2026", lot: "LOT-31", audit: "LCW", status: "Onaylı" },
  { product: "KIRMIZI KGC", supplier: "KIMYA GRUP", type: "LCW Onay / Deklarasyon", no: "LCW-102", validUntil: "Bekliyor", uploadDate: "18.05.2026", lot: "LOT-56", audit: "LCW", status: "Eksik" },
  { product: "ORANJ KG", supplier: "KIMYA GRUP", type: "TDS", no: "TDS-557", validUntil: "31.01.2027", uploadDate: "08.05.2026", lot: "LOT-88", audit: "Teknik", status: "Onaylı" },
];

export const reportRows = [
  { type: "Model Renk Reçete Raporu", record: "A-150 MODEL / KIRMIZI", date: "23.05.2026", owner: "Boyahane", status: "Hazır" },
  { type: "Lot Hareket Raporu", record: "S 20 BEYAZ / LOT-31", date: "23.05.2026", owner: "Depo", status: "Kontrol" },
  { type: "Eksik Evrak Raporu", record: "KIRMIZI KGC / LCW", date: "22.05.2026", owner: "Denetim", status: "Eksik" },
  { type: "Model Boya Gideri Raporu", record: "STREÇ BASE / A-150", date: "21.05.2026", owner: "Üretim", status: "Hazır" },
];
